import ExcelJS from 'exceljs';
import type {z} from 'zod';
import {AppError} from '../../contracts/src/index.js';
import {accountabilitySchema} from '../../contracts/src/evidence.js';
import {mappingAccountSchema} from '../../contracts/src/analysis.js';
import {Finance,type Context} from './finance.js';
import {Evidence} from './evidence.js';
export function excelAmount(value:string):number|string{const n=BigInt(value),abs=n<0n?-n:n;if(abs<=999999999999999n)return Number(n)/100;return `${n<0n?'-':''}${abs/100n}.${String(abs%100n).padStart(2,'0')}`;}
type Cell=string|number|null|undefined;
export class Accountant {
 constructor(public f:Finance,public evidence=new Evidence(f)){}
 async mappings(ctx:Context){return this.f.transaction(ctx,async t=>{this.f.permit(t,'reports:view');return {items:(await t.db.query('SELECT c.id,c.name,c.direction,m.debit_code,m.credit_code,m.notes,coalesce(m.version,1) AS version FROM app.categories c LEFT JOIN app.accounting_mappings m ON m.category_id=c.id ORDER BY c.name')).rows};});}
 async saveMapping(ctx:Context,d:z.infer<typeof mappingAccountSchema>){return this.f.command(ctx,'context:update',{mapping:d},async t=>{this.f.permit(t,'categories:update');const old=(await t.db.query('SELECT * FROM app.accounting_mappings WHERE category_id=$1 FOR UPDATE',[d.category_id])).rows[0]??{version:1};this.f.version(t,old);const result=(await t.db.query('INSERT INTO app.accounting_mappings(category_id,debit_code,credit_code,notes,version) VALUES($1,$2,$3,$4,2) ON CONFLICT(category_id) DO UPDATE SET debit_code=$2,credit_code=$3,notes=$4,version=app.accounting_mappings.version+1 RETURNING *',[d.category_id,d.debit_code,d.credit_code,d.notes])).rows[0];await this.f.audit(t,'accounting_mapping',d.category_id,'save',old,d);return result;});}
 async data(ctx:Context,q:z.infer<typeof accountabilitySchema>){return this.f.transaction(ctx,async t=>{
  this.f.permit(t,'exports:create');this.f.permit(t,'parties:view');const report=await this.evidence.reportTx(t,{...q,after:undefined},5000);if(report.next)throw new AppError(422,'EXPORT_LIMIT','Mais de 5.000 transações. Reduza o período ou escolha uma conta.');
  const ids=report.items.map(e=>e.id);const entries=(await t.db.query(`SELECT e.id,e.title,e.direction,e.amount_minor,e.due_on,e.competence_on,e.status,a.name AS account,l.name AS company,l.cnpj,p.name AS supplier,p.document AS supplier_document,ec.justification,ec.status AS review_status,ec.reviewed_at,u.display_name AS reviewer,
   (SELECT string_agg(s.settled_on::text,', ' ORDER BY s.id) FROM app.settlements s WHERE s.entry_id=e.id AND s.reversal_of IS NULL AND NOT EXISTS(SELECT 1 FROM app.settlements rev WHERE rev.reversal_of=s.id)) AS settled_on,
   (SELECT coalesce(jsonb_agg(jsonb_build_object('kind',d.kind,'name',d.name)),'[]') FROM app.entry_dimensions ed JOIN app.context_dimensions d ON d.id=ed.dimension_id WHERE ed.entry_id=e.id) AS dimensions,
   (SELECT coalesce(jsonb_agg(jsonb_build_object('id',r.id,'filename',b.filename,'description',r.payload->>'title','date',r.payload->>'date')),'[]') FROM app.import_rows r JOIN app.import_batches b ON b.id=r.batch_id WHERE r.entry_id=e.id AND r.status='matched') AS movements
   FROM app.entries e JOIN app.accounts a ON a.id=e.account_id JOIN app.legal_entities l ON l.id=a.legal_entity_id LEFT JOIN app.parties p ON p.id=e.party_id LEFT JOIN app.entry_context ec ON ec.entry_id=e.id LEFT JOIN app.users u ON u.id=ec.reviewed_by WHERE e.id=ANY($1::bigint[]) ORDER BY e.due_on,e.id`,[ids])).rows;
  const allocations=(await t.db.query("SELECT al.entry_id,al.id,al.amount_minor,al.reporting_group,c.name AS category,cc.name AS cost_center,m.debit_code,m.credit_code,m.notes FROM app.entry_allocations al LEFT JOIN app.categories c ON c.id=al.category_id LEFT JOIN app.cost_centers cc ON cc.id=al.cost_center_id LEFT JOIN app.accounting_mappings m ON m.category_id=c.id WHERE al.entry_id=ANY($1::bigint[]) ORDER BY al.entry_id,al.id LIMIT 20001",[ids])).rows;if(allocations.length>20000)throw new AppError(422,'EXPORT_LIMIT','Mais de 20.000 rateios. Reduza o período.');
  const linked=(await t.db.query('SELECT DISTINCT document_id AS id FROM app.entry_documents WHERE entry_id=ANY($1::bigint[]) ORDER BY document_id',[ids])).rows.map(r=>r.id);
  if(linked.length>10000)throw new AppError(422,'EXPORT_LIMIT','Mais de 10.000 documentos vinculados. Reduza o período.');
  const documents=(await t.db.query(`SELECT d.id,d.filename,d.fields,d.status,d.content_hash AS hash,
   ARRAY(SELECT ed.entry_id::text FROM app.entry_documents ed WHERE ed.document_id=d.id AND ed.entry_id=ANY($1::bigint[])) AS entries,
   coalesce((SELECT jsonb_agg(jsonb_build_object('url',dc.url,'status',dc.status,'checked_at',dc.checked_at)) FROM app.document_copies dc JOIN app.provider_connections c ON c.id=dc.connection_id WHERE dc.document_id=d.id AND c.user_id=$3 AND c.status='connected' AND dc.status='available'),'[]') AS copies
   FROM app.documents d JOIN app.accounts a ON a.id=d.account_id WHERE d.id=ANY($2::bigint[]) AND ($4 OR(a.id=ANY($5::bigint[]) AND a.legal_entity_id=ANY($6::bigint[]) AND NOT EXISTS(SELECT 1 FROM app.entry_documents ed JOIN app.entries e ON e.id=ed.entry_id WHERE ed.document_id=d.id AND (NOT(e.direction=ANY($7::text[])) OR EXISTS(SELECT 1 FROM app.entry_allocations al WHERE al.entry_id=e.id AND NOT(al.reporting_group=ANY($8::text[]))))))) ORDER BY d.id`,[ids,linked,ctx.actor,t.policy.is_owner,t.policy.account_ids,t.policy.legal_entity_ids,t.policy.directions,t.policy.groups])).rows as {id:string;filename:string;fields:Record<string,string>;status:string;hash:string;entries:string[];copies:{url:string;status:string}[]}[];
  if(documents.length!==linked.length)throw new AppError(403,'EXPORT_SCOPE','Há comprovantes fora do seu acesso. Revise o escopo antes de exportar.');
  const values:unknown[]=[t.policy.is_owner,t.policy.account_ids,t.policy.legal_entity_ids,q.from,q.to,t.policy.directions];let filter="($1 OR(a.id=ANY($2::bigint[]) AND a.legal_entity_id=ANY($3::bigint[]))) AND r.payload->>'date' BETWEEN $4 AND $5 AND ($1 OR r.payload->>'direction'=ANY($6::text[]))";
  if(q.account_id){values.push(q.account_id);filter+=` AND a.id=$${values.length}`;}if(q.legal_entity_id){values.push(q.legal_entity_id);filter+=` AND a.legal_entity_id=$${values.length}`;}
  const movements=(await t.db.query(`SELECT r.id,r.payload,r.status,r.error,r.entry_id,r.settlement_id,b.filename,a.name AS account,l.name AS company,l.cnpj,EXISTS(SELECT 1 FROM app.settlements rev WHERE rev.reversal_of=r.settlement_id) AS reversed FROM app.import_rows r JOIN app.import_batches b ON b.id=r.batch_id JOIN app.accounts a ON a.id=b.account_id JOIN app.legal_entities l ON l.id=a.legal_entity_id WHERE b.kind IN('xlsx','ofx') AND ${filter} ORDER BY r.payload->>'date',r.id LIMIT 5001`,values)).rows;if(movements.length>5000)throw new AppError(422,'EXPORT_LIMIT','Mais de 5.000 movimentos. Reduza o período.');
  const contacts=q.include_contacts==='true'?(await t.db.query('SELECT ec.entry_id,p.name,p.email,pc.emails FROM app.entry_contacts ec JOIN app.parties p ON p.id=ec.party_id LEFT JOIN app.party_context pc ON pc.party_id=p.id WHERE ec.entry_id=ANY($1::bigint[]) ORDER BY ec.entry_id,p.name',[ids])).rows:[];
  const events=t.policy.is_owner||t.policy.permissions.includes('integrations:view')?(await t.db.query("SELECT ee.entry_id,ev.title,ev.start_on,ev.payload->>'url' AS url FROM app.entry_events ee JOIN app.external_events ev ON ev.id=ee.event_id JOIN app.provider_connections c ON c.id=ev.connection_id WHERE ee.entry_id=ANY($1::bigint[]) AND c.user_id=$2 AND c.status='connected' AND c.settings->'calendars' ? ev.calendar_id AND ev.payload->>'status' IN('confirmed','tentative')",[ids,ctx.actor])).rows:[];
  const activities=(await t.db.query('SELECT ea.entry_id,a.title,a.event_on FROM app.entry_planned_activities ea JOIN app.planned_activities a ON a.id=ea.activity_id WHERE ea.entry_id=ANY($1::bigint[]) AND a.actor_id=$2',[ids,ctx.actor])).rows;
  await this.f.audit(t,'export','0','accountant',null,{from:q.from,to:q.to,account:q.account_id,company:q.legal_entity_id,entries:entries.length,include_contacts:q.include_contacts});return {report,entries,allocations,documents,movements,contacts,events,activities};
 });}
 async workbook(ctx:Context,q:z.infer<typeof accountabilitySchema>){const data=await this.data(ctx,q);const wb=new ExcelJS.Workbook();wb.creator='Black Finance';wb.created=new Date();
  const sheet=(name:string,headers:string[],rows:Cell[][],moneyColumns:number[]=[])=>{const ws=wb.addWorksheet(name,{views:[{state:'frozen',ySplit:1}]});ws.addRow(headers);for(const row of rows)ws.addRow(row.map(v=>v??''));ws.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};ws.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF104238'}};ws.getRow(1).height=28;ws.autoFilter={from:{row:1,column:1},to:{row:Math.max(1,rows.length+1),column:headers.length}};ws.columns.forEach((c,i)=>{c.width=Math.min(55,Math.max(18,headers[i]!.length+3));c.alignment={vertical:'top',wrapText:true};});for(const col of moneyColumns)ws.getColumn(col).numFmt='#,##0.00;[Red]-#,##0.00';return ws;};
  const dimension=(e:typeof data.entries[number],kind:string)=>(e.dimensions as {kind:string;name:string}[]).filter(d=>d.kind===kind).map(d=>d.name).join(' | ');
  sheet('Leia primeiro',['Item','Informação'],[['Período',`${q.from} a ${q.to}`],['Base dos lançamentos','Vencimento; inclui pagos e pendentes, exclui cancelados. Não é arquivo de escrituração automática.'],['Base do extrato','Data bancária; todos os movimentos das contas/CNPJs e período selecionados. Os demais filtros de classificação aplicam-se aos lançamentos.'],['Como usar','Conferir lançamentos, rateios, comprovantes e pendências. O contador valida contas, competência e escrituração.'],['Contas contábeis','Débito/crédito vêm do mapeamento informado pela organização; vazio significa pendente.'],['Valores','BRL. Centavos exatos também são exportados. Valores além de 15 dígitos são texto para evitar arredondamento do Excel.'],['Vínculos','Instituições, programas e pessoas são contexto; não multiplicam valores. Rateios contêm a distribuição monetária.'],['Links Drive','Links privados disponíveis na conexão de quem exportou. O contador precisa receber permissão de acesso separadamente.'],['Gráficos','A aba Resumo contém os dados para gráficos editáveis. Na plataforma, copie/baixe o gráfico como PNG e cole no Excel.'],['Dados pessoais',q.include_contacts==='true'?'Contatos incluídos por escolha explícita.':'Nomes e e-mails de participantes omitidos. Fornecedor fiscal mantido para identificação do lançamento.'],['Limites',`Até 5.000 transações, 5.000 movimentos e 20.000 rateios. ${data.entries.length} transações exportadas.`]]);
  sheet('Lançamentos',['ID','Empresa','CNPJ','Conta','Descrição','Entrada/saída','Valor BRL','Valor exato centavos','Vencimento','Competência','Realização','Situação','Fornecedor','CPF/CNPJ fornecedor','Programa','Instituição','Área','Atividade','Finalidade','Fonte de recurso','Justificativa','Revisão','Revisor','Data revisão','Movimentos vinculados'],data.entries.map(e=>[e.id,e.company,e.cnpj,e.account,e.title,e.direction==='income'?'Entrada':'Saída',excelAmount(e.amount_minor),e.amount_minor,e.due_on,e.competence_on,e.settled_on,e.status,e.supplier,e.supplier_document,...['program','institution','area','activity','purpose','funding'].map(k=>dimension(e,k)),e.justification,e.review_status,e.reviewer,e.reviewed_at?new Date(e.reviewed_at).toISOString():'',e.movements.map((m:{id:string})=>m.id).join(', ')]),[7]);
  sheet('Rateios e contas',['Transação ID','Rateio ID','Valor BRL','Valor exato centavos','Grupo DRE','Categoria','Centro de custo','Conta débito (a validar)','Conta crédito (a validar)','Orientação contábil'],data.allocations.map(a=>[a.entry_id,a.id,excelAmount(a.amount_minor),a.amount_minor,a.reporting_group,a.category,a.cost_center,a.debit_code,a.credit_code,a.notes]),[3]);
  sheet('Extrato importado',['Movimento ID','Arquivo','Empresa','CNPJ','Conta','Data','Descrição original','Entrada/saída','Valor BRL','Centavos exatos','Identificador bancário','Situação','Transação ID','Liquidação revertida','Erro'],data.movements.map(r=>[r.id,r.filename,r.company,r.cnpj,r.account,r.payload.date,r.payload.title,r.payload.direction==='income'?'Entrada':'Saída',excelAmount(r.payload.amount_minor||'0'),r.payload.amount_minor,r.payload.external_id,r.status,r.entry_id,r.reversed?'Sim':'Não',r.error]),[9]);
  sheet('Comprovantes',['Documento ID','Arquivo','Transações','Tipo','Número','Fornecedor','CPF/CNPJ','Emissão','Valor BRL','Revisão','Hash original','Link Drive','Situação Drive'],data.documents.map(d=>[d.id,d.filename,d.entries.join(', '),d.fields.type,d.fields.number,d.fields.supplier,d.fields.tax_id,d.fields.issued_on,d.fields.total_minor?excelAmount(d.fields.total_minor):'',d.status,d.hash,d.copies.map(c=>c.url).join('\n'),d.copies.length?'Disponível na última verificação':'Sem cópia disponível nesta conexão']),[9]);
  sheet('Agenda e atividades',['Transação ID','Origem','Data','Título','Link'],[...data.events.map(e=>[e.entry_id,'Google Calendar',e.start_on,e.title,e.url] as Cell[]),...data.activities.map(a=>[a.entry_id,'Cadastro interno',a.event_on,a.title,''] as Cell[])]);
  const entryMap=new Map(data.report.items.map(e=>[e.id,e]));sheet('Pendências',['Transação ou movimento','Pendência'],[...data.entries.flatMap(e=>{const state=entryMap.get(e.id)!;return [...(!state.has_document?[[`Transação ${e.id}`,'Sem comprovante']]:[]),...(!state.documentation_complete?[[`Transação ${e.id}`,'Documentação completa ainda não declarada']]:[]),...(!state.reconciled?[[`Transação ${e.id}`,'Não conciliada']]:[]),...(e.review_status!=='confirmed'?[[`Transação ${e.id}`,'Contexto pendente']]:[])];}),...data.allocations.filter(a=>!a.debit_code||!a.credit_code).map(a=>[`Transação ${a.entry_id}, rateio ${a.id}`,'Mapeamento contábil incompleto']),...data.movements.filter(r=>r.status!=='matched'||r.reversed).map(r=>[`Movimento ${r.id}`,r.reversed?'Liquidação revertida':r.status])]);
  sheet('Resumo',['Agrupamento','Despesas BRL','Centavos exatos'],data.report.groups.map(g=>[g.name,excelAmount(g.amount_minor),g.amount_minor]),[2]);
  if(q.include_contacts==='true')sheet('Contatos',['Transação ID','Nome','E-mail','Outros e-mails'],data.contacts.map(c=>[c.entry_id,c.name,c.email,(c.emails??[]).join(', ')]));
  const buffer=Buffer.from(await wb.xlsx.writeBuffer());if(buffer.length>3000000)throw new AppError(422,'EXPORT_LIMIT','O pacote ultrapassou 3 MB. Reduza o período ou escolha uma conta.');return {filename:`black-finance-contador-${q.from}-${q.to}.xlsx`,mime:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',base64:buffer.toString('base64'),entries:data.entries.length};
 }
}
