import {z} from 'zod';
import {AppError} from '../../contracts/src/index.js';
import {entrySchema} from '../../contracts/src/finance.js';
import {proposalDraftSchema,plannedActivitySchema,type ProposalDraft} from '../../contracts/src/analysis.js';
import {Finance,type Context,type Tx} from './finance.js';
import {Evidence} from './evidence.js';
import {InternalModules} from './modules.js';

const fail=(message:string,status=422):never=>{throw new AppError(status,'ANALYSIS_VALIDATION',message);};
export const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9@.]+/g,' ').trim();
const mentions=(source:string,term:string)=>normalize(term).length>=4&&normalize(source).includes(normalize(term));
export const specialMovement=(title:string)=>/transferencia entre contas|aplicacao|resgate|saldo inicial|saldo anterior/.test(normalize(title));
const unique=(ids:string[])=>[...new Set(ids)];
type Person={name:string;email:string;source:string};

export class Analysis {
 readonly evidence:Evidence;readonly modules:InternalModules;
 constructor(public f:Finance){this.evidence=new Evidence(f);this.modules=new InternalModules(f);}
 async row(t:Tx,batchId:string,rowId:string,lock=false){
  this.f.permit(t,'imports:view');this.f.permit(t,'reconciliation:view');
  const batch=await this.modules.scoped(t,'import_batches',batchId,lock);
  if(!['xlsx','ofx'].includes(batch.kind))fail('Escolha um extrato bancário XLSX ou OFX.');
  const row=(await t.db.query(`SELECT * FROM app.import_rows WHERE id=$1 AND batch_id=$2${lock?' FOR UPDATE':''}`,[rowId,batchId])).rows[0];
  if(!row||!this.f.allowedEntry(t,row.payload.direction,['unclassified']))fail('Movimento indisponível.',404);
  return {batch,row};
 }
 async permitted(t:Tx,batchId:string,rowId:string){const data=await this.row(t,batchId,rowId);for(const p of ['entries:view','documents:view','context:view','parties:view'])this.f.permit(t,p);return data;}
 async candidates(t:Tx,accountId:string,bank:{amount_minor:string;direction:string;date:string}){
  const rows=(await t.db.query("SELECT e.* FROM app.entries e WHERE e.account_id=$1 AND e.amount_minor=$2 AND e.direction=$3 AND e.status<>'cancelled' AND (e.due_on BETWEEN $4::date-7 AND $4::date+7 OR EXISTS(SELECT 1 FROM app.settlements s WHERE s.entry_id=e.id AND s.settled_on=$4)) ORDER BY e.id DESC LIMIT 31",[accountId,bank.amount_minor,bank.direction,bank.date])).rows;
  const visible=[];for(const e of rows){try{await this.f.checkEntry(t,e);const match=(await t.db.query('SELECT r.id FROM app.import_rows r WHERE r.entry_id=$1 AND r.status=$2 LIMIT 1',[e.id,'matched'])).rows[0];visible.push({...e,already_matched:!!match});}catch(e){if(!(e instanceof AppError)||e.statusCode!==404)throw e;}}
  return visible;
 }
 async analyze(ctx:Context,batchId:string,rowId:string){return this.f.command(ctx,'reconciliation:update',{operation:'analyze',batchId,rowId},async t=>{
  const {row,batch}=await this.row(t,batchId,rowId,true);if(row.status!=='pending')fail('Este movimento já foi revisado.',409);
  const existing=(await t.db.query('SELECT * FROM app.analysis_proposals WHERE row_id=$1 AND actor_id=$2',[rowId,ctx.actor])).rows[0];
  if(existing)return existing;
  const bank=row.payload,entries=await this.candidates(t,batch.account_id,bank);
  const documents=[];
  const docs=(await t.db.query("SELECT id FROM app.documents WHERE account_id=$1 AND status<>'rejected' AND (fields->>'total_minor'=$2 OR fields->>'issued_on' BETWEEN ($3::date-7)::text AND ($3::date+7)::text) ORDER BY id DESC LIMIT 30",[batch.account_id,bank.amount_minor,bank.date])).rows;
  for(const ref of docs){try{const d=await this.evidence.document(t,ref.id);const reasons=[d.fields.total_minor===bank.amount_minor?'Valor igual ao extrato':'Valor diferente: confira rateio ou pagamento parcial',d.fields.issued_on===bank.date?'Data igual':'Data diferente ou ausente'];const linked=(await t.db.query('SELECT 1 FROM app.entry_documents WHERE document_id=$1 LIMIT 1',[d.id])).rowCount;
   documents.push({id:d.id,version:d.version,filename:d.filename,mime:d.mime,fields:d.fields,status:d.status,reasons,linked:!!linked,compatible:d.fields.total_minor===bank.amount_minor&&!!d.fields.issued_on&&Math.abs(Date.parse(d.fields.issued_on)-Date.parse(bank.date))<=7*86400000});
  }catch(e){if(!(e instanceof AppError)||e.statusCode!==404)throw e;}}
  const usable=documents.filter(d=>d.compatible&&!d.linked);const selectedDoc=usable.length===1?usable[0]:undefined;
  const canCalendar=t.policy.is_owner||t.policy.permissions.includes('integrations:view');
  const events=canCalendar?(await t.db.query("SELECT ev.id,ev.title,ev.start_on,ev.payload,ev.seen_at FROM app.external_events ev JOIN app.provider_connections c ON c.id=ev.connection_id WHERE c.user_id=$1 AND c.status='connected' AND c.settings->'calendars' ? ev.calendar_id AND ev.start_on BETWEEN $2::date-1 AND $2::date+1 AND ev.payload->>'status' IN('confirmed','tentative') ORDER BY ev.start_on,ev.id LIMIT 30",[ctx.actor,bank.date])).rows:[];
  const activities=(await t.db.query("SELECT * FROM app.planned_activities WHERE actor_id=$1 AND status='active' AND event_on BETWEEN $2::date-1 AND $2::date+1 ORDER BY id DESC LIMIT 30",[ctx.actor,bank.date])).rows;
  const text=[bank.title,selectedDoc?.fields.supplier,selectedDoc?.fields.description].filter(Boolean).join(' ');
  const eventMatches=events.filter(e=>e.start_on===bank.date&&(mentions(text,e.title)||mentions(`${e.title} ${e.payload.description??''}`,String(selectedDoc?.fields.supplier??''))));
  const activityMatches=activities.filter(e=>e.event_on===bank.date&&mentions(text,e.title));
  const sameDayEvents=events.filter(ev=>ev.start_on===bank.date),sameDayActivities=activities.filter(ev=>ev.event_on===bank.date);const event=eventMatches.length===1?eventMatches[0]:sameDayEvents.length===1?sameDayEvents[0]:undefined,activity=activityMatches.length===1?activityMatches[0]:sameDayActivities.length===1?sameDayActivities[0]:undefined;
  const sourceText=[text,event?.title,event?.payload.description,activity?.title,activity?.description].filter(Boolean).join(' ');
  const dimensions=(await t.db.query("SELECT * FROM app.context_dimensions WHERE status='active' ORDER BY id LIMIT 1000")).rows;
  const categories=(await t.db.query("SELECT * FROM app.categories WHERE status='active' AND direction=$1 ORDER BY id LIMIT 1000",[bank.direction])).rows.filter(c=>this.f.allowedEntry(t,bank.direction,[c.reporting_group]));
  const parties=(await t.db.query("SELECT p.*,coalesce(pc.emails,'[]') AS other_emails FROM app.parties p LEFT JOIN app.party_context pc ON pc.party_id=p.id WHERE p.status='active' ORDER BY p.id LIMIT 1000")).rows;
  const supplier=String(selectedDoc?.fields.supplier??'');const matchingParties=parties.filter(p=>supplier&&normalize(p.name)===normalize(supplier)||selectedDoc?.fields.tax_id&&normalize(p.document)===normalize(selectedDoc.fields.tax_id));
  const keywords=[['alimentacao',['restaurante','almoco','alimentacao','refeicao']],['combustivel',['combustivel','gasolina','etanol','posto']],['estacionamento',['estacionamento','parking']],['transporte',['uber','99app','taxi','transporte']],['tarifa',['tarifa','taxa bancaria']]];
  const categoryMatches=categories.filter(c=>mentions(sourceText,c.name)||keywords.some(([name,words])=>typeof name==='string'&&Array.isArray(words)&&normalize(c.name).includes(name)&&words.some(w=>mentions(sourceText,w))));
  const rules=(await t.db.query('SELECT * FROM app.classification_rules WHERE actor_id=$1 AND account_id=$2 AND direction=$3 AND active ORDER BY length(term) DESC,id DESC',[ctx.actor,batch.account_id,bank.direction])).rows.filter(r=>mentions(sourceText,r.term));
  const rule=rules.length===1?rules[0]:undefined;
  const people:Person[]=[];for(const d of selectedDoc?[selectedDoc]:[]){for(const email of d.fields.emails??[])people.push({name:'',email,source:`Nota ${d.filename}`});for(const name of d.fields.names??[])people.push({name,email:'',source:`Nota ${d.filename}`});}
  for(const ev of event?[event]:[]){for(const p of [...(ev.payload.attendees??[]),ev.payload.organizer??{}])if(p.email||p.displayName)people.push({name:String(p.displayName??''),email:String(p.email??''),source:`Evento ${ev.title} — convite não comprova presença`});}
  for(const p of activity?.participants??[])people.push({...p,source:`Atividade ${activity.title}`});
  const contactIds=people.flatMap(person=>{const matches=parties.filter(p=>person.email&&[p.email,...p.other_emails].map((s:string)=>s.toLowerCase()).includes(person.email.toLowerCase())||person.name&&normalize(p.name)===normalize(person.name));return matches.length===1?[String(matches[0].id)]:[];});
  const candidates=entries.filter(e=>!e.already_matched);const matching=candidates.length===1?candidates[0]:undefined;
  const draft=proposalDraftSchema.parse({title:supplier?`${bank.direction==='expense'?'Pagamento':'Recebimento'} · ${supplier}`.slice(0,240):bank.title,mode:matching?'match':'create',entry_id:matching?.id??null,category_id:rule?.defaults.category_id??(categoryMatches.length===1?categoryMatches[0].id:null),party_id:rule?.defaults.party_id??(matchingParties.length===1?matchingParties[0].id:null),new_party:matchingParties.length===0&&supplier?{name:supplier,email:selectedDoc?.fields.emails?.[0]??'',document:selectedDoc?.fields.tax_id??''}:null,competence_on:selectedDoc?.fields.issued_on??bank.date,document_ids:selectedDoc?[selectedDoc.id]:[],event_ids:event?[event.id]:[],activity_ids:activity?[activity.id]:[],dimension_ids:unique([...(rule?.defaults.dimension_ids??[]),...dimensions.filter(d=>mentions(sourceText,d.name)).map(d=>d.id),...(activity?.dimension_ids??[])]),party_ids:unique(contactIds),justification:activity?.description||event?.payload.description?.slice(0,5000)||'',remember_term:''});
  const sources={bank,documents,entries,events,activities,people,rules:rules.map(r=>({id:r.id,term:r.term})),engine:'rules-v1',warnings:[...(!selectedDoc?['Nenhuma nota única identificada. Escolha entre as alternativas ou aprove sem comprovante.']:[]),...(event&&!eventMatches.length?['Evento sugerido apenas por ser o único do dia. Confirme a relação antes de aprovar.']:[]),...(activity&&!activityMatches.length?['Atividade sugerida apenas pela data; confirme o contexto.']:[]),...(events.length&&!event?['Eventos próximos são alternativas; selecione o contexto correto.']:[]),...(entries.length?['Há transações com mesmo valor no período. Confira antes de criar outra.']:[]),...(specialMovement(bank.title)?['Possível transferência, aplicação ou resgate: use o fluxo específico quando aplicável.']:[]),...(rules.length>1?['Mais de uma regra aplicável; classificação exige escolha.']:[]),'O extrato determina valor, direção e data da realização. A análise não altera saldo.']};
  const result=(await t.db.query('INSERT INTO app.analysis_proposals(row_id,actor_id,draft,sources) VALUES($1,$2,$3,$4) RETURNING *',[rowId,ctx.actor,draft,sources])).rows[0];await this.f.audit(t,'analysis',result.id,'analyze',null,{row_id:rowId,engine:sources.engine});return result;
 },t=>this.permitted(t,batchId,rowId).then(()=>{}));}
 async proposal(t:Tx,batchId:string,id:string,lock=false){
  const p=(await t.db.query(`SELECT p.* FROM app.analysis_proposals p JOIN app.import_rows r ON r.id=p.row_id WHERE p.id=$1 AND p.actor_id=$2 AND r.batch_id=$3${lock?' FOR UPDATE OF p':''}`,[id,t.ctx.actor,batchId])).rows[0];if(!p)fail('Proposta não encontrada.',404);
  await this.permitted(t,batchId,p.row_id);
  for(const doc of p.sources.documents)await this.evidence.document(t,doc.id);
  for(const e of p.sources.entries)await this.evidence.entry(t,e.id);
  // Private event payloads must disappear immediately when access or selection changes.
  const calendars=t.policy.is_owner||t.policy.permissions.includes('integrations:view');
  const authorized=calendars?(await t.db.query("SELECT ev.id FROM app.external_events ev JOIN app.provider_connections c ON c.id=ev.connection_id WHERE ev.id=ANY($1::bigint[]) AND c.user_id=$2 AND c.status='connected' AND c.settings->'calendars' ? ev.calendar_id AND ev.payload->>'status' IN('confirmed','tentative')",[p.sources.events.map((e:{id:string})=>e.id),t.ctx.actor])).rows.map(e=>e.id):[];
  const revoked=p.sources.events.some((e:{id:string})=>!authorized.includes(e.id));
  if(revoked){p.context_stale=true;p.sources={...p.sources,events:[],people:[],warnings:[...p.sources.warnings,'Agenda desconectada ou evento indisponível. Reanalise para atualizar o contexto.']};p.draft={...p.draft,event_ids:[],justification:'',new_contacts:[],party_ids:[],dimension_ids:[]};}
  return p;
 }
 async list(ctx:Context,batchId:string){return this.f.transaction(ctx,async t=>{await this.modules.scoped(t,'import_batches',batchId);this.f.permit(t,'reconciliation:view');return {items:(await t.db.query('SELECT p.id,p.row_id,p.status,p.version,p.entry_id,r.payload FROM app.analysis_proposals p JOIN app.import_rows r ON r.id=p.row_id WHERE r.batch_id=$1 AND p.actor_id=$2 ORDER BY r.line LIMIT 500',[batchId,ctx.actor])).rows.filter(r=>this.f.allowedEntry(t,r.payload.direction,['unclassified']))};});}
 async detail(ctx:Context,batchId:string,id:string){return this.f.transaction(ctx,t=>this.proposal(t,batchId,id));}
 async review(ctx:Context,batchId:string,id:string,draft:ProposalDraft,reason:string){return this.f.command(ctx,'reconciliation:update',{operation:'review',batchId,id,draft,reason},async t=>{const p=await this.proposal(t,batchId,id,true);this.f.version(t,p);if(p.status==='approved')fail('Proposta já aprovada.',409);const result=(await t.db.query("UPDATE app.analysis_proposals SET draft=$2,status='draft',version=version+1,updated_at=now() WHERE id=$1 RETURNING *",[id,draft])).rows[0];await this.f.audit(t,'analysis',id,'review',p.draft,{draft,reason});return result;},t=>this.proposal(t,batchId,id).then(()=>{}));}
 async reject(ctx:Context,batchId:string,id:string,reason:string){return this.f.command(ctx,'reconciliation:update',{operation:'reject',batchId,id,reason},async t=>{const p=await this.proposal(t,batchId,id,true);this.f.version(t,p);if(p.status==='approved')fail('Proposta já aprovada.',409);await t.db.query("UPDATE app.analysis_proposals SET status='rejected',version=version+1 WHERE id=$1",[id]);await this.f.audit(t,'analysis',id,'reject',null,{reason});return {id,status:'rejected'};},t=>this.proposal(t,batchId,id).then(()=>{}));}
 async approve(ctx:Context,batchId:string,id:string,reason:string){return this.f.command(ctx,'reconciliation:update',{operation:'approve',batchId,id,reason},async t=>{
  const initial=await this.proposal(t,batchId,id);const {row,batch}=await this.row(t,batchId,initial.row_id,true);const p=await this.proposal(t,batchId,id,true);this.f.version(t,p);
  if(p.status==='approved'||row.status!=='pending')fail('Proposta ou movimento já aprovado.',409);if(p.status==='rejected')fail('Salve uma revisão antes de aprovar.',409);
  if(p.context_stale)fail('O acesso a uma agenda mudou. Reanalise o movimento antes de aprovar.',409);const d=proposalDraftSchema.parse(p.draft),bank=row.payload;this.f.permit(t,'context:update');await this.f.accounts(t,[batch.account_id]);
  for(const docId of [...d.document_ids].sort()){await t.db.query('SELECT id FROM app.documents WHERE id=$1 FOR SHARE',[docId]);const doc=await this.evidence.document(t,docId);if(doc.account_id!==batch.account_id||doc.status==='rejected')fail('Documento indisponível nesta conta.');const snapshot=p.sources.documents.find((s:{id:string})=>s.id===docId);if(snapshot&&snapshot.version!==doc.version)fail('Uma nota mudou desde a análise. Reanalise o movimento.',409);}
  for(const eventId of d.event_ids){const current=(await t.db.query('SELECT seen_at FROM app.external_events WHERE id=$1 FOR SHARE',[eventId])).rows[0],snapshot=p.sources.events.find((ev:{id:string})=>ev.id===eventId);if(!current||!snapshot||new Date(current.seen_at).getTime()!==new Date(snapshot.seen_at).getTime())fail('O evento mudou ou não foi analisado. Reanalise antes de aprovar.',409);}
  for(const activityId of d.activity_ids){const activity=(await t.db.query("SELECT * FROM app.planned_activities WHERE id=$1 AND actor_id=$2 AND status='active'",[activityId,ctx.actor])).rows[0];if(!activity)fail('Atividade indisponível.');const snapshot=p.sources.activities.find((item:{id:string})=>item.id===activityId);if(!snapshot||snapshot.version!==activity.version)fail('A atividade mudou. Reanalise o movimento.',409);}
  let e:Awaited<ReturnType<Evidence['entry']>>;
  if(d.mode==='match'){
   e=await this.evidence.entry(t,d.entry_id!,true);const snapshot=p.sources.entries.find((x:{id:string})=>x.id===e.id);if(snapshot&&snapshot.version!==e.version)fail('A transação mudou. Reanalise o movimento.',409);
   if(e.account_id!==batch.account_id||e.direction!==bank.direction||e.amount_minor!==bank.amount_minor||e.status==='cancelled')fail('Transação incompatível com o extrato.');
  }else{
   if((await this.candidates(t,batch.account_id,bank)).length&&!d.acknowledge_duplicate)fail('Confira as transações existentes e confirme que este é outro movimento.');
   if(specialMovement(bank.title)&&!d.acknowledge_special)fail('Confirme que este movimento é receita ou despesa, e não transferência ou aplicação.');
   let party=d.party_id;if(!party&&d.new_party){this.f.permit(t,'parties:create');const similar=(await t.db.query("SELECT id FROM app.parties WHERE status='active' AND (lower(name)=lower($1) OR ($2<>'' AND document=$2))",[d.new_party.name,d.new_party.document])).rows;if(similar.length)fail('Já existe um contato com esse nome/documento. Selecione-o na revisão.');const created=(await t.db.query('INSERT INTO app.parties(name,email,document) VALUES($1,$2,$3) RETURNING *',[d.new_party.name,d.new_party.email,d.new_party.document])).rows[0];party=created.id;await this.f.audit(t,'parties',created.id,'create',null,created);}
   e=await this.f.writeEntry(t,entrySchema.parse({account_id:batch.account_id,title:d.title,direction:bank.direction,amount_minor:bank.amount_minor,due_on:bank.date,competence_on:d.competence_on,party_id:party,notes:`Extrato: ${bank.title}`,allocations:[{amount_minor:bank.amount_minor,category_id:d.category_id}]}));
  }
  if(e.status==='open')e=await this.f.mutateEntryTx({...t,ctx:{...t.ctx,version:e.version}},e.id,'settle',{settled_on:bank.date,reason:reason.slice(0,500)});
  await this.modules.reconcileTx({...t,ctx:{...t.ctx,version:row.version}},batchId,row.id,e.id);
  const contacts=[...d.party_ids];for(const person of d.new_contacts){this.f.permit(t,'parties:create');const existing=(await t.db.query("SELECT p.id FROM app.parties p LEFT JOIN app.party_context pc ON pc.party_id=p.id WHERE p.status='active' AND (lower(p.name)=lower($1) OR ($2<>'' AND (lower(p.email)=lower($2) OR pc.emails ? $2)))",[person.name,person.email])).rows;if(existing.length)fail('Um participante já existe nos contatos. Selecione o cadastro em vez de criar outro.');const personRow=(await t.db.query('INSERT INTO app.parties(name,email) VALUES($1,$2) RETURNING *',[person.name,person.email])).rows[0];contacts.push(personRow.id);await this.f.audit(t,'parties',personRow.id,'create',null,personRow);}
  const previous=(await t.db.query('SELECT * FROM app.entry_context WHERE entry_id=$1',[e.id])).rows[0];const refs=async(table:string,col:string)=>(await t.db.query(`SELECT ${col} AS id FROM app.${table} WHERE entry_id=$1`,[e.id])).rows.map(x=>x.id);
  const eventRefs=(await t.db.query('SELECT ev.id FROM app.entry_events ee JOIN app.external_events ev ON ev.id=ee.event_id JOIN app.provider_connections c ON c.id=ev.connection_id WHERE ee.entry_id=$1 AND c.user_id=$2',[e.id,ctx.actor])).rows.map(x=>x.id);
  await this.evidence.saveContextTx({...t,ctx:{...t.ctx,version:previous?.version??1}},e.id,{dimension_ids:unique([...await refs('entry_dimensions','dimension_id'),...d.dimension_ids]),party_ids:unique([...await refs('entry_contacts','party_id'),...contacts]),document_ids:unique([...await refs('entry_documents','document_id'),...d.document_ids]),movement_ids:unique([...await refs('entry_movements','movement_id'),row.id]),event_ids:unique([...eventRefs,...d.event_ids]),justification:[previous?.justification,d.justification].filter(Boolean).join('\n').slice(0,5000),documentation_complete:false,status:'confirmed',reason});
  for(const aid of d.activity_ids)await t.db.query('INSERT INTO app.entry_planned_activities(entry_id,activity_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[e.id,aid]);
  if(d.remember_term){if(normalize(d.remember_term).length<4)fail('A regra precisa de pelo menos quatro caracteres.');await t.db.query('INSERT INTO app.classification_rules(actor_id,account_id,direction,term,defaults) VALUES($1,$2,$3,$4,$5) ON CONFLICT(actor_id,account_id,direction,term) DO UPDATE SET defaults=$5,active=true',[ctx.actor,batch.account_id,bank.direction,normalize(d.remember_term),{category_id:d.category_id,party_id:e.party_id,dimension_ids:d.dimension_ids}]);}
  await t.db.query("UPDATE app.analysis_proposals SET status='approved',entry_id=$2,version=version+1,updated_at=now() WHERE id=$1",[id,e.id]);await this.f.audit(t,'analysis',id,'approve',null,{entry_id:e.id,mode:d.mode,reason});return {id,entry_id:e.id,status:'approved'};
 },async t=>{const p=await this.proposal(t,batchId,id);this.f.permit(t,'entries:view');this.f.permit(t,'context:update');const d=proposalDraftSchema.parse(p.draft);if(d.mode==='create')this.f.permit(t,'entries:create');if(d.mode==='create'||p.sources.entries.some((e:{id:string;status:string})=>e.id===d.entry_id&&e.status==='open'))this.f.permit(t,'entries:settle');if(d.mode==='create'&&d.new_party||d.new_contacts.length)this.f.permit(t,'parties:create');if(p.entry_id)await this.evidence.entry(t,p.entry_id);});}
 async restart(ctx:Context,batchId:string,id:string){return this.f.command(ctx,'reconciliation:update',{operation:'restart',batchId,id},async t=>{const p=await this.proposal(t,batchId,id,true);this.f.version(t,p);const {row}=await this.row(t,batchId,p.row_id);if(p.status==='approved'||row.status!=='pending')fail('Não é possível reanalisar um movimento concluído.');await t.db.query('DELETE FROM app.analysis_proposals WHERE id=$1',[id]);await this.f.audit(t,'analysis',id,'restart',null,{row_id:p.row_id});return {id,row_id:p.row_id};},t=>this.proposal(t,batchId,id).then(()=>{}));}
 async activities(ctx:Context){return this.f.transaction(ctx,async t=>{this.f.permit(t,'context:view');return {items:(await t.db.query('SELECT * FROM app.planned_activities WHERE actor_id=$1 ORDER BY event_on DESC,id DESC LIMIT 200',[ctx.actor])).rows};});}
 async saveActivity(ctx:Context,data:z.infer<typeof plannedActivitySchema>,id?:string){return this.f.command(ctx,'context:update',{activity:id,data},async t=>{for(const dim of data.dimension_ids)if(!(await t.db.query("SELECT 1 FROM app.context_dimensions WHERE id=$1 AND status='active'",[dim])).rowCount)fail('Classificação inválida.');let before=null;if(id){before=(await t.db.query('SELECT * FROM app.planned_activities WHERE id=$1 AND actor_id=$2 FOR UPDATE',[id,ctx.actor])).rows[0];if(!before)fail('Atividade não encontrada.',404);this.f.version(t,before);}const values=[ctx.actor,data.title,data.event_on,data.description,JSON.stringify(data.participants),JSON.stringify(data.dimension_ids),data.status];const result=(await t.db.query(id?'UPDATE app.planned_activities SET title=$2,event_on=$3,description=$4,participants=$5,dimension_ids=$6,status=$7,version=version+1 WHERE id=$8 AND actor_id=$1 RETURNING *':'INSERT INTO app.planned_activities(actor_id,title,event_on,description,participants,dimension_ids,status) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',id?[...values,id]:values)).rows[0];await this.f.audit(t,'planned_activity',result.id,'save',before,data);return result;});}
 async rules(ctx:Context){return this.f.transaction(ctx,async t=>{this.f.permit(t,'context:view');return {items:(await t.db.query('SELECT r.* FROM app.classification_rules r JOIN app.accounts a ON a.id=r.account_id WHERE r.actor_id=$1 AND ($2 OR(a.id=ANY($3::bigint[]) AND a.legal_entity_id=ANY($4::bigint[]))) ORDER BY r.id DESC LIMIT 200',[ctx.actor,t.policy.is_owner,t.policy.account_ids,t.policy.legal_entity_ids])).rows};});}
 async disableRule(ctx:Context,id:string){return this.f.command(ctx,'context:update',{rule:id},async t=>{const result=(await t.db.query('UPDATE app.classification_rules SET active=false WHERE id=$1 AND actor_id=$2 RETURNING id',[id,ctx.actor])).rows[0];if(!result)fail('Regra não encontrada.',404);await this.f.audit(t,'classification_rule',id,'disable',null,{});return result;});}
}
