import {z} from 'zod';
import {id,day} from '../../contracts/src/finance.js';
import {Finance,type Context} from './finance.js';
import {Evidence} from './evidence.js';
import {AppError} from '../../contracts/src/index.js';
export const contactContextSchema=z.object({emails:z.array(z.email()).max(20),affiliations:z.array(z.object({institution_id:id,role:z.string().max(240),from:day.nullable(),to:day.nullable()}).strict().refine(d=>!d.from||!d.to||d.to>=d.from)).max(30),notes:z.string().max(3000),source:z.string().max(500),reason:z.string().trim().min(3).max(2000)}).strict();
export class Contacts {
 constructor(public f:Finance){}
 async get(ctx:Context,id:string){return this.f.transaction(ctx,async t=>{this.f.permit(t,'parties:view');const party=(await t.db.query('SELECT * FROM app.parties WHERE id=$1',[id])).rows[0];if(!party)throw new AppError(404,'NOT_FOUND','Contato não encontrado.');return {...party,context:(await t.db.query('SELECT * FROM app.party_context WHERE party_id=$1',[id])).rows[0]??{version:1,emails:[],affiliations:[],notes:''}};});}
 async save(ctx:Context,id:string,d:z.infer<typeof contactContextSchema>){return this.f.command(ctx,'parties:update',{id,...d},async t=>{this.f.permit(t,'context:view');const p=(await t.db.query('SELECT id FROM app.parties WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!p)throw new AppError(404,'NOT_FOUND','Contato não encontrado.');const previous=(await t.db.query('SELECT * FROM app.party_context WHERE party_id=$1',[id])).rows[0]??{version:1};this.f.version(t,previous);for(const a of d.affiliations)if(!(await t.db.query("SELECT 1 FROM app.context_dimensions WHERE id=$1 AND kind='institution'",[a.institution_id])).rowCount)throw new AppError(422,'INSTITUTION','Instituição não encontrada.');const r=(await t.db.query('INSERT INTO app.party_context(party_id,emails,affiliations,notes,version) VALUES($1,$2,$3,$4,2) ON CONFLICT(party_id) DO UPDATE SET emails=$2,affiliations=$3,notes=$4,version=app.party_context.version+1 RETURNING *',[id,JSON.stringify([...new Set(d.emails.map(e=>e.toLowerCase()))]),JSON.stringify(d.affiliations),d.notes])).rows[0];await this.f.audit(t,'party_context',id,'review',previous,d);return {id,...r};});}
 async suggestions(ctx:Context,entryId:string){return this.f.transaction(ctx,async t=>{this.f.permit(t,'parties:view');this.f.permit(t,'context:view');const evidence=new Evidence(this.f);await evidence.entry(t,entryId);const docs=(await t.db.query('SELECT d.id,d.filename,d.fields FROM app.documents d JOIN app.entry_documents ed ON ed.document_id=d.id WHERE ed.entry_id=$1',[entryId])).rows;const candidates:{name:string;email:string;source:string;source_id:string}[]=[];
  for(const d of docs){await evidence.document(t,d.id);for(const email of d.fields.emails??[])candidates.push({name:'',email,source:`Documento: ${d.filename}`,source_id:`document:${d.id}`});}
  if(t.policy.is_owner||t.policy.permissions.includes('integrations:view')){const events=(await t.db.query("SELECT ev.* FROM app.external_events ev JOIN app.entry_events ee ON ee.event_id=ev.id JOIN app.provider_connections c ON c.id=ev.connection_id WHERE ee.entry_id=$1 AND c.user_id=$2 AND c.status='connected' AND c.settings->'calendars' ? ev.calendar_id",[entryId,ctx.actor])).rows;for(const ev of events)for(const a of [...ev.payload.attendees??[],ev.payload.organizer??{}])if(a.email)candidates.push({name:a.displayName??'',email:a.email,source:`Evento: ${ev.title}`,source_id:`event:${ev.id}`});}
  const items=[];for(const c of candidates.slice(0,50)){const matches=(await t.db.query("SELECT p.id,p.name,p.email FROM app.parties p LEFT JOIN app.party_context pc ON pc.party_id=p.id WHERE lower(p.email)=lower($1) OR pc.emails ? lower($1) OR ($2<>'' AND lower(p.name)=lower($2)) LIMIT 10",[c.email,c.name])).rows;items.push({...c,matches,note:'Nome ou e-mail coincidente é uma pista. Confira homônimos e endereços compartilhados. O domínio não comprova vínculo institucional.'});}return {items};
 });}
}
