import {createHash} from 'node:crypto';
import type {z} from 'zod';
import {Finance,type Context,type Tx} from './finance.js';
import {InternalModules} from './modules.js';
import {AppError} from '../../contracts/src/index.js';
import {extractedSchema,documentSchema,documentReviewSchema,dimensionSchema,accountabilitySchema,type EvidenceContext} from '../../contracts/src/evidence.js';
import type {ListQuery} from '../../contracts/src/finance.js';
const fail=(message:string,status=422):never=>{throw new AppError(status,'EVIDENCE_VALIDATION',message);};
const docColumns='d.id,d.account_id,d.filename,d.mime,d.content_hash,d.byte_size,d.fields,d.provenance,d.method,d.duration_ms,d.cost_minor,d.status,d.created_at,d.version';
export function extractFields(source:string){
 const lines=source.split(/\r?\n/).map(s=>s.trim()).filter(Boolean),first=(pattern:RegExp)=>pattern.exec(source)?.[1]?.trim()??'';
 const rawDate=first(/(?:emiss[aã]o|data)\s*:?\s*(\d{2}\/\d{2}\/\d{4})/i);const total=first(/(?:valor\s+total(?:\s+da\s+nota)?|total\s+a\s+pagar)\s*:?\s*(?:R\$\s*)?([\d.]+,\d{2})/i);
 const raw={type:/nota fiscal|danfe|nfs-e/i.test(source)?'Nota fiscal':/recibo/i.test(source)?'Recibo':'',number:first(/(?:n[uú]mero|n[º°.]|nota\s+n[º°.]?)\s*:?\s*(\d[\d./-]*)/i),supplier:first(/(?:raz[aã]o\s+social|emitente|fornecedor)\s*:?\s*([^\r\n]+)/i),tax_id:first(/(?:CNPJ|CPF)\s*:?\s*([\d./-]+)/i),issued_on:rawDate?rawDate.split('/').reverse().join('-'):null,total_minor:total?total.replace(/[.,]/g,''):null,description:lines.filter(l=>/descri[cç][aã]o|produto|servi[cç]o|item/i.test(l)).join('\n').slice(0,5000),payment:first(/(?:forma\s+de\s+pagamento|pagamento)\s*:?\s*([^\r\n]+)/i),emails:[...new Set(source.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)??[])].slice(0,30),names:lines.flatMap(l=>{const m=/^(?:nome(?: do contato)?|respons[aá]vel|contato)\s*:\s*([^@]+)$/i.exec(l);return m?[m[1]!.trim()]:[]}).slice(0,30)};
 const result:Record<string,unknown>={...extractedSchema.parse({})};for(const k of Object.keys(raw) as (keyof typeof raw)[]){const field=extractedSchema.shape[k].safeParse(raw[k]);if(field.success)result[k]=field.data;}return extractedSchema.parse(result);
}
export class Evidence {
 constructor(public f:Finance,public modules=new InternalModules(f)){}
 async entry(t:Tx,id:string,lock=false){this.f.permit(t,'entries:view');const e=(await t.db.query(`SELECT * FROM app.entries WHERE id=$1${lock?' FOR UPDATE':''}`,[id])).rows[0];if(!e)fail('Transação não encontrada.',404);await this.f.checkEntry(t,e);return e;}
 async document(t:Tx,id:string,original=false){this.f.permit(t,'documents:view');const d=(await t.db.query(`SELECT ${docColumns},d.extracted_text,d.extracted_fields${original?',d.original':''} FROM app.documents d JOIN app.accounts a ON a.id=d.account_id WHERE d.id=$1 AND ($2 OR(a.id=ANY($3::bigint[]) AND a.legal_entity_id=ANY($4::bigint[])))`,[id,t.policy.is_owner,t.policy.account_ids,t.policy.legal_entity_ids])).rows[0];if(!d)fail('Documento não encontrado.',404);
  const linked=(await t.db.query('SELECT e.* FROM app.entries e JOIN app.entry_documents ed ON ed.entry_id=e.id WHERE ed.document_id=$1',[id])).rows;for(const e of linked)await this.f.checkEntry(t,e);return d;
 }
 async documents(ctx:Context,q:Pick<ListQuery,'account_id'|'legal_entity_id'>&{after?:string;hash?:string;q?:string;unlinked?:string}){return this.f.transaction(ctx,async t=>{
  this.f.permit(t,'documents:view');const values:unknown[]=[t.policy.is_owner,t.policy.account_ids,t.policy.legal_entity_ids,t.policy.directions,t.policy.groups];let where=`($1 OR(a.id=ANY($2::bigint[]) AND a.legal_entity_id=ANY($3::bigint[]) AND NOT EXISTS(SELECT 1 FROM app.entry_documents ed JOIN app.entries e ON e.id=ed.entry_id WHERE ed.document_id=d.id AND (NOT(e.direction=ANY($4::text[])) OR EXISTS(SELECT 1 FROM app.entry_allocations al WHERE al.entry_id=e.id AND NOT(al.reporting_group=ANY($5::text[])))))))`;
  for(const [v,column] of [[q.account_id,'d.account_id'],[q.legal_entity_id,'a.legal_entity_id'],[q.hash,'d.content_hash']] as const)if(v){values.push(v);where+=` AND ${column}=$${values.length}`;}if(q.q){values.push('%'+q.q.replace(/[\\%_]/g,'\\$&')+'%');where+=` AND (d.filename || ' ' || coalesce(d.fields->>'supplier','')) ILIKE $${values.length}`;}if(q.unlinked==='true')where+=' AND NOT EXISTS(SELECT 1 FROM app.entry_documents ed WHERE ed.document_id=d.id)';if(q.after){values.push(q.after);where+=` AND d.id<$${values.length}`;}
  const items=(await t.db.query(`SELECT ${docColumns},EXISTS(SELECT 1 FROM app.entry_documents ed WHERE ed.document_id=d.id) AS linked FROM app.documents d JOIN app.accounts a ON a.id=d.account_id WHERE ${where} ORDER BY d.id DESC LIMIT 51`,values)).rows;return {items:items.slice(0,50),next:items.length>50?items[49].id:null};
 });}
 async upload(ctx:Context,d:z.infer<typeof documentSchema>){
  const original=Buffer.from(d.base64,'base64'),hash=createHash('sha256').update(original).digest('hex');
  if(!original.length||original.length>1500000)fail('Documento deve ter até 1,5 MB.');
  const mime=original.subarray(0,5).toString()==='%PDF-'?'application/pdf':original.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))?'image/png':original[0]===255&&original[1]===216?'image/jpeg':original.subarray(0,4).toString()==='RIFF'&&original.subarray(8,12).toString()==='WEBP'?'image/webp':'';if(mime!==d.mime)fail('O conteúdo não corresponde ao tipo do arquivo.');
  return this.f.command(ctx,'documents:create',{account_id:d.account_id,hash,filename:d.filename},async t=>{
   await this.f.accounts(t,[d.account_id]);await t.db.query('SELECT pg_advisory_xact_lock(7172703)');const previous=(await t.db.query('SELECT id FROM app.documents WHERE account_id=$1 AND content_hash=$2',[d.account_id,hash])).rows[0];if(previous)return this.document(t,previous.id);
   const used=(await t.db.query('SELECT coalesce(sum(byte_size),0)::bigint AS bytes FROM app.documents')).rows[0].bytes;const quota=Math.min(500000000,Math.max(1500000,Number(process.env.DOCUMENT_QUOTA_BYTES)||50000000));if(BigInt(used)+BigInt(original.length)>BigInt(quota))fail('Armazenamento de documentos cheio. Solicite revisão do limite ao administrador.',409);
   const fields=extractFields(d.text),provenance=Object.fromEntries(Object.entries(fields).filter(([,v])=>v!==null&&v!==''&&(!Array.isArray(v)||v.length)).map(([k])=>[k,{status:'extracted',source:d.method}]));
   const r=(await t.db.query(`INSERT INTO app.documents(account_id,filename,mime,content_hash,original,byte_size,extracted_text,extracted_fields,fields,provenance,method,duration_ms,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$8,$9,$10,$11,$12) RETURNING id`,[d.account_id,d.filename,d.mime,hash,original,original.length,d.text,fields,provenance,d.method,d.duration_ms,ctx.actor])).rows[0];await this.f.audit(t,'document',r.id,'upload',null,{filename:d.filename,hash,method:d.method,bytes:original.length});return this.document(t,r.id);
  },async t=>{this.f.permit(t,'documents:view');await this.f.accounts(t,[d.account_id]);const prior=(await t.db.query('SELECT id FROM app.documents WHERE account_id=$1 AND content_hash=$2',[d.account_id,hash])).rows[0];if(prior)await this.document(t,prior.id);});
 }
 async reviewDocument(ctx:Context,id:string,d:z.infer<typeof documentReviewSchema>){return this.f.command(ctx,'documents:update',{id,...d},async t=>{await t.db.query('SELECT id FROM app.documents WHERE id=$1 FOR UPDATE',[id]);const before=await this.document(t,id);this.f.version(t,before);const provenance=Object.fromEntries(Object.keys(d.fields).map(k=>[k,{status:d.status==='confirmed'?'confirmed':'reviewed',source:'human',actor:ctx.actor,at:new Date().toISOString(),original:{status:'extracted',source:before.method}}]));await t.db.query('UPDATE app.documents SET fields=$2,status=$3,provenance=$4,version=version+1 WHERE id=$1',[id,d.fields,d.status,provenance]);await t.db.query("UPDATE app.entry_context ec SET documentation_complete=false,status='pending',version=version+1 WHERE EXISTS(SELECT 1 FROM app.entry_documents ed WHERE ed.entry_id=ec.entry_id AND ed.document_id=$1)",[id]);await this.f.audit(t,'document',id,'review',{fields:before.fields,status:before.status},{...d});return this.document(t,id);},async t=>{await this.document(t,id);});}
 async dimensions(ctx:Context){return this.f.transaction(ctx,async t=>{this.f.permit(t,'context:view');return {items:(await t.db.query('SELECT * FROM app.context_dimensions ORDER BY kind,name,id LIMIT 1000')).rows};});}
 async saveDimension(ctx:Context,d:z.infer<typeof dimensionSchema>,id?:string){return this.f.command(ctx,`context:${id?'update':'create'}`,{...d,id},async t=>{let before=null;if(id){before=(await t.db.query('SELECT * FROM app.context_dimensions WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!before)fail('Cadastro não encontrado.',404);this.f.version(t,before);}const r=(await t.db.query(id?'UPDATE app.context_dimensions SET kind=$2,name=$3,description=$4,status=$5,version=version+1 WHERE id=$1 RETURNING *':'INSERT INTO app.context_dimensions(kind,name,description,status) VALUES($1,$2,$3,$4) RETURNING *',id?[id,d.kind,d.name,d.description,d.status]:[d.kind,d.name,d.description,d.status])).rows[0];await this.f.audit(t,'context_dimension',r.id,'save',before,r);return r;});}
 async context(ctx:Context,id:string){return this.f.transaction(ctx,async t=>{this.f.permit(t,'context:view');await this.entry(t,id);const row=(await t.db.query('SELECT * FROM app.entry_context WHERE entry_id=$1',[id])).rows[0]??{entry_id:id,version:1,justification:'',status:'pending'};
  const result:Record<string,unknown>={...row,id};for(const [key,table,col] of [['dimensions','context_dimensions','dimension'],['contacts','parties','party'],['documents','documents','document'],['movements','import_rows','movement'],['events','external_events','event']] as const){const relation=key==='contacts'?'entry_contacts':`entry_${key}`;if(key==='documents'){if(!t.policy.is_owner&&!t.policy.permissions.includes('documents:view')){result[key]=[];continue;}}
   if(key==='events'){result[key]=(await t.db.query('SELECT x.* FROM app.external_events x JOIN app.entry_events link ON link.event_id=x.id JOIN app.provider_connections c ON c.id=x.connection_id WHERE link.entry_id=$1 AND c.user_id=$2 AND c.status=$3',[id,ctx.actor,'connected'])).rows;continue;}
   if(key==='contacts')this.f.permit(t,'parties:view');if(key==='movements')this.f.permit(t,'imports:view');
   result[key]=(await t.db.query(`SELECT ${key==='documents'?'x.id,x.filename,x.fields,x.status,x.version': 'x.*'} FROM app.${table} x JOIN app.${relation} link ON link.${col}_id=x.id WHERE link.entry_id=$1 ORDER BY x.id`,[id])).rows;
  }result.history=(await t.db.query("SELECT a.action,a.after_data,a.occurred_at,u.display_name FROM app.audit_events a JOIN app.users u ON u.id=a.actor_id WHERE a.resource_type='entry_context' AND a.resource_id=$1 ORDER BY a.id DESC LIMIT 30",[id])).rows;return result;
 });}
 async saveContext(ctx:Context,id:string,d:EvidenceContext){return this.f.command(ctx,'context:update',{id,...d},async t=>{
  const e=await this.entry(t,id,true);if(d.documentation_complete&&(!d.document_ids.length||d.status!=='confirmed'))fail('Documentação completa exige comprovante e contexto confirmados.');const before=(await t.db.query('SELECT * FROM app.entry_context WHERE entry_id=$1 FOR UPDATE',[id])).rows[0]??{version:1};this.f.version(t,before);
  for(const documentId of new Set(d.document_ids)){const doc=await this.document(t,documentId);if(doc.account_id!==e.account_id)fail('Documento deve pertencer à conta da transação.');if(d.documentation_complete&&doc.status!=='confirmed')fail('Confirme os documentos antes de declarar a documentação completa.');}
  for(const movementId of new Set(d.movement_ids)){this.f.permit(t,'imports:view');const movement=(await t.db.query('SELECT r.*,b.account_id FROM app.import_rows r JOIN app.import_batches b ON b.id=r.batch_id WHERE r.id=$1',[movementId])).rows[0];if(!movement||movement.account_id!==e.account_id||!this.f.allowedEntry(t,movement.payload.direction,['unclassified']))fail('Movimento indisponível nesta conta.');}
  for(const eventId of new Set(d.event_ids)){this.f.permit(t,'integrations:view');if(!(await t.db.query("SELECT 1 FROM app.external_events ev JOIN app.provider_connections c ON c.id=ev.connection_id WHERE ev.id=$1 AND c.user_id=$2 AND c.status='connected' AND c.settings->'calendars' ? ev.calendar_id",[eventId,ctx.actor])).rowCount)fail('Evento não pertence a uma agenda autorizada.');}
  if(d.party_ids.length)this.f.permit(t,'parties:view');
  for(const dimensionId of new Set(d.dimension_ids))if(!(await t.db.query("SELECT 1 FROM app.context_dimensions WHERE id=$1 AND status='active'",[dimensionId])).rowCount)fail('Classificação indisponível.');
  await t.db.query("INSERT INTO app.entry_context(entry_id,justification,status,reviewed_by,reviewed_at,version,documentation_complete,entry_version) VALUES($1,$2,$3,$4,now(),2,$5,$6) ON CONFLICT(entry_id) DO UPDATE SET justification=$2,status=$3,reviewed_by=$4,reviewed_at=now(),version=app.entry_context.version+1,documentation_complete=$5,entry_version=$6",[id,d.justification,d.status,ctx.actor,d.documentation_complete,e.version]);
  // A colleague's private calendar links are preserved; only this person's links are replaced.
  await t.db.query('DELETE FROM app.entry_events link USING app.external_events ev,app.provider_connections c WHERE link.entry_id=$1 AND link.event_id=ev.id AND ev.connection_id=c.id AND c.user_id=$2',[id,ctx.actor]);
  for(const [ids,table,col] of [[d.dimension_ids,'entry_dimensions','dimension'],[d.party_ids,'entry_contacts','party'],[d.document_ids,'entry_documents','document'],[d.movement_ids,'entry_movements','movement'],[d.event_ids,'entry_events','event']] as const){if(table!=='entry_events')await t.db.query(`DELETE FROM app.${table} WHERE entry_id=$1`,[id]);for(const ref of new Set(ids))await t.db.query(`INSERT INTO app.${table}(entry_id,${col}_id) VALUES($1,$2) ON CONFLICT DO NOTHING`,[id,ref]);}
  await this.f.audit(t,'entry_context',id,'review',before,d);return {id,version:Number(before.version)+1,status:d.status};
 },async t=>{await this.entry(t,id);this.f.permit(t,'context:view');this.f.permit(t,'documents:view');});}
 async suggestions(ctx:Context,id:string){return this.f.transaction(ctx,async t=>{
  this.f.permit(t,'context:view');const e=await this.entry(t,id);this.f.permit(t,'documents:view');this.f.permit(t,'imports:view');
  const documents=(await t.db.query(`SELECT ${docColumns} FROM app.documents d WHERE d.account_id=$1 AND d.status<>'rejected' AND (d.fields->>'total_minor'=$2 OR (d.fields->>'issued_on') BETWEEN ($3::date-7)::text AND ($3::date+7)::text) ORDER BY d.id DESC LIMIT 30`,[e.account_id,e.amount_minor,e.due_on])).rows;
  const visible=[];for(const d of documents){try{await this.document(t,d.id);visible.push({...d,reasons:[d.fields.total_minor===e.amount_minor?'Valor igual':'Valor diferente: confira pagamento parcial ou várias notas',d.fields.issued_on===e.due_on?'Data igual':'Data de emissão diferente do vencimento'],certainty:d.fields.total_minor===e.amount_minor?'Compatível; requer revisão':'Somente contexto'});}catch(err){if(!(err instanceof AppError)||err.statusCode!==404)throw err;}}
  const movements=(await t.db.query(`SELECT r.*,b.filename FROM app.import_rows r JOIN app.import_batches b ON b.id=r.batch_id WHERE b.account_id=$1 AND b.kind IN('ofx','xlsx') AND r.payload->>'direction'=$2 AND (r.payload->>'amount_minor'=$3 OR r.payload->>'date' BETWEEN ($4::date-7)::text AND ($4::date+7)::text) AND r.status NOT IN('invalid','duplicate') ORDER BY r.id DESC LIMIT 30`,[e.account_id,e.direction,e.amount_minor,e.due_on])).rows.filter(r=>this.f.allowedEntry(t,r.payload.direction,['unclassified']));
  const events=(await t.db.query(`SELECT ev.* FROM app.external_events ev JOIN app.provider_connections c ON c.id=ev.connection_id WHERE c.user_id=$1 AND c.status='connected' AND c.settings->'calendars' ? ev.calendar_id AND ev.start_on BETWEEN $2::date-3 AND $2::date+3 AND ev.payload->>'status' IN('confirmed','tentative') ORDER BY ev.start_on LIMIT 30`,[ctx.actor,e.due_on])).rows;
  const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  const sources=[{text:String(e.title),source:'Descrição da transação'},...visible.map(d=>({text:JSON.stringify(d.fields),source:`Documento ${d.filename}`})),...events.map(ev=>({text:`${ev.title} ${ev.payload.description??''} ${ev.payload.location??''}`,source:`Evento ${ev.title}`}))];
  const dimensions=(await t.db.query("SELECT * FROM app.context_dimensions WHERE status='active' LIMIT 1000")).rows.flatMap(d=>{const term=normalize(d.name);if(term.length<4)return [];const matches=sources.filter(s=>normalize(s.text).includes(term));return matches.length?[{...d,reasons:matches.map(m=>`Nome mencionado em: ${m.source}`),certainty:'Menção textual; confirme a relação'}]:[];});
  return {dimensions,documents:visible,movements:movements.map(r=>({...r,reasons:[r.payload.amount_minor===e.amount_minor?'Valor igual':'Valor divergente',r.payload.date===e.due_on?'Mesma data':'Data diferente'],certainty:'Confira a realização; vincular não concilia'})),events:events.map(ev=>({...ev,reasons:['Evento próximo ao vencimento; convite não comprova presença nem finalidade'],certainty:'Somente contexto'})),limitations:'Liquidação e conciliação financeira são integrais. Vários documentos e movimentos podem ser evidências, mas isso não liquida nem concilia pagamentos parciais.'};
 });}
 async report(ctx:Context,q:z.infer<typeof accountabilitySchema>){return this.f.transaction(ctx,async t=>{
  this.f.permit(t,'reports:view');this.f.permit(t,'context:view');this.f.permit(t,'documents:view');this.f.permit(t,'imports:view');const {sql,values}=this.f.entryFilter(t,q);let filter=sql+" AND e.status<>'cancelled'";
  if(q.dimension_id){values.push(q.dimension_id);filter+=` AND EXISTS(SELECT 1 FROM app.entry_dimensions ed WHERE ed.entry_id=e.id AND ed.dimension_id=$${values.length})`;}
  const docs="EXISTS(SELECT 1 FROM app.entry_documents ed JOIN app.documents d ON d.id=ed.document_id WHERE ed.entry_id=e.id AND d.status<>'rejected')",confirmed="EXISTS(SELECT 1 FROM app.entry_documents ed JOIN app.documents d ON d.id=ed.document_id WHERE ed.entry_id=e.id AND d.status='confirmed')",matched="EXISTS(SELECT 1 FROM app.import_rows r WHERE r.entry_id=e.id AND r.status='matched' AND NOT EXISTS(SELECT 1 FROM app.settlements s WHERE s.reversal_of=r.settlement_id))";
  const complete="(coalesce(ec.documentation_complete,false) AND ec.entry_version=e.version AND "+confirmed+" AND NOT EXISTS(SELECT 1 FROM app.entry_documents ed JOIN app.documents d ON d.id=ed.document_id WHERE ed.entry_id=e.id AND d.status<>'confirmed'))";
  if(q.documentation!=='all')filter+=` AND ${q.documentation==='missing'?`NOT ${docs}`:q.documentation==='complete'?complete:q.documentation==='confirmed'?confirmed:docs}`;if(q.review!=='all'){values.push(q.review);filter+=` AND coalesce(ec.status,'pending')=$${values.length}`;}if(q.reconciliation!=='all')filter+=` AND ${q.reconciliation==='unmatched'?'NOT ':''}${matched}`;
  if(q.program_group){values.push(q.program_group);filter+=` AND coalesce((SELECT string_agg(cd.name,' + ' ORDER BY cd.id) FROM app.entry_dimensions ed JOIN app.context_dimensions cd ON cd.id=ed.dimension_id WHERE ed.entry_id=e.id AND cd.kind='program'),'Sem programa')=$${values.length}`;}
  const base=`FROM app.entries e JOIN app.accounts a ON a.id=e.account_id LEFT JOIN app.entry_context ec ON ec.entry_id=e.id WHERE ${filter}`;
  const total=(await t.db.query(`SELECT count(*)::int AS count,coalesce(sum(e.amount_minor) FILTER(WHERE e.direction='income'),0)::text AS income_minor,coalesce(sum(e.amount_minor) FILTER(WHERE e.direction='expense'),0)::text AS expense_minor,count(*) FILTER(WHERE ${confirmed})::int AS documented,count(*) FILTER(WHERE ${complete})::int AS complete,count(*) FILTER(WHERE ${matched})::int AS reconciled ${base}`,values)).rows[0];
  const groups=(await t.db.query(`SELECT coalesce((SELECT string_agg(cd.name,' + ' ORDER BY cd.id) FROM app.entry_dimensions ed JOIN app.context_dimensions cd ON cd.id=ed.dimension_id WHERE ed.entry_id=e.id AND cd.kind='program'),'Sem programa') AS name,sum(e.amount_minor)::text AS amount_minor ${base} AND e.direction='expense' GROUP BY 1 ORDER BY sum(e.amount_minor) DESC LIMIT 30`,values)).rows;
  const pageValues=[...values];let paging='';if(q.after){pageValues.push(q.after);paging=` AND e.id<$${pageValues.length}`;}
  if(q.include_contacts==='true')this.f.permit(t,'parties:view');
  const contactColumns=q.include_contacts==='true'?`,(SELECT coalesce(jsonb_agg(jsonb_build_object('name',p.name,'email',p.email)),'[]') FROM app.entry_contacts ec JOIN app.parties p ON p.id=ec.party_id WHERE ec.entry_id=e.id) AS contacts`:'';
  const items=(await t.db.query(`SELECT e.*${contactColumns},coalesce(ec.status,'pending') AS review_status,${docs} AS has_document,${confirmed} AS confirmed_document,${complete} AS documentation_complete,${matched} AS reconciled ${base}${paging} ORDER BY e.id DESC LIMIT 51`,pageValues)).rows;return {total,groups,items:items.slice(0,50),next:items.length>50?items[49].id:null};
 });}
}
