import pg from 'pg';
import { createHash } from 'node:crypto';
import { AppError } from '../../contracts/src/index.js';
import { policySchema, type Policy, type EntryInput, type ListQuery, type Catalog } from '../../contracts/src/finance.js';
type Row=Record<string,unknown>;
export type Context={actor:string;requestId:string;key?:string;version?:number;policyAdministration?:boolean};
type Tx={db:pg.PoolClient;ctx:Context;policy:Policy};
const fail=(status:number,code:string,message:string):never=>{throw new AppError(status,code,message);};
const canonical=(v:unknown):string=>JSON.stringify(v,(_k,val)=>val && typeof val==='object'&&!Array.isArray(val)?Object.fromEntries(Object.entries(val).sort(([a],[b])=>a.localeCompare(b))):val);
export const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export class Finance {
 constructor(public pool:pg.Pool){}
 async transaction<T>(ctx:Context,run:(tx:Tx)=>Promise<T>):Promise<T>{
  const db=await this.pool.connect();
  try {await db.query('BEGIN');if(ctx.policyAdministration)await db.query('SELECT pg_advisory_xact_lock(7172701)');
   // Shared lock serializes policy changes against in-flight commands without serializing readers.
   const u=await db.query("SELECT status FROM app.users WHERE id=$1 FOR SHARE",[ctx.actor]);
   if(u.rows[0]?.status!=='active')fail(403,'ACCESS_REVOKED','Seu acesso não está ativo.');
   const p=await db.query('SELECT * FROM app.access_policies WHERE user_id=$1 FOR SHARE',[ctx.actor]);
   if(!p.rows[0])fail(403,'NO_POLICY','Seu acesso ainda não foi configurado.');
   const policy=Object.fromEntries(Object.entries(p.rows[0]).filter(([k])=>k!=='user_id'&&k!=='version'));
   const result=await run({db,ctx,policy:policySchema.parse(policy)});await db.query('COMMIT');return result;
  }catch(e){await db.query('ROLLBACK');const code=(e as {code?:string}).code;
   if(code==='23505')fail(409,'DUPLICATE','Este registro já existe.');
   if(code==='23503'||code==='23514')fail(422,'INVALID_REFERENCE','Verifique os vínculos e valores informados.');
   if(code==='55P03'||code==='40P01'||code==='40001')fail(409,'BUSY','Outra operação está em andamento. Tente novamente com a mesma chave.');
   throw e;
  }finally{db.release();}
 }
 permit(t:Tx,permission:string){if(!t.policy.is_owner&&!t.policy.permissions.includes(permission))fail(403,'FORBIDDEN','Seu perfil não permite esta ação.');}
 allowed(t:Tx,account:Row){return t.policy.is_owner || t.policy.account_ids.includes(String(account.id))&&t.policy.legal_entity_ids.includes(String(account.legal_entity_id));}
 allowedEntry(t:Tx,direction:string,groups:string[]){return t.policy.is_owner||t.policy.directions.includes(direction as 'income'|'expense')&&groups.every(g=>t.policy.groups.includes(g as Policy['groups'][number]));}
 async accounts(t:Tx,ids:string[],active=true){const r=await t.db.query('SELECT a.*,l.status AS entity_status FROM app.accounts a JOIN app.legal_entities l ON l.id=a.legal_entity_id WHERE a.id=ANY($1::bigint[]) ORDER BY a.id FOR UPDATE OF a',[ids]);
  if(r.rows.length!==new Set(ids).size||r.rows.some(a=>!this.allowed(t,a)))fail(404,'NOT_FOUND','Conta não encontrada.');
  if(active&&r.rows.some(a=>a.status!=='active'||a.entity_status!=='active'))fail(409,'ARCHIVED','Conta ou empresa arquivada.');return r.rows;
 }
 version(t:Tx,row:Row){if(t.ctx.version===undefined)fail(428,'VERSION_REQUIRED','Atualize os dados antes de continuar.');if(row.version!==t.ctx.version)fail(412,'STALE_VERSION','Este registro mudou. Atualize a tela.');}
 async audit(t:Tx,type:string,rid:string,action:string,before:unknown,after:unknown){await t.db.query('INSERT INTO app.audit_events(actor_id,resource_type,resource_id,action,before_data,after_data,request_id) VALUES($1,$2,$3,$4,$5,$6,$7)',[t.ctx.actor,type,rid,action,before,after,t.ctx.requestId]);}
 async command(ctx:Context,kind:string,input:unknown,run:(t:Tx)=>Promise<Row>){return this.transaction({...ctx,policyAdministration:kind.startsWith('policy:')},async t=>{
  // Reauthorize even when replaying a previously successful response.
  const parts=kind.split(':');const root=parts[0]!;const data=input as Row;
  const permission=root==='organization'||root==='entity'?'organization:manage':root==='transfer'?'entries:transfer':root==='account'?`accounts:${parts[1]==='create'?'create':'update'}`:root==='entry'?`entries:${parts[1]==='create'?'create':parts[2]??'update'}`:root==='policy'||root==='invitation'?'users:manage':`${root}:${parts[1]==='create'?'create':'update'}`;
  this.permit(t,permission);
  if(root==='policy'&&!t.policy.is_owner)fail(403,'OWNER_REQUIRED','Somente proprietários podem alterar acessos.');
  if(root==='entry'&&parts[1]!=='create'){const e=(await t.db.query('SELECT * FROM app.entries WHERE id=$1',[parts[1]])).rows[0];if(!e)fail(404,'NOT_FOUND','Lançamento não encontrado.');await this.checkEntry(t,e);}
  if(root==='account'&&parts[1]==='update'){const a=(await t.db.query('SELECT * FROM app.accounts WHERE id=$1',[parts[2]])).rows[0];if(!a||!this.allowed(t,a))fail(404,'NOT_FOUND','Conta não encontrada.');}
  if(root==='transfer'&&parts[1]==='reverse'){const a=await t.db.query('SELECT a.* FROM app.transfers tr JOIN app.accounts a ON a.id IN(tr.source_account_id,tr.destination_account_id) WHERE tr.id=$1',[parts[2]]);if(a.rows.length!==2||a.rows.some(row=>!this.allowed(t,row)))fail(404,'NOT_FOUND','Transferência não encontrada.');}
  const ids=[data.account_id,data.source_account_id,data.destination_account_id].filter(Boolean);
  if(ids.length){const a=await t.db.query('SELECT * FROM app.accounts WHERE id=ANY($1::bigint[])',[ids]);if(a.rows.length!==new Set(ids).size||a.rows.some(row=>!this.allowed(t,row)))fail(404,'NOT_FOUND','Conta não encontrada.');}
  if(!ctx.key||!/^[\w:.-]{8,128}$/.test(ctx.key))fail(400,'IDEMPOTENCY_REQUIRED','Informe uma chave de operação válida.');
  const hash=createHash('sha256').update(canonical({kind,input,version:ctx.version})).digest('hex');
  await t.db.query('INSERT INTO app.idempotency_records(actor_id,key,payload_hash) VALUES($1,$2,$3) ON CONFLICT DO NOTHING',[ctx.actor,ctx.key,hash]);
  const r=(await t.db.query('SELECT * FROM app.idempotency_records WHERE actor_id=$1 AND key=$2 FOR UPDATE',[ctx.actor,ctx.key])).rows[0];
  if(r.payload_hash!==hash)fail(409,'IDEMPOTENCY_CONFLICT','Esta chave já foi usada com outros dados.');
  if(r.response){if(root==='entry'&&parts[1]==='create'){const e=(await t.db.query('SELECT * FROM app.entries WHERE id=$1',[r.response.id])).rows[0];if(!e)fail(404,'NOT_FOUND','Lançamento não encontrado.');await this.checkEntry(t,e);}return r.response as Row;}
  const response=await run(t);await t.db.query('UPDATE app.idempotency_records SET response=$3 WHERE actor_id=$1 AND key=$2',[ctx.actor,ctx.key,response]);return response;
 });}
 async post(t:Tx,a:string,date:string,amount:bigint,kind:string,description:string,item:string|null=null,transfer:string|null=null,reversal:string|null=null){
  if(!amount)return;
  await t.db.query('INSERT INTO app.cash_postings(account_id,effective_on,signed_minor,kind,description,settlement_item_id,transfer_id,reversal_of) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[a,date,amount.toString(),kind,description,item,transfer,reversal]);
  await t.db.query('INSERT INTO app.account_balances(account_id,balance_minor) VALUES($1,$2) ON CONFLICT(account_id) DO UPDATE SET balance_minor=app.account_balances.balance_minor+excluded.balance_minor',[a,amount.toString()]);
  await t.db.query('INSERT INTO app.cash_daily(account_id,effective_on,net_minor) VALUES($1,$2,$3) ON CONFLICT(account_id,effective_on) DO UPDATE SET net_minor=app.cash_daily.net_minor+excluded.net_minor',[a,date,amount.toString()]);
 }
 date(date:string,account:Row){if(date>today())fail(422,'FUTURE_DATE','A realização não pode ter data futura.');if(date<String(account.opening_on))fail(422,'BEFORE_OPENING','A data é anterior à abertura da conta.');}
 async profile(ctx:Context){return this.transaction(ctx,async t=>({...(await t.db.query('SELECT * FROM app.organization_profile WHERE id=1')).rows[0],policy:t.policy}));}
 async organization(ctx:Context,name:string){return this.command(ctx,'organization',{name},async t=>{this.permit(t,'organization:manage');const r=(await t.db.query('SELECT * FROM app.organization_profile WHERE id=1 FOR UPDATE')).rows[0];this.version(t,r);const n=(await t.db.query('UPDATE app.organization_profile SET name=$1,version=version+1 WHERE id=1 RETURNING *',[name])).rows[0];await this.audit(t,'organization','1','update',r,n);return n;});}
 async listEntities(ctx:Context){return this.transaction(ctx,async t=>(await t.db.query('SELECT * FROM app.legal_entities WHERE $1 OR id=ANY($2::bigint[]) ORDER BY id',[t.policy.is_owner,t.policy.legal_entity_ids])).rows);}
 async entity(ctx:Context,data:Row,rid?:string){return this.command(ctx,'entity:'+String(rid),data,async t=>{this.permit(t,'organization:manage');let before=null;if(rid){before=(await t.db.query('SELECT * FROM app.legal_entities WHERE id=$1 FOR UPDATE',[rid])).rows[0];if(!before)fail(404,'NOT_FOUND','Empresa não encontrada.');this.version(t,before);}
  const r=rid?await t.db.query('UPDATE app.legal_entities SET name=$2,cnpj=$3,status=$4,version=version+1 WHERE id=$1 RETURNING *',[rid,data.name,data.cnpj,data.status]):await t.db.query('INSERT INTO app.legal_entities(name,cnpj,status) VALUES($1,$2,$3) RETURNING *',[data.name,data.cnpj,data.status]);await this.audit(t,'legal_entity',r.rows[0].id,rid?'update':'create',before,r.rows[0]);return r.rows[0];});}
 async listAccounts(ctx:Context){return this.transaction(ctx,async t=>{this.permit(t,'accounts:view');const balances=t.policy.is_owner||t.policy.permissions.includes('accounts:balances');return(await t.db.query(`SELECT a.*,l.name AS legal_entity_name,CASE WHEN $4 THEN coalesce(b.balance_minor,0)::text ELSE NULL END AS balance_minor FROM app.accounts a JOIN app.legal_entities l ON l.id=a.legal_entity_id LEFT JOIN app.account_balances b ON b.account_id=a.id WHERE $1 OR (a.id=ANY($2::bigint[]) AND a.legal_entity_id=ANY($3::bigint[])) ORDER BY a.id`,[t.policy.is_owner,t.policy.account_ids,t.policy.legal_entity_ids,balances])).rows;});}
 async createAccount(ctx:Context,d:Row){return this.command(ctx,'account:create',d,async t=>{this.permit(t,'accounts:create');if(!t.policy.is_owner&&!t.policy.legal_entity_ids.includes(String(d.legal_entity_id)))fail(404,'NOT_FOUND','Empresa não encontrada.');
  const legal=await t.db.query("SELECT id FROM app.legal_entities WHERE id=$1 AND status='active' FOR UPDATE",[d.legal_entity_id]);if(!legal.rowCount)fail(404,'NOT_FOUND','Empresa não encontrada.');if(String(d.opening_on)>today())fail(422,'FUTURE_DATE','A abertura não pode ser futura.');
  if(d.is_default)await t.db.query('UPDATE app.accounts SET is_default=false,version=version+1 WHERE legal_entity_id=$1 AND is_default',[d.legal_entity_id]);
  const a=(await t.db.query('INSERT INTO app.accounts(legal_entity_id,name,kind,opening_on,is_default) VALUES($1,$2,$3,$4,$5) RETURNING *',[d.legal_entity_id,d.name,d.kind,d.opening_on,d.is_default])).rows[0];
  await t.db.query('INSERT INTO app.account_balances(account_id) VALUES($1)',[a.id]);await this.post(t,a.id,String(d.opening_on),BigInt(String(d.opening_minor)),'opening','Saldo inicial');
  await this.audit(t,'account',a.id,'create',null,a);return a;});}
 async updateAccount(ctx:Context,rid:string,d:Row){return this.command(ctx,'account:update:'+rid,d,async t=>{this.permit(t,'accounts:update');const [a]=await this.accounts(t,[rid],false);this.version(t,a!);if(d.status==='archived'&&(await t.db.query("SELECT 1 FROM app.entries WHERE account_id=$1 AND status='open' LIMIT 1",[rid])).rowCount)fail(409,'OPEN_ENTRIES','Liquide ou cancele os lançamentos pendentes antes de arquivar.');const n=(await t.db.query('UPDATE app.accounts SET name=$2,status=$3,is_default=CASE WHEN $3=\'archived\' THEN false ELSE is_default END,version=version+1 WHERE id=$1 RETURNING *',[rid,d.name,d.status])).rows[0];await this.audit(t,'account',rid,'update',a,n);return n;});}
 async catalog(ctx:Context,type:Catalog){return this.transaction(ctx,async t=>{this.permit(t,`${type}:view`);return(await t.db.query(`SELECT * FROM app.${type.replace('-','_')} ORDER BY id LIMIT 1000`)).rows;});}
 async saveCatalog(ctx:Context,type:Catalog,data:Row,rid?:string){return this.command(ctx,`${type}:${rid??'create'}`,data,async t=>{this.permit(t,`${type}:${rid?'update':'create'}`);const table=type.replace('-','_');const keys=Object.keys(data);let before=null;if(rid){before=(await t.db.query(`SELECT * FROM app.${table} WHERE id=$1 FOR UPDATE`,[rid])).rows[0];if(!before)fail(404,'NOT_FOUND','Cadastro não encontrado.');this.version(t,before);}
  const r=rid?await t.db.query(`UPDATE app.${table} SET ${keys.map((k,i)=>`${k}=$${i+2}`).join(',')},version=version+1 WHERE id=$1 RETURNING *`,[rid,...Object.values(data)]):await t.db.query(`INSERT INTO app.${table}(${keys.join(',')}) VALUES(${keys.map((_,i)=>`$${i+1}`).join(',')}) RETURNING *`,Object.values(data));await this.audit(t,type,r.rows[0].id,rid?'update':'create',before,r.rows[0]);return r.rows[0];});}
 async allocationData(t:Tx,d:EntryInput){const result=[];for(const a of d.allocations){let group='unclassified';if(a.category_id){const cat=(await t.db.query("SELECT * FROM app.categories WHERE id=$1 AND status='active' FOR SHARE",[a.category_id])).rows[0];if(!cat||cat.direction!==d.direction)fail(422,'CATEGORY_DIRECTION','A categoria deve corresponder ao tipo do lançamento.');group=cat.reporting_group;}if(a.cost_center_id&&!(await t.db.query("SELECT id FROM app.cost_centers WHERE id=$1 AND status='active'",[a.cost_center_id])).rowCount)fail(422,'COST_CENTER','Centro de custo indisponível.');result.push({...a,reporting_group:group});}if(!this.allowedEntry(t,d.direction,result.map(a=>a.reporting_group)))fail(403,'FORBIDDEN','A classificação está fora do seu acesso.');return result;}
 async entry(ctx:Context,d:EntryInput,rid?:string){return this.command(ctx,`entry:${rid??'create'}`,d,async t=>{this.permit(t,`entries:${rid?'update':'create'}`);await this.accounts(t,[d.account_id]);let before=null;
  if(rid){before=(await t.db.query('SELECT * FROM app.entries WHERE id=$1 FOR UPDATE',[rid])).rows[0];if(!before||before.account_id!==d.account_id)fail(404,'NOT_FOUND','Lançamento não encontrado nesta conta.');await this.checkEntry(t,before);this.version(t,before);if(before.status!=='open')fail(409,'ENTRY_NOT_OPEN','Somente lançamentos pendentes podem ser editados.');}
  if(d.party_id&&!(await t.db.query("SELECT id FROM app.parties WHERE id=$1 AND status='active'",[d.party_id])).rowCount)fail(422,'PARTY','Contato indisponível.');
  const allocations=await this.allocationData(t,d);
  const values=[d.account_id,d.party_id,d.direction,d.title,d.notes,d.amount_minor,d.due_on,d.competence_on];
  const e=rid?(await t.db.query('UPDATE app.entries SET account_id=$1,party_id=$2,direction=$3,title=$4,notes=$5,amount_minor=$6,due_on=$7,competence_on=$8,version=version+1 WHERE id=$9 RETURNING *',[...values,rid])).rows[0]:(await t.db.query('INSERT INTO app.entries(account_id,party_id,direction,title,notes,amount_minor,due_on,competence_on) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',values)).rows[0];
  if(rid){if((await t.db.query('SELECT 1 FROM app.settlements WHERE entry_id=$1 LIMIT 1',[rid])).rowCount)fail(409,'HAS_HISTORY','Lançamento com histórico de liquidação deve ser cancelado e recriado para alterar valores.');await t.db.query('DELETE FROM app.entry_allocations WHERE entry_id=$1',[rid]);await t.db.query('DELETE FROM app.entry_labels WHERE entry_id=$1',[rid]);}
  for(const a of allocations)await t.db.query('INSERT INTO app.entry_allocations(entry_id,amount_minor,due_on,competence_on,category_id,cost_center_id,reporting_group) VALUES($1,$2,$3,$4,$5,$6,$7)',[e.id,a.amount_minor,d.due_on,d.competence_on,a.category_id,a.cost_center_id,a.reporting_group]);
  for(const label of new Set(d.label_ids)){if(!(await t.db.query("SELECT id FROM app.labels WHERE id=$1 AND status='active'",[label])).rowCount)fail(422,'LABEL','Marcador indisponível.');await t.db.query('INSERT INTO app.entry_labels VALUES($1,$2)',[e.id,label]);}
  await this.audit(t,'entry',e.id,rid?'update':'create',before,{...e,allocations});return e;});}
 async checkEntry(t:Tx,e:Row){const a=(await t.db.query('SELECT * FROM app.accounts WHERE id=$1',[e.account_id])).rows[0];const lines=(await t.db.query('SELECT * FROM app.entry_allocations WHERE entry_id=$1 ORDER BY id',[e.id])).rows;if(!this.allowed(t,a)||!this.allowedEntry(t,String(e.direction),lines.map(l=>l.reporting_group)))fail(404,'NOT_FOUND','Lançamento não encontrado.');return lines;}
 async mutateEntry(ctx:Context,rid:string,action:'settle'|'reverse'|'cancel',data:Row){return this.command(ctx,`entry:${rid}:${action}`,data,async t=>{this.permit(t,`entries:${action}`);
  const ref=(await t.db.query('SELECT account_id FROM app.entries WHERE id=$1',[rid])).rows[0];if(!ref)fail(404,'NOT_FOUND','Lançamento não encontrado.');const [a]=await this.accounts(t,[ref.account_id],false);
  const e=(await t.db.query('SELECT * FROM app.entries WHERE id=$1 FOR UPDATE',[rid])).rows[0];const lines=await this.checkEntry(t,e);this.version(t,e);
  if(action==='cancel'){if(e.status!=='open')fail(409,'ENTRY_NOT_OPEN','Reverta a liquidação antes de cancelar.');await t.db.query('UPDATE app.entry_allocations SET cancelled=true WHERE entry_id=$1',[rid]);}
  else {
   if(action==='settle'&&(a!.status!=='active'||a!.entity_status!=='active'))fail(409,'ARCHIVED','Conta ou empresa arquivada.');
   if(e.status!==(action==='settle'?'open':'settled'))fail(409,'INVALID_STATE','A situação do lançamento não permite esta ação.');const date=String(action==='settle'?data.settled_on:data.effective_on);this.date(date,a!);
   let original=null;if(action==='reverse'){original=(await t.db.query('SELECT s.* FROM app.settlements s WHERE entry_id=$1 AND reversal_of IS NULL AND NOT EXISTS(SELECT 1 FROM app.settlements r WHERE r.reversal_of=s.id) ORDER BY id DESC LIMIT 1',[rid])).rows[0];if(!original)fail(409,'NO_SETTLEMENT','Liquidação não encontrada.');if(date<original.settled_on)fail(422,'REVERSAL_DATE','A reversão não pode anteceder a liquidação.');}
   const s=(await t.db.query('INSERT INTO app.settlements(entry_id,account_id,amount_minor,settled_on,reversal_of,reason,actor_id) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[rid,e.account_id,e.amount_minor,date,original?.id??null,data.reason??'',ctx.actor])).rows[0];
   for(const l of lines){const item=(await t.db.query('INSERT INTO app.settlement_items(settlement_id,allocation_id,amount_minor) VALUES($1,$2,$3) RETURNING id',[s.id,l.id,l.amount_minor])).rows[0];let reversal=null;if(original)reversal=(await t.db.query('SELECT c.id FROM app.cash_postings c JOIN app.settlement_items i ON i.id=c.settlement_item_id WHERE i.settlement_id=$1 AND i.allocation_id=$2',[original.id,l.id])).rows[0].id;
    await this.post(t,e.account_id,date,BigInt(l.amount_minor)*(e.direction==='income'?1n:-1n)*(original?-1n:1n),original?'reversal':'settlement',e.title,item.id,null,reversal);}
   await t.db.query('UPDATE app.entry_allocations SET settled_minor=CASE WHEN $2 THEN amount_minor ELSE 0 END WHERE entry_id=$1',[rid,action==='settle']);
  }
  const n=(await t.db.query('UPDATE app.entries SET status=$2,version=version+1 WHERE id=$1 RETURNING *',[rid,action==='cancel'?'cancelled':action==='settle'?'settled':'open'])).rows[0];await this.audit(t,'entry',rid,action,e,{...n,reason:data.reason??''});return n;});}
 async transfer(ctx:Context,d:Row){return this.command(ctx,'transfer',d,async t=>{this.permit(t,'entries:transfer');const accounts=await this.accounts(t,[String(d.source_account_id),String(d.destination_account_id)]);for(const a of accounts)this.date(String(d.effective_on),a);
  const r=(await t.db.query('INSERT INTO app.transfers(source_account_id,destination_account_id,amount_minor,effective_on,scope,reason) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[d.source_account_id,d.destination_account_id,d.amount_minor,d.effective_on,accounts[0]!.legal_entity_id===accounts[1]!.legal_entity_id?'intra_cnpj':'intercompany',d.reason])).rows[0];
  await this.post(t,String(d.source_account_id),String(d.effective_on),-BigInt(String(d.amount_minor)),'transfer','Transferência entre contas',null,r.id);await this.post(t,String(d.destination_account_id),String(d.effective_on),BigInt(String(d.amount_minor)),'transfer','Transferência entre contas',null,r.id);await this.audit(t,'transfer',r.id,'create',null,r);return r;});}
 async reverseTransfer(ctx:Context,rid:string,d:Row){return this.command(ctx,'transfer:reverse:'+rid,d,async t=>{this.permit(t,'entries:transfer');const ref=(await t.db.query('SELECT * FROM app.transfers WHERE id=$1',[rid])).rows[0];if(!ref)fail(404,'NOT_FOUND','Transferência não encontrada.');const acc=await this.accounts(t,[ref.source_account_id,ref.destination_account_id],false);const r=(await t.db.query('SELECT * FROM app.transfers WHERE id=$1 FOR UPDATE',[rid])).rows[0];this.version(t,r);if(r.status!=='confirmed')fail(409,'REVERSED','Transferência já revertida.');for(const a of acc)this.date(String(d.effective_on),a);if(String(d.effective_on)<r.effective_on)fail(422,'REVERSAL_DATE','A reversão não pode anteceder a transferência.');const posts=await t.db.query("SELECT * FROM app.cash_postings WHERE transfer_id=$1 AND kind='transfer' ORDER BY account_id",[rid]);for(const p of posts.rows)await this.post(t,p.account_id,String(d.effective_on),-BigInt(p.signed_minor),'reversal',String(d.reason),null,rid,p.id);const n=(await t.db.query("UPDATE app.transfers SET status='reversed',version=version+1 WHERE id=$1 RETURNING *",[rid])).rows[0];await this.audit(t,'transfer',rid,'reverse',r,n);return n;});}
 entryFilter(t:Tx,q:ListQuery){const values:unknown[]=[t.policy.is_owner,t.policy.account_ids,t.policy.legal_entity_ids,t.policy.directions,t.policy.groups,q.from,q.to];let sql=`($1 OR (e.account_id=ANY($2::bigint[]) AND a.legal_entity_id=ANY($3::bigint[]) AND e.direction=ANY($4::text[]) AND NOT EXISTS(SELECT 1 FROM app.entry_allocations ax WHERE ax.entry_id=e.id AND NOT(ax.reporting_group=ANY($5::text[]))))) AND e.due_on BETWEEN $6 AND $7`;
  for(const [key,column]of [['account_id','e.account_id'],['legal_entity_id','a.legal_entity_id'],['direction','e.direction'],['status','e.status']]as const)if(q[key]){values.push(q[key]);sql+=` AND ${column}=$${values.length}`;}if(q.party_id){values.push(q.party_id);sql+=` AND e.party_id=$${values.length}`;}
  for(const [key,column] of [['group','reporting_group'],['category_id','category_id'],['cost_center_id','cost_center_id']] as const)if(q[key]){values.push(q[key]);sql+=` AND EXISTS(SELECT 1 FROM app.entry_allocations af WHERE af.entry_id=e.id AND af.${column}=$${values.length})`;}
  if(q.label_id){values.push(q.label_id);sql+=` AND EXISTS(SELECT 1 FROM app.entry_labels el WHERE el.entry_id=e.id AND el.label_id=$${values.length})`;}
  if(q.focus){values.push(today());sql+=` AND e.status='open' AND e.due_on${q.focus==='today'?'=':'<'}$${values.length}::date`;}
  if(q.q){values.push(`%${q.q.replace(/[\\%_]/g,'\\$&')}%`);sql+=` AND e.title ILIKE $${values.length}`;}return {sql,values};}
 async entrySummary(ctx:Context,q:ListQuery){return this.transaction(ctx,async t=>{this.permit(t,'entries:view');const f=this.entryFilter(t,q);return(await t.db.query(`SELECT count(*)::int AS count,
  coalesce(sum(e.amount_minor) FILTER(WHERE e.status='open' AND e.direction='income'),0)::text AS receivable_minor,
  coalesce(sum(e.amount_minor) FILTER(WHERE e.status='open' AND e.direction='expense'),0)::text AS payable_minor,
  coalesce(sum(e.amount_minor) FILTER(WHERE e.status='settled' AND e.direction='income'),0)::text AS received_minor,
  coalesce(sum(e.amount_minor) FILTER(WHERE e.status='settled' AND e.direction='expense'),0)::text AS paid_minor
  FROM app.entries e JOIN app.accounts a ON a.id=e.account_id WHERE ${f.sql}`,f.values)).rows[0];});}
 async entries(ctx:Context,q:ListQuery,agenda=false){return this.transaction(ctx,async t=>{this.permit(t,'entries:view');const f=this.entryFilter(t,q);if(agenda)f.sql+=" AND e.status='open'";if(q.cursor){let c;try{c=JSON.parse(Buffer.from(q.cursor,'base64url').toString());if(!Array.isArray(c)||c.length!==2||!/^\d{4}-\d{2}-\d{2}$/.test(c[0])||!/^\d+$/.test(c[1]))throw 0;}catch{fail(400,'INVALID_CURSOR','Cursor inválido.');}f.values.push(c[0],c[1]);f.sql+=` AND (e.due_on,e.id)<($${f.values.length-1}::date,$${f.values.length}::bigint)`;}f.values.push(q.limit+1);const rows=(await t.db.query(`SELECT e.*,a.name AS account_name,l.name AS legal_entity_name,p.name AS party_name,(SELECT string_agg(DISTINCT c.name,', ' ORDER BY c.name) FROM app.entry_allocations ac JOIN app.categories c ON c.id=ac.category_id WHERE ac.entry_id=e.id) AS category_names FROM app.entries e JOIN app.accounts a ON a.id=e.account_id JOIN app.legal_entities l ON l.id=a.legal_entity_id LEFT JOIN app.parties p ON p.id=e.party_id WHERE ${f.sql} ORDER BY e.due_on DESC,e.id DESC LIMIT $${f.values.length}`,f.values)).rows;const more=rows.length>q.limit;const items=rows.slice(0,q.limit);const last=items.at(-1);return{items,next_cursor:more?Buffer.from(JSON.stringify([last!.due_on,last!.id])).toString('base64url'):null};});}
 async detail(ctx:Context,rid:string){return this.transaction(ctx,async t=>{this.permit(t,'entries:view');const e=(await t.db.query('SELECT * FROM app.entries WHERE id=$1',[rid])).rows[0];if(!e)fail(404,'NOT_FOUND','Lançamento não encontrado.');const allocations=await this.checkEntry(t,e);const settlements=(await t.db.query('SELECT * FROM app.settlements WHERE entry_id=$1 ORDER BY id',[rid])).rows;const labels=(await t.db.query('SELECT label_id FROM app.entry_labels WHERE entry_id=$1',[rid])).rows;const history=(await t.db.query("SELECT action,occurred_at,actor_id,before_data,after_data FROM app.audit_events WHERE resource_type='entry' AND resource_id=$1 ORDER BY occurred_at DESC,id DESC LIMIT 100",[rid])).rows;return{...e,allocations,settlements,label_ids:labels.map(l=>l.label_id),history};});}
 async dashboard(ctx:Context,q:ListQuery){return this.transaction(ctx,async t=>{this.permit(t,'dashboard:view');const f=this.entryFilter(t,q);const totals=(await t.db.query(`SELECT coalesce(sum(e.amount_minor) FILTER(WHERE e.status='open' AND e.direction='income'),0)::text AS receivable_minor,coalesce(sum(e.amount_minor) FILTER(WHERE e.status='open' AND e.direction='expense'),0)::text AS payable_minor,coalesce(sum(e.amount_minor) FILTER(WHERE e.status='open' AND e.due_on<$${f.values.length+1}::date),0)::text AS overdue_minor FROM app.entries e JOIN app.accounts a ON a.id=e.account_id WHERE ${f.sql}`,[...f.values,today()])).rows[0];const balances=t.policy.is_owner||t.policy.permissions.includes('accounts:balances');let balance=null;let daily:Row[]=[];if(balances){const args=[t.policy.is_owner,t.policy.account_ids,t.policy.legal_entity_ids,q.account_id??null,q.legal_entity_id??null];const scope='($1 OR(a.id=ANY($2::bigint[]) AND a.legal_entity_id=ANY($3::bigint[]))) AND ($4::bigint IS NULL OR a.id=$4) AND ($5::bigint IS NULL OR a.legal_entity_id=$5)';balance=(await t.db.query(`SELECT coalesce(sum(b.balance_minor),0)::text AS total FROM app.accounts a JOIN app.account_balances b ON b.account_id=a.id WHERE ${scope}`,args)).rows[0].total;daily=(await t.db.query(`SELECT d.effective_on, sum(d.net_minor)::text AS net_minor FROM app.cash_daily d JOIN app.accounts a ON a.id=d.account_id WHERE ${scope} AND d.effective_on BETWEEN $6 AND $7 GROUP BY d.effective_on ORDER BY d.effective_on`,[...args,q.from,q.to])).rows;}return{...totals,balance_minor:balance,daily,from:q.from,to:q.to};});}
 async statement(ctx:Context,rid:string,q:ListQuery){return this.transaction(ctx,async t=>{this.permit(t,'accounts:view');this.permit(t,'accounts:balances');await this.accounts(t,[rid],false);if(!t.policy.is_owner&&(new Set(t.policy.directions).size!==2||new Set(t.policy.groups).size!==7))fail(403,'FULL_SCOPE_REQUIRED','Extrato integral exige acesso a todas as classificações da conta.');const opening=(await t.db.query('SELECT coalesce(sum(net_minor),0)::text AS value FROM app.cash_daily WHERE account_id=$1 AND effective_on<$2',[rid,q.from])).rows[0].value;const totals=(await t.db.query('SELECT coalesce(sum(net_minor),0)::text AS value FROM app.cash_daily WHERE account_id=$1 AND effective_on BETWEEN $2 AND $3',[rid,q.from,q.to])).rows[0].value;let cursor='';const args:unknown[]=[rid,q.from,q.to,opening];if(q.cursor){let c;try{c=JSON.parse(Buffer.from(q.cursor,'base64url').toString());if(!Array.isArray(c)||c.length!==2||!/^\d{4}-\d{2}-\d{2}$/.test(c[0])||!/^\d+$/.test(c[1]))throw 0;}catch{fail(400,'INVALID_CURSOR','Cursor inválido.');}args.push(c[0],c[1]);cursor=' AND (effective_on,id)>($5::date,$6::bigint)';}args.push(q.limit+1);const rows=(await t.db.query(`SELECT * FROM (SELECT *, ($4::numeric+sum(signed_minor) OVER(ORDER BY effective_on,id))::text AS balance_minor FROM app.cash_postings WHERE account_id=$1 AND effective_on BETWEEN $2 AND $3) s WHERE true ${cursor} ORDER BY effective_on,id LIMIT $${args.length}`,args)).rows;const items=rows.slice(0,q.limit);const last=items.at(-1);return{opening_minor:opening,closing_minor:(BigInt(opening)+BigInt(totals)).toString(),items,next_cursor:rows.length>q.limit?Buffer.from(JSON.stringify([last!.effective_on,last!.id])).toString('base64url'):null};});}
}
