import {createHash,randomBytes,createCipheriv,createDecipheriv} from 'node:crypto';
import type {Finance,Context,Tx} from './finance.js';
import {Evidence} from './evidence.js';
import {AppError} from '../../contracts/src/index.js';
const fail=(message:string,status=422):never=>{throw new AppError(status,'GOOGLE_INTEGRATION',message);};
type Tokens={access_token:string;refresh_token?:string;expires_at:number};
type GoogleEvent={id:string;summary?:string;description?:string;location?:string;htmlLink?:string;status?:string;start?:{date?:string;dateTime?:string};end?:{date?:string;dateTime?:string};organizer?:{email?:string;displayName?:string};attendees?:{email?:string;displayName?:string;responseStatus?:string}[];etag?:string};
export const googleConfigured=()=>!!(process.env.GOOGLE_CLIENT_ID&&process.env.GOOGLE_CLIENT_SECRET&&process.env.BETTER_AUTH_SECRET&&process.env.BETTER_AUTH_URL);
const callback=()=>`${process.env.BETTER_AUTH_URL}/v1/integrations/google/callback`;
const key=()=>createHash('sha256').update('black-finance/google/v1/'+process.env.BETTER_AUTH_SECRET).digest();
export function seal(value:unknown){if(!process.env.BETTER_AUTH_SECRET)fail('Chave de proteção indisponível.',503);const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key(),iv),bytes=Buffer.concat([cipher.update(JSON.stringify(value),'utf8'),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),bytes]).toString('base64');}
export function unseal(value:string):Tokens{const b=Buffer.from(value,'base64'),cipher=createDecipheriv('aes-256-gcm',key(),b.subarray(0,12));cipher.setAuthTag(b.subarray(12,28));return JSON.parse(Buffer.concat([cipher.update(b.subarray(28)),cipher.final()]).toString());}
export class GoogleIntegration {
 constructor(public f:Finance,public request:typeof fetch=fetch){}
 async connection(t:Tx){this.f.permit(t,'integrations:view');const c=(await t.db.query("SELECT * FROM app.provider_connections WHERE user_id=$1 AND provider='google' AND status='connected'",[t.ctx.actor])).rows[0];if(!c)fail('Conecte sua conta Google em Integrações.',409);return c;}
 async status(ctx:Context){return this.f.transaction(ctx,async t=>{this.f.permit(t,'integrations:view');return {configured:googleConfigured(),callback:googleConfigured()?callback():null,connection:(await t.db.query("SELECT id,provider,settings,status,version FROM app.provider_connections WHERE user_id=$1 AND provider='google'",[ctx.actor])).rows[0]??null,missing:googleConfigured()?[]:['Configurar cliente OAuth Google no servidor e autorizar a conta nesta tela.']};});}
 async start(ctx:Context){if(!googleConfigured())fail('O administrador precisa configurar GOOGLE_CLIENT_ID e GOOGLE_CLIENT_SECRET no servidor e cadastrar a URL de retorno. Nenhuma senha Google é solicitada aqui.',503);return this.f.transaction(ctx,async t=>{this.f.permit(t,'integrations:update');const state=randomBytes(32).toString('base64url'),verifier=randomBytes(32).toString('base64url');await t.db.query('DELETE FROM app.oauth_states WHERE user_id=$1 OR expires_at<now()',[ctx.actor]);await t.db.query("INSERT INTO app.oauth_states(state_hash,user_id,verifier,expires_at) VALUES($1,$2,$3,now()+interval '10 minutes')",[createHash('sha256').update(state).digest('hex'),ctx.actor,verifier]);const params=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID!,redirect_uri:callback(),response_type:'code',access_type:'offline',prompt:'consent',state,code_challenge:createHash('sha256').update(verifier).digest('base64url'),code_challenge_method:'S256',scope:'https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/calendar.calendarlist.readonly https://www.googleapis.com/auth/calendar.events.readonly'});return {url:`https://accounts.google.com/o/oauth2/v2/auth?${params}`};});}
 async tokenRequest(params:Record<string,string>){const r=await this.request('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({...params,client_id:process.env.GOOGLE_CLIENT_ID!,client_secret:process.env.GOOGLE_CLIENT_SECRET!}),signal:AbortSignal.timeout(15000)});if(!r.ok)fail('A autorização Google expirou ou foi recusada. Reconecte sua conta.',409);return await r.json() as {access_token:string;refresh_token?:string;expires_in:number};}
 async complete(ctx:Context,state:string,code:string){if(!googleConfigured())fail('Google não configurado.',503);const saved=await this.f.transaction(ctx,async t=>{this.f.permit(t,'integrations:update');const r=(await t.db.query('DELETE FROM app.oauth_states WHERE state_hash=$1 AND user_id=$2 AND expires_at>now() RETURNING verifier',[createHash('sha256').update(state).digest('hex'),ctx.actor])).rows[0];if(!r)fail('Autorização expirada. Inicie novamente.',409);return r;});const tokens=await this.tokenRequest({code,code_verifier:saved.verifier,redirect_uri:callback(),grant_type:'authorization_code'});if(!tokens.refresh_token)fail('A autorização precisa permitir acesso offline. Reconecte sua conta.',409);
  await this.f.transaction(ctx,async t=>{this.f.permit(t,'integrations:update');const r=(await t.db.query("INSERT INTO app.provider_connections(user_id,tokens) VALUES($1,$2) ON CONFLICT(user_id,provider) DO UPDATE SET tokens=$2,status='connected',settings='{}',version=app.provider_connections.version+1 RETURNING id",[ctx.actor,seal({...tokens,expires_at:Date.now()+tokens.expires_in*1000})])).rows[0];await this.f.audit(t,'integration',r.id,'connect',null,{provider:'google'});});return {connected:true};
 }
 async access(ctx:Context){const c=await this.f.transaction(ctx,t=>this.connection(t));let tokens=unseal(c.tokens);if(tokens.expires_at<Date.now()+60000){try{const refreshed=await this.tokenRequest({refresh_token:tokens.refresh_token!,grant_type:'refresh_token'});tokens={...tokens,...refreshed,expires_at:Date.now()+refreshed.expires_in*1000};await this.f.transaction(ctx,async t=>{const current=await this.connection(t);if(current.tokens!==c.tokens)fail('A conexão foi alterada; atualize a página.',409);await t.db.query('UPDATE app.provider_connections SET tokens=$2 WHERE id=$1',[c.id,seal(tokens)]);});}catch(e){if(e instanceof AppError)await this.f.transaction(ctx,async t=>{await t.db.query("UPDATE app.provider_connections SET status='reauthorize' WHERE id=$1 AND tokens=$2",[c.id,c.tokens]);});throw e;}}return {connection:c,token:tokens.access_token};}
 async call(token:string,path:string,init:RequestInit={}){const r=await this.request(`https://www.googleapis.com/${path}`,{...init,headers:{...init.headers,Authorization:`Bearer ${token}`},signal:AbortSignal.timeout(15000)});if(!r.ok){if(r.status===401||r.status===403)fail('Acesso ao Google recusado. Confira a autorização e reconecte se necessário.',409);if(r.status===404)fail('Arquivo ou agenda removido ou sem acesso.',404);fail('Google indisponível. Tente novamente mais tarde.',503);}return r.json();}
 async choices(ctx:Context){const {token}=await this.access(ctx);const [calendars,folders]=await Promise.all([this.call(token,'calendar/v3/users/me/calendarList?maxResults=100'),this.call(token,`drive/v3/files?${new URLSearchParams({q:"mimeType='application/vnd.google-apps.folder' and trashed=false",fields:'files(id,name)',pageSize:'100'})}`)]);return {calendars:calendars.items??[],folders:folders.files??[]};}
 async settings(ctx:Context,d:{calendars:string[];folder:string|null}){const choices=await this.choices(ctx);if(d.calendars.some(id=>!choices.calendars.some((c:{id:string})=>c.id===id))||d.folder&&!choices.folders.some((x:{id:string})=>x.id===d.folder))fail('Selecione somente pastas e agendas disponíveis.');return this.f.command(ctx,'integrations:update',d,async t=>{const c=await this.connection(t);this.f.version(t,c);const r=(await t.db.query('UPDATE app.provider_connections SET settings=$2,version=version+1 WHERE id=$1 RETURNING id,settings,status,version',[c.id,d])).rows[0];await this.f.audit(t,'integration',c.id,'settings',null,{calendar_count:d.calendars.length,folder:d.folder});return r;});}
 async folder(ctx:Context,name:string){await this.f.transaction(ctx,async t=>this.f.permit(t,'integrations:update'));const {token}=await this.access(ctx);return this.call(token,'drive/v3/files?fields=id,name',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,mimeType:'application/vnd.google-apps.folder'})});}
 async disconnect(ctx:Context){return this.f.command(ctx,'integrations:update',{action:'disconnect'},async t=>{const c=await this.connection(t);await t.db.query("UPDATE app.provider_connections SET tokens='',settings='{}',status='disconnected',version=version+1 WHERE id=$1",[c.id]);await this.f.audit(t,'integration',c.id,'disconnect',null,{provider:'google'});return {id:c.id,status:'disconnected'};});}
 async sync(ctx:Context,from:string,to:string){await this.f.transaction(ctx,async t=>this.f.permit(t,'integrations:update'));const {token,connection:c}=await this.access(ctx);let count=0;const pending:GoogleEvent[]=[];const calendars=(c.settings.calendars??[]) as string[];if(!calendars.length)fail('Selecione e salve as agendas primeiro.');
  for(const calendar of calendars){pending.length=0;let cursor:string|undefined;do{const params=new URLSearchParams({timeMin:`${from}T00:00:00-03:00`,timeMax:`${to}T23:59:59-03:00`,singleEvents:'true',maxResults:'250',showDeleted:'true',...(cursor?{pageToken:cursor}:{})});const result=await this.call(token,`calendar/v3/calendars/${encodeURIComponent(calendar)}/events?${params}`);pending.push(...(result.items??[]));cursor=result.nextPageToken;if(pending.length>1000)fail('Mais de 1.000 eventos na agenda. Reduza o período.');}while(cursor);
   await this.f.transaction(ctx,async t=>{const fresh=await this.connection(t);if(!fresh.settings.calendars?.includes(calendar))fail('Agenda desmarcada durante a consulta.',409);await t.db.query("UPDATE app.external_events SET payload=jsonb_set(payload,'{status}','\"unavailable\"') WHERE connection_id=$1 AND calendar_id=$2 AND start_on BETWEEN $3 AND $4 AND NOT(external_id=ANY($5::text[]))",[c.id,calendar,from,to,pending.map(e=>e.id)]);for(const ev of pending){if(ev.status==='cancelled'){await t.db.query("UPDATE app.external_events SET payload=jsonb_set(payload,'{status}','\"cancelled\"'),seen_at=now() WHERE connection_id=$1 AND calendar_id=$2 AND external_id=$3",[c.id,calendar,ev.id]);}const start=ev.start?.date??ev.start?.dateTime?.slice(0,10);if(!start)continue;const end=ev.end?.date??ev.end?.dateTime?.slice(0,10)??start;const payload={status:ev.status??'confirmed',description:ev.description?.slice(0,10000)??'',location:ev.location??'',url:ev.htmlLink??'',organizer:ev.organizer??{},attendees:(ev.attendees??[]).slice(0,100),start:ev.start,end:ev.end,etag:ev.etag};await t.db.query('INSERT INTO app.external_events(connection_id,calendar_id,external_id,title,start_on,end_on,payload) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(connection_id,calendar_id,external_id) DO UPDATE SET title=$4,start_on=$5,end_on=$6,payload=$7,seen_at=now()',[c.id,calendar,ev.id,ev.summary?.slice(0,240)??'Evento sem título',start,end,payload]);count++;}await this.f.audit(t,'integration',c.id,'calendar_sync',null,{from,to,count:pending.length});});
  }return {id:c.id,count};
 }
 async events(ctx:Context,from:string,to:string){return this.f.transaction(ctx,async t=>{this.f.permit(t,'integrations:view');return {items:(await t.db.query("SELECT ev.*,u.display_name AS person FROM app.external_events ev JOIN app.provider_connections c ON c.id=ev.connection_id JOIN app.users u ON u.id=c.user_id WHERE c.user_id=$1 AND c.status='connected' AND c.settings->'calendars' ? ev.calendar_id AND ev.start_on<=$3 AND ev.end_on>=$2 AND ev.payload->>'status' IN('confirmed','tentative') ORDER BY ev.start_on,ev.id LIMIT 500",[ctx.actor,from,to])).rows};});}
 async copy(ctx:Context,id:string){const evidence=new Evidence(this.f);await this.f.transaction(ctx,async t=>{this.f.permit(t,'integrations:update');await evidence.document(t,id);});const {token,connection:c}=await this.access(ctx);if(!c.settings.folder)fail('Selecione uma pasta em Integrações.');let copy=await this.f.transaction(ctx,async t=>{const fresh=await this.connection(t);if(fresh.settings.folder!==c.settings.folder)fail('Pasta alterada. Atualize a tela.',409);return (await t.db.query('SELECT * FROM app.document_copies WHERE document_id=$1 AND connection_id=$2',[id,c.id])).rows[0];});
  if(!copy){const generated=await this.call(token,'drive/v3/files/generateIds?count=1&space=drive&type=files');copy=await this.f.transaction(ctx,async t=>{await this.connection(t);await evidence.document(t,id);await t.db.query("INSERT INTO app.document_copies(document_id,connection_id,external_id,url,status) VALUES($1,$2,$3,$4,'pending') ON CONFLICT DO NOTHING",[id,c.id,generated.ids[0],`https://drive.google.com/file/d/${generated.ids[0]}/view`]);return (await t.db.query('SELECT * FROM app.document_copies WHERE document_id=$1 AND connection_id=$2',[id,c.id])).rows[0];});}
  try{const meta=await this.call(token,`drive/v3/files/${encodeURIComponent(copy.external_id)}?fields=id,trashed,webViewLink,parents`);if(meta.trashed)fail('Arquivo na lixeira do Drive. O original do sistema está preservado.',404);await this.f.transaction(ctx,async t=>{await this.connection(t);await evidence.document(t,id);await t.db.query("UPDATE app.document_copies SET status='available',checked_at=now() WHERE document_id=$1 AND connection_id=$2",[id,c.id]);});return {id,url:copy.url,status:'available'};}catch(e){if(!(e instanceof AppError)||e.statusCode!==404||copy.status!=='pending'){await this.f.transaction(ctx,async t=>{await t.db.query("UPDATE app.document_copies SET status='unavailable',checked_at=now() WHERE document_id=$1 AND connection_id=$2",[id,c.id]);});throw e;}}
  const doc=await this.f.transaction(ctx,t=>evidence.document(t,id,true));const boundary='bf_'+randomBytes(16).toString('hex'),metadata={id:copy.external_id,name:doc.filename,parents:[c.settings.folder],appProperties:{bf_document:id,sha256:doc.content_hash}};const body=Buffer.concat([Buffer.from(`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify(metadata)}\r\n--${boundary}\r\nContent-Type: ${doc.mime}\r\n\r\n`),doc.original,Buffer.from(`\r\n--${boundary}--`)]);await this.call(token,'upload/drive/v3/files?uploadType=multipart&fields=id',{method:'POST',headers:{'Content-Type':`multipart/related; boundary=${boundary}`},body});await this.f.transaction(ctx,async t=>{await this.connection(t);await evidence.document(t,id);await t.db.query("UPDATE app.document_copies SET status='available',checked_at=now() WHERE document_id=$1 AND connection_id=$2",[id,c.id]);await this.f.audit(t,'document',id,'drive_copy',null,{connection_id:c.id,external_id:copy.external_id});});return {id,url:copy.url,status:'available'};
 }
}
