import {useState} from 'react';
import {Plus,X} from 'lucide-react';
import {Button} from '@/components/ui/button';import {Input} from '@/components/ui/input';import {Label} from '@/components/ui/label';import {Textarea} from '@/components/ui/textarea';
import {type API,type Item,text,minor,decimal,civilToday,groupNames} from './lib/api';
export type Option={value:string;label:string};export type Field={key:string;label:string;type?:string;options?:Option[];optional?:boolean};
export const options=(items:Item[])=>items.map(i=>({value:i.id,label:text(i.name)}));
export function Select({value,onChange,options,id,empty=true}:{value:string;onChange:(v:string)=>void;options:Option[];id?:string;empty?:boolean}){return<select id={id} className="select" value={value} onChange={e=>onChange(e.target.value)}>{empty&&<option value="">Selecione</option>}{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>;}
export function Editor({api,type,item,fields,catalogs,account,company,done}:{api:API;type:string;item?:Item;fields:Field[];catalogs:Record<string,Item[]>;account:string;company:string;done:()=>void}){
 const [values,setValues]=useState<Record<string,string>>(()=>Object.fromEntries(fields.map(f=>[f.key,item?f.key.endsWith('_minor')?decimal(item[f.key]):text(item[f.key]):f.type==='date'?civilToday():f.key==='status'?'active':f.key==='direction'?'expense':f.key==='kind'?'bank':f.key==='opening_minor'?'0,00':f.key==='account_id'?account:f.key==='legal_entity_id'?company:''])));
 const [lines,setLines]=useState<{amount:string;category_id:string;cost_center_id:string}[]>(()=>item?.allocations?(item.allocations as Item[]).map(a=>({amount:decimal(a.amount_minor),category_id:text(a.category_id),cost_center_id:text(a.cost_center_id)})):[{amount:'',category_id:'',cost_center_id:''}]);
 const [tags,setTags]=useState<string[]>(()=>item?.label_ids as string[]??[]);const[busy,setBusy]=useState(false);const[error,setError]=useState('');
 // Keep the key after uncertain network failures; change it when the payload changes.
 const [attempt,setAttempt]=useState<{payload:string;key:string}>();
 const set=(k:string,v:string)=>setValues(prev=>({...prev,[k]:v}));
 async function save(e:React.FormEvent){e.preventDefault();setError('');setBusy(true);try{const body:Record<string,unknown>={};for(const f of fields)body[f.key]=f.type==='checkbox'?values[f.key]==='true':f.key.endsWith('_minor')?minor(values[f.key]??'0'):values[f.key]??'';if(type==='entries'){body.party_id=body.party_id||null;body.allocations=lines.map(l=>({amount_minor:minor(lines.length===1?values.amount_minor??'':l.amount),category_id:l.category_id||null,cost_center_id:l.cost_center_id||null}));body.label_ids=tags;}
 const payload=JSON.stringify(body);const key=attempt?.payload===payload?attempt.key:crypto.randomUUID();setAttempt({payload,key});await api(`/v1/${type}${item?`/${item.id}`:''}`,item?'PATCH':'POST',body,item?.version,key);done();}catch(e){const err=e as Error&{fields?:Record<string,string[]>};setError(err.fields?Object.values(err.fields).flat().join(' ')||err.message:err.message);}finally{setBusy(false);}}
 return<form className="editor-form" onSubmit={e=>{void save(e);}}><div className="form-grid">{fields.map(f=><div className={`field ${f.type==='textarea'?'full':''}`} key={f.key}><Label htmlFor={`edit-${f.key}`}>{f.label}{f.optional&&<small> opcional</small>}</Label>{f.type==='checkbox'?<input type="checkbox" id={`edit-${f.key}`} checked={values[f.key]==='true'} onChange={e=>set(f.key,String(e.target.checked))}/>:f.options?<Select id={`edit-${f.key}`} value={values[f.key]??''} options={f.options} onChange={v=>set(f.key,v)} empty/>:f.type==='textarea'?<Textarea id={`edit-${f.key}`} value={values[f.key]??''} onChange={e=>set(f.key,e.target.value)}/>:<Input id={`edit-${f.key}`} type={f.type??'text'} value={values[f.key]??''} onChange={e=>set(f.key,e.target.value)} required={!f.optional} disabled={busy}/>}</div>)}</div>
 {type==='entries'&&<><div className="section-title"><div><h3>Classificação e rateio</h3><p>A soma das linhas deve coincidir com o total.</p></div><Button type="button" variant="outline" size="sm" onClick={()=>setLines(ls=>[...ls,{amount:'',category_id:'',cost_center_id:''}])}><Plus size={14}/>Dividir</Button></div>{lines.map((line,i)=><div className="allocation-row" key={i}><div className="field"><Label htmlFor={`category-${i}`}>Categoria</Label><Select id={`category-${i}`} value={line.category_id} options={(catalogs.categories??[]).filter(c=>c.direction===values.direction&&c.status==='active').map(c=>({value:c.id,label:text(c.name)}))} onChange={v=>setLines(ls=>ls.map((l,j)=>j===i?{...l,category_id:v}:l))}/></div><div className="field"><Label htmlFor={`center-${i}`}>Centro de custo</Label><Select id={`center-${i}`} value={line.cost_center_id} options={options(catalogs['cost-centers']??[])} onChange={v=>setLines(ls=>ls.map((l,j)=>j===i?{...l,cost_center_id:v}:l))}/></div>{lines.length>1&&<><div className="field"><Label htmlFor={`allocation-${i}`}>Valor (R$)</Label><Input id={`allocation-${i}`} value={line.amount} onChange={e=>setLines(ls=>ls.map((l,j)=>j===i?{...l,amount:e.target.value}:l))}/></div><Button type="button" variant="ghost" size="icon" aria-label={`Remover linha ${i+1}`} onClick={()=>setLines(ls=>ls.filter((_,j)=>j!==i))}><X size={14}/></Button></>}</div>)}{!!catalogs.labels?.length&&<div className="field"><Label>Marcadores</Label><div className="tag-picker">{catalogs.labels.map(l=><label key={l.id}><input type="checkbox" checked={tags.includes(l.id)} onChange={e=>setTags(v=>e.target.checked?[...v,l.id]:v.filter(x=>x!==l.id))}/>{text(l.name)}</label>)}</div></div>}</>}
 {error&&<p role="alert" className="form-error">{error}</p>}<div className="form-footer"><p>O registro só é criado ao salvar.</p><Button disabled={busy}>{busy?'Salvando…':'Salvar registro'}</Button></div></form>;
}
export function makeFields(type:string,item:Item|undefined,entities:Item[],accounts:Item[],catalogs:Record<string,Item[]>):Field[]{
 const name={key:'name',label:'Nome'};const status={key:'status',label:'Situação',options:[{value:'active',label:'Ativo'},{value:'archived',label:'Arquivado'}]};const direction={key:'direction',label:'Tipo',options:[{value:'income',label:'Receita'},{value:'expense',label:'Despesa'}]};
 if(type==='legal-entities')return[name,{key:'cnpj',label:'CNPJ'},...(item?[status]:[])];
 if(type==='accounts')return item?[name,status]:[name,{key:'legal_entity_id',label:'Empresa',options:options(entities.filter(i=>i.status==='active'))},{key:'kind',label:'Tipo de conta',options:[{value:'bank',label:'Banco'},{value:'cash',label:'Caixa'},{value:'other',label:'Outros'}]},{key:'opening_on',label:'Data de abertura',type:'date'},{key:'opening_minor',label:'Saldo inicial (R$)'},{key:'is_default',label:'Conta principal',type:'checkbox'}];
 if(type==='transfers')return[{key:'source_account_id',label:'Conta de origem',options:options(accounts.filter(a=>a.status==='active'))},{key:'destination_account_id',label:'Conta de destino',options:options(accounts.filter(a=>a.status==='active'))},{key:'amount_minor',label:'Valor (R$)'},{key:'effective_on',label:'Data da realização',type:'date'},{key:'reason',label:'Motivo',optional:true}];
 if(type==='entries')return[{key:'title',label:'Descrição'},direction,{key:'account_id',label:'Conta',options:options(accounts.filter(a=>a.status==='active'))},{key:'amount_minor',label:'Valor (R$)'},{key:'due_on',label:'Vencimento',type:'date'},{key:'competence_on',label:'Competência',type:'date'},{key:'party_id',label:'Contato',options:options(catalogs.parties??[]),optional:true},{key:'notes',label:'Observações',type:'textarea',optional:true}];
 if(type==='parties')return[name,{key:'document',label:'CPF / CNPJ',optional:true},{key:'email',label:'E-mail',type:'email',optional:true},{key:'phone',label:'Telefone',optional:true},status];
 if(type==='categories')return[name,direction,{key:'reporting_group',label:'Grupo gerencial',options:Object.entries(groupNames).map(([value,label])=>({value,label}))},status];return[name,status];
}
