import {TooltipProvider} from '@/components/ui/tooltip';
import {Feedback} from '@/components/Feedback';
import React,{useEffect,useState,useCallback} from 'react';import {createRoot} from 'react-dom/client';import type {SupabaseClient} from '@supabase/supabase-js';import {meSchema,type Me} from '../../../packages/contracts/src/index';const Workspace=React.lazy(()=>import('./Workspace').then(m=>({default:m.Workspace}))); import {type API,ApiError} from './lib/api';import {AppButton as Button} from '@/components/AppButton';import {Input} from '@/components/ui/input';import {Label} from '@/components/ui/label';import {ArrowRight,ShieldCheck} from 'lucide-react';import './style.css';
function App(){const[client,setClient]=useState<SupabaseClient>();const[cloud,setCloud]=useState(false);const[ready,setReady]=useState(false);const[user,setUser]=useState<Me>();const[error,setError]=useState('');const[busy,setBusy]=useState(false);const[email,setEmail]=useState('');const[password,setPassword]=useState('');
 const api:API=useCallback(async<T,>(path:string,method='GET',body?:unknown,version?:number,key?:string):Promise<T>=>{const headers:Record<string,string>={};if(body!==undefined){headers['Content-Type']='application/json';headers['Idempotency-Key']=key??crypto.randomUUID();}if(version!==undefined)headers['If-Match']=String(version);if(client){const{data}=await client.auth.getSession();if(data.session)headers.Authorization=`Bearer ${data.session.access_token}`;}const response=await fetch(path,{method,headers,body:body===undefined?undefined:JSON.stringify(body),credentials:'same-origin'});const result=await response.json();if(!response.ok){if(response.status===401||result.code==='ACCESS_REVOKED')setUser(undefined);throw new ApiError(result.message??'Não foi possível concluir a operação.',response.status,result.field_errors);}return result as T;},[client]);
 useEffect(()=>{let active=true;let unsubscribe=()=>{};async function setup(){const response=await fetch('/v1/config');if(!response.ok)throw new Error('Serviço indisponível.');const config=await response.json();if(config.authMode==='cookie'){if(active)setCloud(true);const me=await fetch('/v1/me');if(me.ok&&active)setUser(meSchema.parse(await me.json()));}else{const {createClient}=await import('@supabase/supabase-js');if(!active)return;const supabase=createClient(config.supabaseUrl,config.supabasePublishableKey);if(active)setClient(supabase);const sub=supabase.auth.onAuthStateChange((_event,session)=>{if(!active)return;if(!session){setUser(undefined);return;}void fetch('/v1/me',{headers:{Authorization:`Bearer ${session.access_token}`}}).then(async r=>{if(!r.ok)throw new Error('Seu acesso não está ativo.');return meSchema.parse(await r.json());}).then(u=>{if(active)setUser(u);}).catch(e=>{if(active)setError(e.message);});});unsubscribe=()=>sub.data.subscription.unsubscribe();}}void setup().catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setReady(true);});return()=>{active=false;unsubscribe();};},[]);
 async function login(e:React.FormEvent){e.preventDefault();setError('');setBusy(true);try{if(cloud){const response=await fetch('/api/auth/sign-in/email',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password}),credentials:'same-origin'});if(!response.ok)throw new Error('E-mail ou senha inválidos.');setUser(meSchema.parse(await api('/v1/me')));}else{const result=await client!.auth.signInWithPassword({email,password});if(result.error)throw new Error('E-mail ou senha inválidos.');}setPassword('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function logout(){try{if(cloud)await fetch('/api/auth/sign-out',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});else await client?.auth.signOut();setUser(undefined);}catch{setError('Não foi possível sair. Tente novamente.');}}
 if(user)return<React.Suspense fallback={<div className="loading-screen" role="status">Preparando seu financeiro…</div>}><Workspace api={api} user={user} logout={()=>{void logout();}}/></React.Suspense>;
 return<main className="login-page"><section className="login-story"><img src="/brand/logo.svg" alt="Black Finance"/><p className="eyebrow">GESTÃO FINANCEIRA INTERNA</p><h1>Clareza para cuidar<br/>do que é seu.</h1><p>Suas empresas, suas contas e cada movimento.<br/>Tudo no mesmo lugar.</p><div className="login-grid-art" aria-hidden="true"><span/><span/><span/><span/></div><small>Uma organização. Todas as suas contas.</small></section><section className="login-form"><div className="login-form-inner"><span className="login-icon"><ShieldCheck size={24}/></span><p className="eyebrow">BEM-VINDO À BLACK FINANCE</p><h2>Acesse seu financeiro</h2><p className="muted">Use o acesso disponibilizado pelo administrador.</p><form onSubmit={e=>{void login(e);}}><div className="field"><Label htmlFor="email">E-mail</Label><Input id="email" type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} required/></div><div className="field"><Label htmlFor="password">Senha</Label><Input id="password" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></div>{error&&<Feedback error>{error}</Feedback>}<Button disabled={!ready||busy} className="w-full">{!ready?'Conectando…':busy?'Entrando…':'Entrar'}<ArrowRight size={17}/></Button></form><div className="login-note"><span className="live-dot"/>Ambiente de teste · dados de demonstração</div></div><small className="login-footer">Black Finance · Informação que dá direção.</small></section></main>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><TooltipProvider delayDuration={300}><App/></TooltipProvider></React.StrictMode>);
