import {PeriodNavigator} from '@/components/TransactionControls';
import {ReferenceDashboard,AccountPanel,ProgressPair,CashLine,MonthControl,overviewTotals,amount} from '@/components/ReferenceDashboard';
import {ReferenceEntryList} from '@/components/ReferenceEntryList';
import {QuickEntry} from '@/components/QuickEntry';
import {DropdownMenu,DropdownMenuContent,DropdownMenuItem,DropdownMenuSeparator,DropdownMenuTrigger} from '@/components/ui/dropdown-menu';
import {FileText,BarChart3,Upload,CheckCheck,ChevronsLeft,ChevronDown,MoreHorizontal,Filter} from 'lucide-react';
import {GettingStarted} from '@/components/GettingStarted';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {BookOpen} from 'lucide-react';
import {Feedback} from '@/components/Feedback';
import {useEffect,useState,useCallback,useRef} from 'react';
import {LayoutDashboard,ArrowLeftRight,Wallet,Building2,Users,Tags,Shapes,Network,CalendarDays,Plus,LogOut,ChevronRight,ChevronLeft,Search,Menu,ShieldCheck,History,SlidersHorizontal,RefreshCw,Check,Undo2,Pencil,ArrowRight} from 'lucide-react';
import {AppButton as Button} from '@/components/AppButton';import {Card,CardContent} from '@/components/ui/card';import {Input} from '@/components/ui/input';import {Label} from '@/components/ui/label';import {Textarea} from '@/components/ui/textarea';import {Badge} from '@/components/ui/badge';import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';import {Sheet,SheetContent,SheetTitle} from '@/components/ui/sheet';import {Skeleton} from '@/components/ui/skeleton';
import {type API,type Item,text,money,date,civilToday,groupNames} from './lib/api';import {type Policy} from '../../../packages/contracts/src/finance';import {Editor,Select,options,makeFields} from './Editor';import {PolicyEditor} from './PolicyEditor';
const nav=[['start','Comece por aqui',BookOpen],['dashboard','Página inicial',LayoutDashboard],['entries','Transações',ArrowLeftRight],['agenda','Agenda',CalendarDays],['accounts','Contas bancárias',Wallet],['transfers','Transferências',ArrowRight],['legal-entities','Empresas',Building2],['parties','Contatos',Users],['invoices','Faturas',FileText],['reports','Relatórios',BarChart3],['imports','Importações',Upload],['reconciliation','Conciliações (OFX)',CheckCheck],['categories','Categorias',Shapes],['cost-centers','Centros de custo',Network],['labels','Marcadores',Tags],['users','Acessos',ShieldCheck],['audit-events','Histórico',History],['organization','Organização',SlidersHorizontal]]as const;
function Status({value}:{value:unknown}){const s=text(value);return <Badge variant="outline" className={`status-${s}`}>{({open:'Pendente',settled:'Liquidado',cancelled:'Cancelado',active:'Ativo',archived:'Arquivado',confirmed:'Confirmada',reversed:'Revertida',suspended:'Suspenso'}as Record<string,string>)[s]??s}</Badge>;}
export function Workspace({api,user,logout}:{api:API;user:{display_name:string;email:string};logout:()=>void}){
 const [direction,setDirection]=useState('');const [group,setGroup]=useState('');const [focus,setFocus]=useState('');const [party,setParty]=useState('');const [category,setCategory]=useState('');const [center,setCenter]=useState('');const [label,setLabel]=useState('');const [advanced,setAdvanced]=useState<string[]>([]);const [summary,setSummary]=useState<Item>();const [debouncedSearch,setDebouncedSearch]=useState('');
 const [page,setPage]=useState('dashboard');const [overview,setOverview]=useState<Item>();const [bootstrapReady,setBootstrapReady]=useState(false);const [quick,setQuick]=useState(false);const [unavailable,setUnavailable]=useState('');const [menuSearch,setMenuSearch]=useState('');const [collapsed,setCollapsed]=useState(false);const [sort,setSort]=useState('due_on');const [order,setOrder]=useState('desc');const initialized=useRef(false);const [mobile,setMobile]=useState(false);const [entities,setEntities]=useState<Item[]>([]);const [accounts,setAccounts]=useState<Item[]>([]);const [catalogs,setCatalogs]=useState<Record<string,Item[]>>({});const [profile,setProfile]=useState<Item&{policy:Policy}>();
 const now=civilToday();const [from,setFrom]=useState(`${now.slice(0,7)}-01`);const [to,setTo]=useState(`${now.slice(0,7)}-${new Date(Number(now.slice(0,4)),Number(now.slice(5,7)),0).getDate()}`);const [company,setCompany]=useState('');const [account,setAccount]=useState('');const [search,setSearch]=useState('');const [status,setStatus]=useState('');const [cursor,setCursor]=useState<string>();const [cursorStack,setCursorStack]=useState<(string|undefined)[]>([]);
 const [items,setItems]=useState<Item[]>([]);const [next,setNext]=useState<string|null>(null);const [dashboard,setDashboard]=useState<Item>();const [statement,setStatement]=useState<Item>();const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [revision,setRevision]=useState(0);const [editor,setEditor]=useState<{type:string;item?:Item;direction?:string}>();const [detail,setDetail]=useState<Item>();const [confirm,setConfirm]=useState<{item:Item;action:string;key:string}>();const [busy,setBusy]=useState(false);const [actionDate,setActionDate]=useState(now);const [reason,setReason]=useState('');
 const can=(resource:string,action='view')=>!!profile&&(profile.policy.is_owner||profile.policy.permissions.includes(`${resource}:${action}`));const refresh=()=>setRevision(v=>v+1);
 const bootstrap=useCallback(async()=>{const p=await api<Item&{policy:Policy}>('/v1/organization-profile');setProfile(p);const allowed=(r:string)=>p.policy.is_owner||p.policy.permissions.includes(`${r}:view`);setEntities((await api<{items:Item[]}>('/v1/legal-entities')).items);if(allowed('accounts')){const list=(await api<{items:Item[]}>('/v1/accounts')).items;setAccounts(list);if(!initialized.current){setAccount(text((list.find(a=>a.is_default&&a.status==='active')??list.find(a=>a.status==='active'))?.id));initialized.current=true;}}if(!allowed('dashboard'))setPage(current=>current==='dashboard'?(allowed('entries')?'entries':'start'):current);const result:Record<string,Item[]>={};await Promise.all(['parties','categories','cost-centers','labels'].map(async key=>{if(allowed(key))result[key]=(await api<{items:Item[]}>(`/v1/${key}`)).items;}));setCatalogs(result);setBootstrapReady(true);},[api]);
 useEffect(()=>{void bootstrap().catch(e=>setError(e.message));},[bootstrap,revision]);
 useEffect(()=>{const timer=setTimeout(()=>setDebouncedSearch(search),300);return()=>clearTimeout(timer);},[search]);
 const resetPagination=()=>{setCursor(undefined);setCursorStack([]);};
 const clearRefinements=()=>{setSearch('');setDebouncedSearch('');setStatus('');setDirection('');setGroup('');setFocus('');setParty('');setCategory('');setCenter('');setLabel('');resetPagination();};
 const query=new URLSearchParams({from,to,limit:'20'});
 for(const [key,value] of [['legal_entity_id',company],['account_id',account],['q',debouncedSearch],['status',page==='agenda'?'open':status],['direction',direction],['group',group],['focus',focus],['party_id',party],['category_id',category],['cost_center_id',center],['label_id',label]] as const)if(value)query.set(key,value);
 const queryString=query.toString();const scopeQuery=new URLSearchParams({from,to,...(account?{account_id:account}:{}),...(company?{legal_entity_id:company}:{})}).toString();
 useEffect(()=>{let active=true;if(profile&&(profile.policy.is_owner||profile.policy.permissions.includes('dashboard:view'))&&['dashboard','entries','transfers'].includes(page)){setOverview(undefined);setDashboard(undefined);void Promise.all([api<Item>(`/v1/overview?${scopeQuery}`),api<Item>(`/v1/dashboard?${scopeQuery}`)]).then(([o,d])=>{if(active){setOverview(o);setDashboard(d);}}).catch(e=>{if(active)setError(e.message);});}return()=>{active=false;};},[api,scopeQuery,profile,page,revision]);
 useEffect(()=>{let active=true;setSummary(undefined);if(['entries','agenda'].includes(page))void api<Item>(`/v1/entries/summary?${queryString}`).then(data=>{if(active)setSummary(data);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[api,page,queryString,revision]);
 useEffect(()=>{let active=true;setLoading(true);setError('');setItems([]);setNext(null);const query=new URLSearchParams(queryString);if(cursor)query.set('cursor',cursor);query.set('sort',sort);query.set('order',order);
 async function load(){if(page==='start')return;else if(page==='dashboard')return;else if(page==='organization')return;else if(page==='statement'||page==='reports'){if(!account)return;const d=await api<Item&{items:Item[];next_cursor:string|null}>(`/v1/accounts/${account}/statement?${query}`);if(active){setStatement(d);setItems(d.items);setNext(d.next_cursor);}}else{const data=await api<{items:Item[];next_cursor?:string|null}>(`/v1/${page}${['entries','agenda','transfers'].includes(page)?`?${query}`:''}`);if(active){setItems(data.items);setNext(data.next_cursor??null);}}}
 void load().catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[api,page,queryString,cursor,revision,profile,sort,order]);
 const navigate=(p:string)=>{setPage(p);setMobile(false);clearRefinements();setQuick(false);setAdvanced([]);setSort('due_on');setOrder('desc');if(p==='entries')setDirection('income');setNotice('');};
 const openEntries=(kind:string,attention='')=>{navigate('entries');setDirection(kind);setFocus(attention);if(attention)setStatus('open');};
 const showDetail=async(item:Item)=>{setError('');try{setDetail(await api<Item>(`/v1/entries/${item.id}`));}catch(e){setError((e as Error).message);}};
 const openAction=(item:Item,action:string)=>{setReason('');setActionDate(now);setConfirm({item,action,key:crypto.randomUUID()});};
 const action=async()=>{if(!confirm)return;setBusy(true);setError('');try{const {item,action,key}=confirm;await api(`/v1/${page==='transfers'?'transfers':'entries'}/${item.id}/${action==='settle'?'settlements':action}`,'POST',action==='settle'?{settled_on:actionDate,reason}:action==='cancel'?{reason}:{effective_on:actionDate,reason},item.version,key);setConfirm(undefined);setDetail(undefined);setNotice('Operação registrada com sucesso.');refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const createType=page==='agenda'?'entries':page;
 const permittedNav=nav.filter(([key])=>key==='start'||(['invoices','imports','reconciliation'].includes(key)?!!profile:key==='reports'?can('accounts')&&can('accounts','balances'):(key==='organization'||key==='legal-entities'?can('organization','manage'):key==='users'||key==='audit-events'?can('users','manage'):can(key==='agenda'||key==='transfers'?'entries':key))));
 const navButton=(key:string)=>{const n=permittedNav.find(n=>n[0]===key);if(!n)return null;const [id,title,Icon]=n;const missing=['invoices','imports','reconciliation'].includes(id);return <Button key={id} aria-label={title} variant="ghost" className={`nav-link ${(page===id||id==='entries'&&page==='transfers')?'selected':''}`} aria-current={page===id?'page':undefined} onClick={()=>missing?setUnavailable(title):navigate(id)}><Icon size={15}/><span>{title}</span>{missing&&<small aria-hidden="true" title="Ainda não implantado">○</small>}</Button>;};
 const settingsKeys=['organization','users','legal-entities','categories','cost-centers','accounts','labels','audit-events','agenda','start'];
 const navItems=<><a className="brand" href="#" onClick={e=>{e.preventDefault();navigate('dashboard');}}><img src="/brand/logo-dark.svg" alt="Black Finance"/></a><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" aria-label="Menu do usuário" className="ref-user"><span className="avatar">{user.display_name.slice(0,1)}</span><span><strong>{user.display_name}</strong><small>{user.email}</small></span><ChevronDown size={12}/></Button></DropdownMenuTrigger><DropdownMenuContent align="start" className="ref-profile-menu">{settingsKeys.map(key=>{const n=permittedNav.find(n=>n[0]===key);return n&&<DropdownMenuItem key={key} onSelect={()=>navigate(key)}>{n[1]}</DropdownMenuItem>;})}<DropdownMenuSeparator/><DropdownMenuItem onSelect={logout}><LogOut size={14}/>Sair</DropdownMenuItem></DropdownMenuContent></DropdownMenu><form className="ref-global-search" onSubmit={e=>{e.preventDefault();navigate('entries');setDirection('');setSearch(menuSearch);}}><Search size={13}/><Input disabled={!can('entries')} aria-label="Pesquisar transações" placeholder="Pesquisar transações…" value={menuSearch} onChange={e=>setMenuSearch(e.target.value)}/></form><nav aria-label="Menu principal">{['dashboard','entries','invoices','parties','reports'].map(navButton)}<div className="ref-nav-separator"/>{['imports','reconciliation'].map(navButton)}</nav><Button className="ref-collapse" variant="ghost" size="icon" aria-label={collapsed?'Expandir menu':'Recolher menu'} onClick={()=>setCollapsed(v=>!v)}><ChevronsLeft size={16}/></Button><div className="sidebar-foot"><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" aria-label="Selecionar CNPJ" className="ref-org"><Building2 size={22}/><span><strong>{text(profile?.name)||'Black Finance'}</strong><small>{text(entities.find(e=>e.id===company)?.name)||'Todos os CNPJs'}</small></span><ArrowLeftRight size={12}/></Button></DropdownMenuTrigger><DropdownMenuContent align="start"><DropdownMenuItem onSelect={()=>{setCompany('');setAccount('');resetPagination();}}>Todos os CNPJs</DropdownMenuItem>{entities.map(e=><DropdownMenuItem key={e.id} onSelect={()=>{setCompany(e.id);setAccount(text(accounts.find(a=>a.legal_entity_id===e.id&&a.status==='active')?.id));resetPagination();}}>{text(e.name)}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu></div></>;
 const baseTotals=overviewTotals(overview),visibleTotals=summary?{receivable:amount(summary.receivable_minor),received:amount(summary.received_minor),payable:amount(summary.payable_minor),paid:amount(summary.paid_minor)}:undefined;
 const panel=<AccountPanel accounts={accounts.filter(a=>!company||a.legal_entity_id===company)} account={account} onChange={id=>{setAccount(id);resetPagination();}} balance={can('dashboard')?dashboard?.balance_minor:accounts.find(a=>a.id===account)?.balance_minor} pending={baseTotals.receivable-baseTotals.payable}/>;
 const changeMonth=(a:string,b:string)=>{setFrom(a);setTo(b);resetPagination();setQuick(false);};
 const transactionNav=<div className="ref-transaction-nav"><MonthControl from={from} to={to} onChange={changeMonth}/><div className="ref-type-tabs" aria-label="Tipos de transação">{[['income','','Recebimentos'],['expense','fixed','Despesas fixas'],['expense','variable','Despesas variáveis'],['expense','people','Pessoas'],['expense','taxes','Impostos']].map(([d,g,label])=><Button key={label} variant="outline" size="sm" className={page==='entries'&&direction===d&&group===g?`active ${d}`:''} aria-pressed={page==='entries'&&direction===d&&group===g} onClick={()=>{if(page!=='entries')navigate('entries');setDirection(d!);setGroup(g!);setCategory('');setQuick(false);resetPagination();}}>{label}</Button>)}<Button variant="outline" size="icon" title="Todas as despesas" aria-label="Todas as despesas" onClick={()=>{navigate('entries');setDirection('expense');}}><MoreHorizontal size={14}/></Button><Button variant="outline" size="sm" className={page==='transfers'?'active':''} onClick={()=>navigate('transfers')}>Transferências</Button></div></div>;
 const entryTable=(rows:Item[])=><ReferenceEntryList creation={page==='entries'&&can('entries','create')&&(quick?<QuickEntry api={api} account={account} accounts={accounts} catalogs={catalogs} direction={direction||'income'} group={group} done={()=>{setQuick(false);refresh();setNotice('Transação salva.');}} cancel={()=>setQuick(false)}/>:<Button variant="ghost" className="ref-new-row" onClick={()=>setQuick(true)}><Plus size={14}/>Nova transação</Button>)} empty={<Empty title="A lista está vazia" description="Adicione uma transação ou ajuste os filtros para encontrar seus registros." action={can('entries','create')?<Button onClick={()=>setQuick(true)}><Plus size={14}/>Adicionar</Button>:undefined}/>} rows={rows} direction={direction} today={now} can={can} onDetail={i=>{void showDetail(i);}} onAction={openAction} sort={sort} onSort={key=>{setSort(key);setOrder(key===sort&&order==='desc'?'asc':'desc');resetPagination();}}/>;
 return <div className={`workspace reference-workspace ${collapsed?'sidebar-collapsed':''}`}><aside className="sidebar">{navItems}</aside><Sheet open={mobile} onOpenChange={setMobile}><SheetContent side="left" className="mobile-nav"><SheetTitle className="sr-only">Navegação</SheetTitle>{navItems}</SheetContent></Sheet><div className="workspace-main"><div className="ref-test-banner">Ambiente de teste Black Finance · Dados de demonstração · Nenhum pagamento bancário é enviado</div><header className="topbar"><Button variant="ghost" size="icon" className="mobile-menu" aria-label="Abrir menu" onClick={()=>setMobile(true)}><Menu/></Button><h1 aria-label={page==='dashboard'?'Página inicial':undefined}>{page==='dashboard'?`Olá, ${user.display_name.split(' ')[0]}.`:page==='statement'?'Extrato':page==='transfers'?'Transações':nav.find(n=>n[0]===page)?.[1]}</h1><div className="ref-header-actions">{['entries','agenda','legal-entities','accounts','parties','categories','cost-centers','labels','transfers'].includes(page)&&can(createType==='legal-entities'?'organization':createType==='transfers'?'entries':createType,createType==='legal-entities'?'manage':createType==='transfers'?'transfer':'create')&&<Button variant="outline" size="icon" aria-label={page==='entries'?'Adicionar transação':page==='transfers'?'Nova transferência':'Adicionar'} onClick={()=>setEditor({type:createType,direction})}><Plus size={15}/></Button>}{['entries','transfers'].includes(page)&&<div className="search"><Search size={14}/><Input aria-label="Buscar lançamentos" placeholder="Pesquisar…" value={search} onChange={e=>{setSearch(e.target.value);resetPagination();}}/></div>}<Button variant="outline" size="icon" title="Como usar" aria-label="Abrir guia de uso" onClick={()=>navigate('start')}><BookOpen size={15}/></Button><Button variant="outline" size="icon" aria-label="Atualizar" onClick={refresh}><RefreshCw size={15}/></Button></div></header>
 <main className={`content ${['entries','agenda'].includes(page)?'transaction-page':''}`}><div className="page-heading"><div><p className="eyebrow">CLAREZA PARA CADA DECISÃO</p><h1>{page==='statement'?'Extrato da conta':nav.find(n=>n[0]===page)?.[1]}</h1><p className="muted">{page==='start'?'Um roteiro simples para conhecer seu financeiro.':page==='dashboard'?'Acompanhe o que já aconteceu e organize os próximos movimentos.':page==='entries'?'Receitas e despesas, da previsão à realização.':page==='agenda'?'Seus compromissos pendentes, organizados por vencimento.':({accounts:'Contas bancárias e caixas, com saldo e extrato por CNPJ.',transfers:'Registre dinheiro que mudou entre suas próprias contas.',parties:'Clientes e fornecedores vinculados às suas receitas e despesas.',categories:'Classifique a finalidade de cada receita e despesa.', 'cost-centers':'Identifique a área ou projeto responsável pelo valor.',labels:'Crie etiquetas para encontrar lançamentos relacionados.', 'legal-entities':'Cadastre os CNPJs internos da sua organização.'} as Record<string,string>)[page]??'Organize a operação com informação consistente e rastreável.'}</p></div><div className="heading-actions"><Button variant="outline" size="icon" aria-label="Atualizar" onClick={refresh}><RefreshCw size={16}/></Button>{['entries','agenda','legal-entities','accounts','parties','categories','cost-centers','labels','transfers'].includes(page)&&can(createType==='legal-entities'?'organization':createType==='transfers'?'entries':createType,createType==='legal-entities'?'manage':createType==='transfers'?'transfer':'create')&&<Button onClick={()=>setEditor({type:createType,direction})}><Plus size={16}/>{page==='transfers'?'Nova transferência':page==='entries'||page==='agenda'?'Novo lançamento':'Adicionar'}</Button>}</div></div>
 {error&&<Feedback error action={<Button variant="ghost" size="sm" onClick={()=>setError('')}>Fechar</Button>}>{error}</Feedback>}{notice&&<Feedback>{notice}</Feedback>}
 {['agenda','statement','reports'].includes(page)&&<div className="filters"><div><Label htmlFor="filter-company">Empresa</Label><Select id="filter-company" value={company} onChange={v=>{setCompany(v);setAccount('');resetPagination();}} options={[{value:'',label:'Todas as empresas'},...options(entities)]} empty={false}/></div><div><Label htmlFor="filter-account">Conta</Label><Select id="filter-account" value={account} onChange={v=>{setAccount(v);resetPagination();}} options={[...(page==='statement'?[]:[{value:'',label:'Todas as contas'}]),...options(accounts.filter(a=>!company||a.legal_entity_id===company))]} empty={page==='statement'}/></div><div><Label htmlFor="period-from">De</Label><Input id="period-from" type="date" value={from} onChange={e=>{setFrom(e.target.value);resetPagination();}}/></div><div><Label htmlFor="period-to">Até</Label><Input id="period-to" type="date" value={to} onChange={e=>{setTo(e.target.value);resetPagination();}}/></div></div>}
 {['agenda','statement','reports'].includes(page)&&<PeriodNavigator from={from} to={to} today={now} onChange={(a,b)=>{setFrom(a);setTo(b);resetPagination();}}/>}
 {(!bootstrapReady&&!error||loading&&!['entries','agenda'].includes(page)||page==='dashboard'&&!overview&&!error)?<div className="loading-grid" aria-label="Carregando"><Skeleton className="h-32"/><Skeleton className="h-32"/><Skeleton className="h-64 col-span-full"/></div>:<>
 {page==='start'&&<GettingStarted navigate={navigate} can={can}/>}
 {page==='dashboard'&&<ReferenceDashboard data={overview} dashboard={dashboard} from={from} to={to} today={now} accountPanel={panel} onMonth={changeMonth} canEntries={can('entries')} onEntries={(kind,g='',day='',attention='')=>{openEntries(kind,attention);setGroup(g);if(day){setFrom(day);setTo(day);setStatus('open');}}} onDetail={i=>{void showDetail(i);}}/>}
 {['entries','transfers'].includes(page)&&<><div className="ref-transaction-summary"><div><small>Resultado previsto no mês</small><strong>{overview?money(baseTotals.received+baseTotals.receivable-baseTotals.paid-baseTotals.payable):'—'}</strong><ProgressPair data={overview}/></div><CashLine compact rows={(dashboard?.daily??[]) as Item[]}/>{panel}</div>{transactionNav}</>}
 {['entries','agenda'].includes(page)&&<><Card className="ref-transactions-card"><CardContent><div className="ref-filter-button"><Button variant="outline" size="sm" aria-expanded={advanced.includes('filters')} onClick={()=>setAdvanced(v=>v.length?[]:['filters'])}><Filter size={13}/>Filtrar</Button></div>
 <Accordion type="multiple" value={advanced} onValueChange={setAdvanced} className="advanced-filters"><AccordionItem value="filters"><AccordionTrigger className="sr-only">Mais filtros{[party,category,center,label].filter(Boolean).length?` (${[party,category,center,label].filter(Boolean).length} ativos)`:''}</AccordionTrigger><AccordionContent><div className="ref-filter-fields"><div><Label htmlFor="ref-from">Data inicial</Label><Input id="ref-from" type="date" value={from} onChange={e=>{setFrom(e.target.value);resetPagination();}}/></div><div><Label htmlFor="ref-to">Data final</Label><Input id="ref-to" type="date" value={to} onChange={e=>{setTo(e.target.value);resetPagination();}}/></div><div><Label>Situação</Label><Select label="Situação dos lançamentos" value={status} onChange={v=>{setStatus(v);if(v!=='open')setFocus('');resetPagination();}} options={[{value:'',label:'Todas'},{value:'open',label:'Não pagas'},{value:'settled',label:'Pago'},{value:'cancelled',label:'Canceladas'}]} empty={false}/></div><div><Label>Vencimento</Label><Select label="Vencimentos" value={focus} onChange={v=>{setFocus(v);if(v)setStatus('open');resetPagination();}} options={[{value:'',label:'Todos'},{value:'today',label:'A vencer hoje'},{value:'overdue',label:'Vencidas (em atraso)'}]} empty={false}/></div></div><div className="filters">{[['Contato',party,setParty,catalogs.parties??[]],['Categoria',category,setCategory,(catalogs.categories??[]).filter(c=>!direction||c.direction===direction)],['Centro de custo',center,setCenter,catalogs['cost-centers']??[]],['Marcador',label,setLabel,catalogs.labels??[]]].map(([name,value,setter,choices])=><div key={String(name)}><Label>{String(name)}</Label><Select label={String(name)} value={value as string} onChange={v=>{(setter as (v:string)=>void)(v);resetPagination();}} options={[{value:'',label:'Todos'},...options(choices as Item[])]} empty={false}/></div>)}</div><Button variant="ghost" size="sm" onClick={()=>{clearRefinements();setDirection('income');}}>Limpar filtros</Button></AccordionContent></AccordionItem></Accordion>
 <div className="list-context" role="status"><span>{loading?'Buscando…':`${summary?.count??'…'} lançamento(s) encontrado(s)`} · vencimento de {date(from)} a {date(to)}</span>{(group||category||center)&&<span>{group?`Grupo: ${groupNames[group]} · `:''}Totais incluem o valor integral de cada lançamento, mesmo com rateio.</span>}<span>Totais por vencimento, sem cancelados. Limpar filtros mantém empresa, conta e período.</span></div>

 {loading?<Skeleton className="h-32"/>:entryTable(items)}
 </CardContent></Card>{visibleTotals&&<Card className="ref-list-total"><CardContent><dl><div><dt>Total</dt><dd>{money(direction==='income'?visibleTotals.receivable+visibleTotals.received:direction==='expense'?visibleTotals.payable+visibleTotals.paid:visibleTotals.receivable+visibleTotals.received+visibleTotals.payable+visibleTotals.paid)}</dd></div><div><dt>{direction==='income'?'Recebido':direction==='expense'?'Pago':'Realizado'}</dt><dd>{money(direction==='income'?visibleTotals.received:direction==='expense'?visibleTotals.paid:visibleTotals.received+visibleTotals.paid)}</dd></div><div><dt>{direction==='income'?'A receber':direction==='expense'?'A pagar':'Pendente'}</dt><dd>{money(direction==='income'?visibleTotals.receivable:direction==='expense'?visibleTotals.payable:visibleTotals.receivable+visibleTotals.payable)}</dd></div></dl></CardContent></Card>}</>}
 {page==='accounts'&&<div className="account-grid">{items.map(i=><Card key={i.id}><CardContent><div className="account-header"><span className="account-icon"><Wallet size={22}/></span><Status value={i.status}/></div><h2>{text(i.name)}</h2><p className="muted">{text(i.legal_entity_name)}</p><div className="account-balance"><small>Saldo realizado</small><strong>{money(i.balance_minor)}</strong></div><div className="account-footer"><Button variant="outline" onClick={()=>{setAccount(i.id);navigate('statement');}}>Ver extrato <ChevronRight size={15}/></Button>{can('accounts','update')&&<Button variant="ghost" size="icon" aria-label={`Editar ${text(i.name)}`} onClick={()=>setEditor({type:'accounts',item:i})}><Pencil size={16}/></Button>}</div></CardContent></Card>)}{!items.length&&<Empty/>}</div>}
 {(page==='statement'||page==='reports')&&<Card><CardContent>{!account?<Empty title="Selecione uma conta para consultar o extrato."/>:<><div className="statement-summary"><span>Saldo anterior <strong>{money(statement?.opening_minor)}</strong></span><ArrowRight size={20}/><span>Saldo ao fim do período <strong>{money(statement?.closing_minor)}</strong></span></div><Table><TableHeader><TableRow><TableHead>Data</TableHead><TableHead>Descrição</TableHead><TableHead>Origem</TableHead><TableHead className="text-right">Movimento</TableHead><TableHead className="text-right">Saldo</TableHead></TableRow></TableHeader><TableBody>{items.map(i=><TableRow key={i.id}><TableCell>{date(i.effective_on)}</TableCell><TableCell>{text(i.description)}</TableCell><TableCell>{({opening:'Abertura',settlement:'Liquidação',transfer:'Transferência',reversal:'Reversão'} as Record<string,string>)[text(i.kind)]}</TableCell><TableCell className="text-right font-bold">{money(i.signed_minor)}</TableCell><TableCell className="text-right">{money(i.balance_minor)}</TableCell></TableRow>)}</TableBody></Table>{!items.length&&<Empty/>}</>}</CardContent></Card>}
 {['legal-entities','parties','categories','cost-centers','labels'].includes(page)&&<Card><CardContent>{items.length?<Table><TableHeader><TableRow><TableHead>Nome</TableHead><TableHead>{page==='legal-entities'?'CNPJ':page==='categories'?'Grupo gerencial':page==='parties'?'Contato':'Identificação'}</TableHead><TableHead>Situação</TableHead><TableHead/></TableRow></TableHeader><TableBody>{items.map(i=><TableRow key={i.id}><TableCell className="font-bold">{text(i.name)}</TableCell><TableCell>{page==='legal-entities'?text(i.cnpj):page==='categories'?groupNames[text(i.reporting_group)]:page==='parties'?text(i.email)||text(i.phone):`#${i.id}`}</TableCell><TableCell><Status value={i.status}/></TableCell><TableCell className="text-right">{can(page==='legal-entities'?'organization':page,page==='legal-entities'?'manage':'update')&&<Button size="icon" variant="ghost" aria-label={`Editar ${text(i.name)}`} onClick={()=>setEditor({type:page,item:i})}><Pencil size={16}/></Button>}</TableCell></TableRow>)}</TableBody></Table>:<Empty/>}</CardContent></Card>}
 {page==='transfers'&&<Card><CardContent>{can('entries','transfer')&&<Button variant="ghost" className="ref-new-row" onClick={()=>setEditor({type:'transfers'})}><Plus size={14}/>Nova transferência</Button>}<p className="helper mb-6">Transferências mudam os saldos das contas; não representam receita ou despesa.</p>{items.length?<Table><TableHeader><TableRow><TableHead>Data</TableHead><TableHead>Origem → Destino</TableHead><TableHead>Escopo</TableHead><TableHead>Valor</TableHead><TableHead>Situação</TableHead><TableHead/></TableRow></TableHeader><TableBody>{items.map(i=><TableRow key={i.id}><TableCell>{date(i.effective_on)}</TableCell><TableCell>{text(i.source_name)} → {text(i.destination_name)}</TableCell><TableCell>{i.scope==='intercompany'?'Entre empresas':'Mesmo CNPJ'}</TableCell><TableCell>{money(i.amount_minor)}</TableCell><TableCell><Status value={i.status}/></TableCell><TableCell>{i.status==='confirmed'&&can('entries','transfer')&&<Button variant="ghost" size="sm" onClick={()=>openAction(i,'reverse')}><Undo2 size={15}/>Reverter</Button>}</TableCell></TableRow>)}</TableBody></Table>:<Empty/>}</CardContent></Card>}
 {page==='organization'&&profile&&<Organization api={api} profile={profile} onSave={()=>{refresh();setNotice('Organização atualizada.');}}/>}
 {page==='users'&&<Card><CardContent><div className="section-title"><div><h2>Acesso à organização</h2><p>Permissões por empresa, conta, direção e grupo gerencial.</p></div></div><Table><TableHeader><TableRow><TableHead>Pessoa</TableHead><TableHead>Papel</TableHead><TableHead>Situação</TableHead><TableHead/></TableRow></TableHeader><TableBody>{items.map(i=><TableRow key={i.id}><TableCell>{text(i.display_name)}<small className="cell-secondary">{text(i.email)}</small></TableCell><TableCell>{i.is_owner?'Proprietário':'Personalizado'}</TableCell><TableCell><Status value={i.status}/></TableCell><TableCell><Button variant="outline" onClick={()=>setEditor({type:'policy',item:i})}>Editar acesso</Button></TableCell></TableRow>)}</TableBody></Table><p className="helper mt-6">Convites e recuperação por e-mail dependem da configuração de envio. Neste teste, os acessos são provisionados pelo administrador.</p></CardContent></Card>}
 {page==='audit-events'&&<Card><CardContent><Table><TableHeader><TableRow><TableHead>Quando</TableHead><TableHead>Recurso</TableHead><TableHead>Ação</TableHead><TableHead>Responsável</TableHead></TableRow></TableHeader><TableBody>{items.map(i=><TableRow key={i.id}><TableCell>{new Date(text(i.occurred_at)).toLocaleString('pt-BR')}</TableCell><TableCell>{text(i.resource_type)} #{text(i.resource_id)}</TableCell><TableCell>{text(i.action)}</TableCell><TableCell className="audit-id">{text(i.actor_id)}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card>}
 {(next||cursor)&&<div className="pagination"><Button variant="outline" disabled={!cursor} onClick={()=>{const history=[...cursorStack];setCursor(history.pop());setCursorStack(history);}}><ChevronLeft size={16}/>Anterior</Button><span>Até 20 registros por página</span><Button variant="outline" disabled={!next} onClick={()=>{setCursorStack(v=>[...v,cursor]);setCursor(next!);}}>Próxima<ChevronRight size={16}/></Button></div>}</>}
 <footer className="page-footer"><span>Black Finance · Gestão financeira interna</span><span>Valores em BRL · Datas de Brasília</span></footer></main></div>
 <Dialog open={!!unavailable} onOpenChange={v=>{if(!v)setUnavailable('');}}><DialogContent><DialogHeader><DialogTitle>{unavailable}</DialogTitle><DialogDescription>Este módulo ainda não está implantado na versão de teste.</DialogDescription></DialogHeader><p>A posição no menu acompanha a referência. A funcionalidade será disponibilizada quando suas regras e operações estiverem implementadas.</p><Button onClick={()=>setUnavailable('')}>Entendi</Button></DialogContent></Dialog>
 {editor&&<Dialog open onOpenChange={v=>{if(!v)setEditor(undefined);}}><DialogContent className="editor-dialog"><DialogHeader><DialogTitle>{editor.type==='policy'?'Permissões de acesso':`${editor.item?'Editar':'Adicionar'} ${editor.type==='entries'?'lançamento':nav.find(n=>n[0]===editor.type)?.[1]?.toLowerCase()??'cadastro'}`}</DialogTitle><DialogDescription>{editor.type==='entries'?'Vencimento, competência e realização são datas independentes.':'As alterações serão registradas no histórico da organização.'}</DialogDescription></DialogHeader>{editor.type==='policy'?<PolicyEditor api={api} item={editor.item!} accounts={accounts} entities={entities} done={()=>{setEditor(undefined);refresh();}}/>:<Editor api={api} type={editor.type} item={editor.item} initialDirection={editor.direction} fields={makeFields(editor.type,editor.item,entities,accounts,catalogs)} catalogs={catalogs} account={account} company={company} done={()=>{setEditor(undefined);refresh();setNotice('Registro salvo com sucesso.');}}/>}</DialogContent></Dialog>}
 <Dialog open={!!detail} onOpenChange={v=>{if(!v)setDetail(undefined);}}><DialogContent className="detail-dialog"><DialogHeader><DialogTitle>{text(detail?.title)}</DialogTitle><DialogDescription>Detalhes e histórico do lançamento</DialogDescription></DialogHeader>{detail&&<><div className="detail-amount"><strong>{money(detail.amount_minor)}</strong><Status value={detail.status}/></div><div className="detail-grid"><span>Vencimento<strong>{date(detail.due_on)}</strong></span><span>Competência<strong>{date(detail.competence_on)}</strong></span><span>Conta<strong>{text(accounts.find(a=>a.id===detail.account_id)?.name)}</strong></span><span>Tipo<strong>{detail.direction==='income'?'Receita':'Despesa'}</strong></span></div><h3>Rateio</h3><Table><TableHeader><TableRow><TableHead>Categoria / Grupo</TableHead><TableHead>Valor</TableHead></TableRow></TableHeader><TableBody>{(detail.allocations as Item[]).map(a=><TableRow key={a.id}><TableCell>{text(catalogs.categories?.find(c=>c.id===a.category_id)?.name)||'Sem categoria'}<small className="cell-secondary">{groupNames[text(a.reporting_group)]}</small></TableCell><TableCell>{money(a.amount_minor)}</TableCell></TableRow>)}</TableBody></Table>{!!detail.notes&&<p className="helper">{text(detail.notes)}</p>}<div className="detail-actions">{detail.status==='open'&&<>{can('entries','settle')&&<Button onClick={()=>openAction(detail,'settle')}><Check size={16}/>Liquidar</Button>}{can('entries','update')&&<Button variant="outline" onClick={()=>{setEditor({type:'entries',item:detail});setDetail(undefined);}}><Pencil size={16}/>Editar</Button>}{can('entries','cancel')&&<Button variant="ghost" onClick={()=>openAction(detail,'cancel')}>Cancelar lançamento</Button>}</>}{detail.status==='settled'&&can('entries','reverse')&&<Button variant="outline" onClick={()=>openAction(detail,'reverse')}><Undo2 size={16}/>Reverter liquidação</Button>}</div><h3>Histórico</h3><div className="timeline">{(detail.history as Item[]).map((h,i)=><div key={i}><span className="timeline-dot"/><strong>{({create:'Criado',update:'Atualizado',settle:'Liquidado',reverse:'Liquidação revertida',cancel:'Cancelado'}as Record<string,string>)[text(h.action)]??text(h.action)}</strong><small>{new Date(text(h.occurred_at)).toLocaleString('pt-BR')}</small></div>)}</div></>}</DialogContent></Dialog>
 <AlertDialog open={!!confirm} onOpenChange={v=>{if(!v&&!busy)setConfirm(undefined);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{confirm?.action==='settle'?'Confirmar liquidação':confirm?.action==='reverse'?'Confirmar reversão':'Cancelar lançamento'}</AlertDialogTitle><AlertDialogDescription>{confirm?.action==='settle'?'Registra o pagamento ou recebimento integral. Não envia dinheiro ao banco.':confirm?.action==='reverse'?'Cria movimentos de sinal contrário e preserva o histórico original.':'O lançamento deixará de compor as pendências. O histórico será preservado.'}</AlertDialogDescription></AlertDialogHeader>{confirm?.action!=='cancel'&&<div className="field"><Label htmlFor="action-date">Data da realização</Label><Input id="action-date" type="date" max={now} value={actionDate} onChange={e=>{setActionDate(e.target.value);if(confirm)setConfirm({...confirm,key:crypto.randomUUID()});}}/></div>}<div className="field"><Label htmlFor="reason">Motivo {confirm?.action==='settle'?'(opcional)':''}</Label><Textarea id="reason" value={reason} onChange={e=>{setReason(e.target.value);if(confirm)setConfirm({...confirm,key:crypto.randomUUID()});}}/></div>{error&&<Feedback error>{error}</Feedback>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>Voltar</AlertDialogCancel><AlertDialogAction disabled={busy||confirm?.action!=='settle'&&reason.trim().length<3} onClick={e=>{e.preventDefault();void action();}}>{busy?'Registrando…':'Confirmar'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
function Empty({title='Nenhum registro neste período.',description='Altere os filtros ou use o botão de adicionar para começar.',action}:{title?:string;description?:string;action?:React.ReactNode}){return<div className="empty"><span><ArrowLeftRight size={24}/></span><h3>{title}</h3><p>{description}</p>{action&&<div className="empty-actions">{action}</div>}</div>;}
function Organization({api,profile,onSave}:{api:API;profile:Item;onSave:()=>void}){const [name,setName]=useState(text(profile.name));const[busy,setBusy]=useState(false);const[error,setError]=useState('');return<Card className="max-w-2xl"><CardContent><h2>Perfil da organização</h2><form className="editor-form" onSubmit={e=>{e.preventDefault();setBusy(true);void api('/v1/organization-profile','PATCH',{name},profile.version).then(onSave).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}><div className="field"><Label htmlFor="org-name">Nome</Label><Input id="org-name" value={name} onChange={e=>setName(e.target.value)} required/></div><p className="helper">Uma organização, múltiplos CNPJs internos. Moeda: BRL. Fuso: Brasília.</p>{error&&<Feedback error>{error}</Feedback>}<Button disabled={busy}>{busy?'Salvando…':'Salvar alterações'}</Button></form></CardContent></Card>;}
