import {useEffect,useState} from 'react';
import {Download,Copy} from 'lucide-react';
import {AppButton as Button} from './AppButton';
import {Input} from './ui/input';
import {Textarea} from './ui/textarea';
import {Feedback} from './Feedback';
import {Select} from '../Editor';
import {type API,type Item,text,money} from '../lib/api';
import {useCommand} from './EvidenceModules';
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function ReportExports({api,query,groups,can,period}:{api:API;query:string;groups:Item[];can:(r:string,a?:string)=>boolean;period:string}){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const exportWorkbook=async()=>{setBusy(true);setError('');try{const qs=new URLSearchParams(query);qs.delete('after');const r=await api<{base64:string;filename:string;mime:string;entries:number}>(`/v1/reports/accountant.xlsx?${qs}`);download(new Blob([Uint8Array.from(atob(r.base64),c=>c.charCodeAt(0))],{type:r.mime}),r.filename);setMessage(`${r.entries} transações exportadas com extrato, rateios, comprovantes e pendências.`);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const graph=async(copy:boolean)=>{setError('');try{const canvas=document.createElement('canvas');canvas.width=1600;canvas.height=180+Math.max(1,groups.length)*70;const c=canvas.getContext('2d')!;c.fillStyle='#ECEDEA';c.fillRect(0,0,canvas.width,canvas.height);c.fillStyle='#06231D';c.font='bold 32px "Kumbh Sans", sans-serif';c.fillText('Black Finance · Despesas por contexto',48,55);c.font='22px "Kumbh Sans", sans-serif';c.fillText(period+' · BRL · até 30 grupos',48,94);const max=groups.reduce((n,g)=>BigInt(text(g.amount_minor))>n?BigInt(text(g.amount_minor)):n,1n);groups.forEach((g,i)=>{const y=145+i*70;c.fillStyle='#06231D';c.font='20px "Kumbh Sans", sans-serif';const label=text(g.name);c.fillText(label.length>42?label.slice(0,39)+'…':label,48,y+25);c.fillStyle='#076653';c.fillRect(530,y,Number(BigInt(text(g.amount_minor))*760n/max),34);c.fillStyle='#06231D';c.fillText(money(g.amount_minor),1310,y+25);});const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('Não foi possível gerar a imagem.')),'image/png'));if(copy&&navigator.clipboard?.write){await navigator.clipboard.write([new ClipboardItem({'image/png':blob})]);setMessage('Gráfico copiado. Cole no Excel, apresentação ou documento.');}else{download(blob,'black-finance-grafico.png');setMessage(copy?'O navegador não permite copiar imagens. PNG baixado para inserir no Excel.':'Gráfico PNG baixado.');}}catch(e){setError('Não foi possível copiar. Use Baixar gráfico. '+(e as Error).message);}};
 return <section className="report-export"><h3>Enviar para o contador</h3><p>Baixe todas as transações filtradas (até 5.000), com rateios, extratos, links privados dos comprovantes e pendências. Não se limita à página da tabela.</p><div className="module-actions"><Button disabled={busy||!can('exports','create')} onClick={()=>void exportWorkbook()}><Download/>{busy?'Preparando Excel…':'Baixar pacote do contador (XLSX)'}</Button><Button variant="outline" disabled={!groups.length||!can('exports','create')} onClick={()=>void graph(true)}><Copy/>Copiar gráfico</Button><Button variant="outline" disabled={!groups.length||!can('exports','create')} onClick={()=>void graph(false)}><Download/>Baixar gráfico PNG</Button></div>{message&&<Feedback>{message}</Feedback>}{error&&<Feedback error>{error}</Feedback>}<AccountingMappings api={api} can={can}/></section>;
}
function AccountingMappings({api,can}:{api:API;can:(r:string,a?:string)=>boolean}){const [items,setItems]=useState<Item[]>([]),[id,setId]=useState(''),[debit,setDebit]=useState(''),[credit,setCredit]=useState(''),[notes,setNotes]=useState(''),[message,setMessage]=useState(''),[tick,setTick]=useState(0),[busy,setBusy]=useState(false);const command=useCommand(api);useEffect(()=>{void api<{items:Item[]}>('/v1/reports/accounting-mappings').then(r=>setItems(r.items)).catch(e=>setMessage(e.message));},[api,tick]);const choose=(value:string)=>{setId(value);const item=items.find(i=>i.id===value);setDebit(text(item?.debit_code));setCredit(text(item?.credit_code));setNotes(text(item?.notes));};const save=async()=>{setBusy(true);try{await command('/v1/reports/accounting-mappings','PATCH',{category_id:id,debit_code:debit,credit_code:credit,notes},items.find(i=>i.id===id)?.version);setMessage('Mapeamento salvo para a exportação. Não houve lançamento contábil.');setTick(t=>t+1);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}};return <details><summary>Mapeamento de categorias para contas contábeis</summary><p>Informe os códigos combinados com o contador. Campos vazios saem como pendência; o sistema não inventa contas nem escritura automaticamente.</p><div className="module-fields"><label>Categoria<Select label="Categoria do mapeamento" value={id} onChange={choose} options={items.map(i=>({value:i.id,label:text(i.name)}))}/></label><label>Conta de débito<Input value={debit} onChange={e=>setDebit(e.target.value)}/></label><label>Conta de crédito<Input value={credit} onChange={e=>setCredit(e.target.value)}/></label><label>Orientação ao contador<Textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label></div><Button variant="outline" disabled={busy||!id||!can('context','update')||!can('categories','update')} onClick={()=>void save()}>Salvar mapeamento</Button>{message&&<p role="status">{message}</p>}</details>;}
