import {useEffect,useState} from 'react';
import {AppButton as Button} from './AppButton';
import {Input} from './ui/input';
import {Checkbox} from './ui/checkbox';
import {Table,TableHeader,TableHead,TableRow,TableBody,TableCell} from './ui/table';
import {Select} from '../Editor';
import {type API} from '../lib/api';
type Sheet={name:string;rows:number;columns:number;preview:{line:number;cells:string[]}[]};
export async function fileBase64(file:File){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]!);r.onerror=()=>reject(new Error('Não foi possível ler o arquivo.'));r.readAsDataURL(file);});}
export function XlsxImport({api,account,onDone,onError,initialFile,driveId}:{api:API;account:string;onDone:(id:string)=>void;onError:(s:string)=>void;initialFile?:File;driveId?:string}){
 const [file,setFile]=useState<{filename:string;base64:string}>(),[sheets,setSheets]=useState<Sheet[]>([]),[sheet,setSheet]=useState(''),[header,setHeader]=useState(1),[map,setMap]=useState<Record<string,string>>({date:'1',description:'2',amount:'3',debit:'',credit:'',identifier:''}),[mode,setMode]=useState('signed'),[busy,setBusy]=useState(false),[skip,setSkip]=useState<number[]>([]);
 const current=sheets.find(s=>s.name===sheet);const columns=current?Array.from({length:current.columns},(_,i)=>({value:String(i+1),label:`${i+1} · ${current.preview[header-1]?.cells[i]||'Sem cabeçalho'}`})):[];
 const upload=async(f?:File)=>{if(!f)return;setBusy(true);setFile(undefined);setSheets([]);onError('');try{if(!/\.xlsx$/i.test(f.name)||f.size>2000000)throw new Error('Escolha XLSX de até 2 MB.');const raw={filename:f.name,base64:await fileBase64(f)},r=await api<{sheets:Sheet[]}>('/v1/xlsx/inspect','POST',raw);setFile(raw);setSheets(r.sheets);setSheet(r.sheets[0]?.name??'');setSkip([]);}catch(e){onError((e as Error).message);}finally{setBusy(false);}};
 useEffect(()=>{if(initialFile)void upload(initialFile);},[initialFile]);
 const submit=async()=>{if(!file)return;setBusy(true);onError('');try{const r=await api(driveId?`/v1/drive/files/${driveId}/statement`:'/v1/xlsx/import','POST',{...file,account_id:account,sheet,header,date:Number(map.date),description:Number(map.description),amount:mode==='signed'?Number(map.amount):null,debit:mode==='separate'?Number(map.debit):null,credit:mode==='separate'?Number(map.credit):null,identifier:map.identifier?Number(map.identifier):null,skip});onDone(r.id);}catch(e){onError((e as Error).message);}finally{setBusy(false);}};
 return <section className="xlsx-import"><h3>Extrato Excel</h3><p>1. Escolha o arquivo. 2. Confira as colunas. 3. Leve os movimentos para a conciliação.</p>{!initialFile&&<Input aria-label="Extrato XLSX" type="file" accept=".xlsx" disabled={busy} onChange={e=>void upload(e.target.files?.[0])}/>} {busy&&<p role="status">Lendo arquivo…</p>}{current&&<><div className="module-fields"><Select label="Planilha" value={sheet} onChange={v=>{setSheet(v);setSkip([]);}} empty={false} options={sheets.map(s=>({value:s.name,label:s.name}))}/><label>Linha do cabeçalho<Input aria-label="Linha do cabeçalho" type="number" min={1} max={Math.min(100,current.rows)} value={header} onChange={e=>setHeader(Number(e.target.value))}/></label><Select label="Formato dos valores" value={mode} onChange={setMode} empty={false} options={[{value:'signed',label:'Valor com sinal (negativo = saída)'},{value:'separate',label:'Débito e crédito separados'}]}/>{['date','description',...(mode==='signed'?['amount']:['debit','credit']),'identifier'].map(key=><label key={key}>{({date:'Data',description:'Descrição',amount:'Valor',debit:'Débito / saída',credit:'Crédito / entrada',identifier:'Identificador (opcional)'} as Record<string,string>)[key]}<Select label={`Coluna ${key}`} value={map[key]??''} onChange={v=>setMap(m=>({...m,[key]:v}))} options={columns}/></label>)}</div><p>Prévia das primeiras 100 linhas. Marque linhas de saldo ou cabeçalhos adicionais para ignorar. Fórmulas não são calculadas.</p><Table><TableHeader><TableRow><TableHead>Ignorar</TableHead><TableHead>Linha</TableHead>{columns.map(c=><TableHead key={c.value}>{c.value}</TableHead>)}</TableRow></TableHeader><TableBody>{current.preview.filter(r=>r.line>header).map(r=><TableRow key={r.line}><TableCell><Checkbox aria-label={`Ignorar linha ${r.line}`} checked={skip.includes(r.line)} onCheckedChange={v=>setSkip(s=>v?[...s,r.line]:s.filter(x=>x!==r.line))}/></TableCell><TableCell>{r.line}</TableCell>{r.cells.map((c,i)=><TableCell key={i}>{c}</TableCell>)}</TableRow>)}</TableBody></Table><p>Sem identificador, movimentos com a mesma data, descrição, direção e valor são sinalizados como duplicados. A conferência entre arquivos OFX e XLSX exige revisão.</p><Button disabled={busy||!account} onClick={()=>void submit()}>Revisar movimentos na conciliação</Button></>}</section>;
}
