import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import pg from 'pg';
import ExcelJS from 'exceljs';
import {Finance,today,type Context} from '../../packages/domain/src/finance.js';
import {Evidence} from '../../packages/domain/src/evidence.js';
import {Contacts} from '../../packages/domain/src/contacts.js';
import {createPool} from '../../packages/domain/src/db.js';
import {entrySchema} from '../../packages/contracts/src/finance.js';
import {documentSchema,documentReviewSchema,dimensionSchema,contextSchema,accountabilitySchema,mappingSchema} from '../../packages/contracts/src/evidence.js';
test('evidence workflow preserves balances, account isolation, review history and totals with many-to-many links',async t=>{
 const env=JSON.parse(await readFile('.local/test-env.json','utf8'));const url=new URL(env.adminDatabaseUrl);if(!['127.0.0.1','localhost'].includes(url.hostname)||url.port!=='54322')throw new Error('Exige banco local.');
 const admin=new pg.Pool({connectionString:env.adminDatabaseUrl,max:2}),pool=createPool(env.databaseUrl);t.after(async()=>{await pool.end();await admin.end();});const f=new Finance(pool),evidence=new Evidence(f);const actor=(await admin.query('SELECT id FROM app.users WHERE email=$1',[env.email])).rows[0].id;const ctx=(version?:number,key=randomUUID()):Context=>({actor,requestId:randomUUID(),version,key});
 let cnpj=String(Date.now()).slice(-12);for(let round=0;round<2;round++){let sum=0;for(let i=cnpj.length-1,w=2;i>=0;i--,w=w===9?2:w+1)sum+=Number(cnpj[i])*w;cnpj+=String(sum%11<2?0:11-sum%11);}
 const entity=await f.entity(ctx(),{name:'Evidências integração',cnpj,status:'active'});const a=await f.createAccount(ctx(),{legal_entity_id:entity.id,name:'Evidências A',kind:'bank',opening_on:'2020-01-01',opening_minor:'0',is_default:false}),b=await f.createAccount(ctx(),{legal_entity_id:entity.id,name:'Evidências B',kind:'bank',opening_on:'2020-01-01',opening_minor:'0',is_default:false});
 const entry=await f.entry(ctx(),entrySchema.parse({account_id:a.id,title:'Almoço fictício',direction:'expense',amount_minor:'12345',due_on:today(),competence_on:today(),allocations:[{amount_minor:'12345'}]}));const second=await f.entry(ctx(),entrySchema.parse({account_id:a.id,title:'Segunda evidência',direction:'expense',amount_minor:'100',due_on:today(),competence_on:today(),allocations:[{amount_minor:'100'}]}));
 const upload=documentSchema.parse({account_id:a.id,filename:'fixture.pdf',mime:'application/pdf',base64:Buffer.from('%PDF-1.4\nfixture-integration-'+randomUUID()).toString('base64'),text:'Emitente: Restaurante Fictício\nValor total: 123,45\ncontato@example.test',method:'pdf-text',duration_ms:10});const uctx=ctx();const doc=await evidence.upload(uctx,upload);assert.equal((await evidence.upload(uctx,upload)).id,doc.id);assert.equal((await evidence.upload(ctx(),upload)).id,doc.id);assert.equal((await f.listAccounts(ctx())).find(x=>x.id===a.id)?.balance_minor,'0');
 const reviewed=await evidence.reviewDocument(ctx(1),String(doc.id),documentReviewSchema.parse({fields:doc.fields,status:'confirmed',reason:'Conferido com o original'}));await assert.rejects(()=>evidence.reviewDocument(ctx(1),String(doc.id),documentReviewSchema.parse({fields:doc.fields,status:'confirmed',reason:'Versão antiga'})));
 const d1=await evidence.saveDimension(ctx(),dimensionSchema.parse({kind:'institution',name:'Instituição A'})),d2=await evidence.saveDimension(ctx(),dimensionSchema.parse({kind:'institution',name:'Instituição B'})),program=await evidence.saveDimension(ctx(),dimensionSchema.parse({kind:'program',name:'Institucional'}));
 const context=contextSchema.parse({dimension_ids:[d1.id,d2.id,program.id],party_ids:[],document_ids:[doc.id],movement_ids:[],event_ids:[],justification:'Reunião de exemplo',documentation_complete:true,status:'confirmed',reason:'Conferido pelo teste'});await evidence.saveContext(ctx(1),String(entry.id),context);await evidence.saveContext(ctx(1),String(second.id),context);const q=accountabilitySchema.parse({from:today(),to:today(),account_id:a.id});const report=await evidence.report(ctx(),q);assert.equal(report.total.expense_minor,'12445');assert.equal(report.total.count,2);assert.equal(report.total.complete,2);assert.equal(report.groups[0].amount_minor,'12445');const byInstitution=await evidence.report(ctx(),{...q,group_by:'institution'});assert.equal(byInstitution.groups[0].name,'Instituição A + Instituição B');assert.equal(byInstitution.groups[0].amount_minor,'12445');assert.equal((await evidence.report(ctx(),{...q,group_by:'institution',program_group:byInstitution.groups[0].name})).total.expense_minor,'12445');assert.equal((await evidence.report(ctx(),{...q,dimension_id:String(d2.id)})).total.expense_minor,'12445');
 const wrong=await evidence.upload(ctx(),{...upload,account_id:String(b.id)});await assert.rejects(()=>evidence.saveContext(ctx(2),String(entry.id),{...context,document_ids:[String(wrong.id)]}));
 const book=new ExcelJS.Workbook();book.addWorksheet('Extrato').addRows([['Data','Descrição','Valor','ID'],[today(),'Almoço fictício',-123.45,'fixture-'+entry.id]]);const xlsx=mappingSchema.parse({account_id:a.id,filename:'fixture.xlsx',base64:Buffer.from(await book.xlsx.writeBuffer()).toString('base64'),sheet:'Extrato',header:1,date:1,description:2,amount:3,identifier:4,debit:null,credit:null});const batch=await evidence.modules.previewXlsx(ctx(),xlsx);const row=(await evidence.modules.batch(ctx(),String(batch.id))).rows[0];assert.equal((await f.listAccounts(ctx())).find(x=>x.id===a.id)?.balance_minor,'0');await assert.rejects(()=>evidence.modules.reconcile(ctx(1),String(batch.id),row.id,String(entry.id)));await f.mutateEntry(ctx(1),String(entry.id),'settle',{settled_on:today()});const balance=(await f.listAccounts(ctx())).find(x=>x.id===a.id)?.balance_minor;await evidence.modules.reconcile(ctx(1),String(batch.id),row.id,String(entry.id));assert.equal((await f.listAccounts(ctx())).find(x=>x.id===a.id)?.balance_minor,balance);assert.equal((await evidence.report(ctx(),q)).total.reconciled,1);
 const contacts=await new Contacts(f).suggestions(ctx(),String(entry.id));assert.equal(contacts.items[0]?.email,'contato@example.test');
 const restricted=randomUUID();await admin.query('INSERT INTO auth.users(id,email) VALUES($1,$2)',[restricted,`${restricted}@example.test`]);await admin.query("INSERT INTO app.users(id,email,display_name) VALUES($1,$2,'Evidência restrita')",[restricted,`${restricted}@example.test`]);await admin.query('INSERT INTO app.access_policies(user_id,permissions) VALUES($1,$2)',[restricted,['documents:view','context:view','reports:view','entries:view','imports:view']]);assert.equal((await evidence.documents({...ctx(),actor:restricted},q)).items.length,0);await assert.rejects(()=>evidence.context({...ctx(),actor:restricted},String(entry.id)));await assert.rejects(()=>f.transaction({...ctx(),actor:restricted},t=>evidence.document(t,String(doc.id),true)));
 assert.equal(reviewed.status,'confirmed');const history=await evidence.context(ctx(),String(entry.id));assert.ok((history.history as unknown[]).length>=1);
});
