import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import pg from 'pg';
import {Finance,type Context} from '../../packages/domain/src/finance.js';
import {GoogleIntegration} from '../../packages/domain/src/google.js';
import {createPool} from '../../packages/domain/src/db.js';
test('Google flow binds consent to the actor, syncs selected agendas, handles removed events and disconnects',async t=>{
 const env=JSON.parse(await readFile('.local/test-env.json','utf8'));const url=new URL(env.adminDatabaseUrl);if(!['127.0.0.1','localhost'].includes(url.hostname)||url.port!=='54322')throw new Error('Exige banco local.');const admin=new pg.Pool({connectionString:env.adminDatabaseUrl,max:2}),pool=createPool(env.databaseUrl);const previous={...process.env};Object.assign(process.env,{GOOGLE_CLIENT_ID:'fixture-client',GOOGLE_CLIENT_SECRET:'fixture-secret',BETTER_AUTH_SECRET:'fixture-encryption-key',BETTER_AUTH_URL:'https://example.test'});t.after(async()=>{for(const k of ['GOOGLE_CLIENT_ID','GOOGLE_CLIENT_SECRET','BETTER_AUTH_SECRET','BETTER_AUTH_URL'])if(previous[k])process.env[k]=previous[k];else delete process.env[k];await pool.end();await admin.end();});
 const actor=randomUUID();await admin.query('INSERT INTO auth.users(id,email) VALUES($1,$2)',[actor,`${actor}@example.test`]);await admin.query("INSERT INTO app.users(id,email,display_name) VALUES($1,$2,'Google fixture')",[actor,`${actor}@example.test`]);await admin.query('INSERT INTO app.access_policies(user_id,permissions) VALUES($1,$2)',[actor,['integrations:view','integrations:update']]);const ctx=(version?:number):Context=>({actor,version,requestId:randomUUID(),key:randomUUID()});let removed=false,refuse=false;const called:string[]=[];
 const mock:typeof fetch=async(input)=>{const url=String(input);called.push(url);let body:unknown={};if(refuse)return new Response('{}',{status:403});if(url==='https://oauth2.googleapis.com/token')body={access_token:'fixture-access',refresh_token:'fixture-refresh',expires_in:3600};else if(url.includes('/calendarList'))body={items:[{id:'chosen@example.test',summary:'Selecionada'},{id:'other@example.test',summary:'Não selecionada'}]};else if(url.includes('drive/v3/files?'))body={files:[{id:'folder-fixture',name:'Pasta de teste'}]};else if(url.includes('/events?')){assert.ok(url.includes('chosen%40example.test'));body={items:removed?[]:[{id:'event-1',summary:'Almoço com instituição fictícia',status:'confirmed',start:{dateTime:'2026-09-15T12:00:00-03:00'},end:{dateTime:'2026-09-15T13:00:00-03:00'},attendees:[{email:'person@example.test',displayName:'Pessoa fictícia'}]}]};}return new Response(JSON.stringify(body),{headers:{'Content-Type':'application/json'}});};
 const f=new Finance(pool),g=new GoogleIntegration(f,mock);const start=await g.start(ctx()),state=new URL(start.url).searchParams.get('state')!;await g.complete(ctx(),state,'fixture-code');await assert.rejects(()=>g.complete(ctx(),state,'fixture-code'));const status=await g.status(ctx());assert.equal(status.connection.status,'connected');assert.ok(!JSON.stringify(status).includes('fixture-access'));
 await g.settings(ctx(1),{calendars:['chosen@example.test'],folder:'folder-fixture'});assert.equal((await g.sync(ctx(),'2026-09-01','2026-09-30')).count,1);assert.equal((await g.events(ctx(),'2026-09-01','2026-09-30')).items.length,1);removed=true;await g.sync(ctx(),'2026-09-01','2026-09-30');assert.equal((await g.events(ctx(),'2026-09-01','2026-09-30')).items.length,0);refuse=true;await assert.rejects(()=>g.choices(ctx()));refuse=false;await g.disconnect(ctx());assert.equal((await g.events(ctx(),'2026-09-01','2026-09-30')).items.length,0);assert.ok(!called.some(u=>u.includes('/gmail/')));assert.ok(!called.some(u=>u.includes('other%40example.test/events')));
});
