import { readFile, writeFile } from 'node:fs/promises';
import { randomBytes } from 'node:crypto';
import { createClient } from '@supabase/supabase-js';
import pg from 'pg';

// Input comes from `supabase status -o json`, captured to a private local file.
const status = JSON.parse(await readFile('.local/supabase-status.json', 'utf8'));
const database = new URL(status.DB_URL);
if (!['127.0.0.1', 'localhost'].includes(database.hostname) || database.port !== '54322') {
  throw new Error('Bootstrap permitido somente no Supabase local, porta 54322.');
}
const admin = new pg.Pool({ connectionString: database.href, max: 1 });
let credentials: { email: string; password: string; runtimePassword: string };
try { credentials = JSON.parse(await readFile('.local/credentials.json', 'utf8')); }
catch { credentials = { email: 'admin@finance.local', password: randomBytes(24).toString('base64url'), runtimePassword: randomBytes(32).toString('hex') }; }
// Quoted literal generated by PostgreSQL; no credentials enter logs or migrations.
const { rows } = await admin.query<{ statement: string }>(
  "SELECT format('ALTER ROLE app_runtime PASSWORD %L', $1::text) AS statement", [credentials.runtimePassword]);
await admin.query(rows[0]!.statement);
const auth = createClient(status.API_URL, status.SERVICE_ROLE_KEY, { auth: { persistSession: false, autoRefreshToken: false } });
const { data: existing } = await admin.query<{ id: string }>('SELECT id FROM app.users WHERE email = $1', [credentials.email]).then(r => ({ data: r.rows[0] }));
if (!existing) {
  const { data, error } = await auth.auth.admin.createUser({ email: credentials.email, password: credentials.password, email_confirm: true });
  if (error || !data.user) throw new Error('Falha ao criar usuário local.');
  await admin.query('INSERT INTO app.users(id,email,display_name) VALUES($1,$2,$3)', [data.user.id, credentials.email, 'Administrador local']);
}
database.username = 'app_runtime'; database.password = credentials.runtimePassword;
const hostDatabaseUrl = database.href;
database.hostname = 'host.docker.internal';
const publicKey = status.PUBLISHABLE_KEY || status.ANON_KEY;
await writeFile('deploy/.env', [
  `DATABASE_URL=${database.href}`, 'SUPABASE_URL=http://host.docker.internal:54321',
  `SUPABASE_PUBLIC_URL=${status.API_URL}`, `SUPABASE_PUBLISHABLE_KEY=${publicKey}`,
  `JWT_ISSUER=${status.API_URL}/auth/v1`, 'APP_ADDRESS=http://localhost',
  'BIND_ADDRESS=127.0.0.1', 'HTTP_PORT=8080', 'HTTPS_PORT=8443', '',
].join('\n'), { mode: 0o600 });
await writeFile('.local/credentials.json', JSON.stringify(credentials, null, 2), { mode: 0o600 });
await writeFile('.local/test-env.json', JSON.stringify({ databaseUrl: hostDatabaseUrl, adminDatabaseUrl: status.DB_URL, supabaseUrl: status.API_URL, publicKey, ...credentials }), { mode: 0o600 });
await admin.end();
console.log('Ambiente local configurado. Credenciais somente em .local/credentials.json (não versionado).');
