import { generateKeyPair, exportJWK, type JWK } from 'jose';
import { randomUUID } from 'node:crypto';

export async function createLocalSigningKey(): Promise<JWK> {
  const { privateKey } = await generateKeyPair('ES256', { extractable: true });
  return { ...await exportJWK(privateKey), kid: randomUUID(), alg: 'ES256', use: 'sig', key_ops: ['sign'] };
}

export function normalizeLocalSigningKeys(value: unknown): JWK[] {
  if (!Array.isArray(value) || value.length !== 1 || value[0]?.alg !== 'ES256' || !value[0]?.d) {
    throw new Error('Configuração local exige uma chave privada ES256.');
  }
  const key = { ...value[0] } as JWK;
  // Preserve key material and kid when upgrading files generated by the initial scaffold.
  key.key_ops ??= ['sign'];
  if (!key.key_ops.includes('sign')) throw new Error('Chave local não permite assinatura.');
  return [key];
}
