import {createRequire} from 'node:module';
import {dirname,join} from 'node:path';
import {mkdir,copyFile,readdir} from 'node:fs/promises';
const require=createRequire(import.meta.url),root='apps/web/public/ocr';
await mkdir(root,{recursive:true});
const tesseract=dirname(require.resolve('tesseract.js/package.json'));
await copyFile(join(tesseract,'dist/worker.min.js'),join(root,'worker.min.js'));
const nested=createRequire(join(tesseract,'package.json')),core=dirname(nested.resolve('tesseract.js-core/package.json'));
for(const file of await readdir(core))if(/\.wasm(?:\.js)?$/.test(file))await copyFile(join(core,file),join(root,file));
await copyFile(join(dirname(require.resolve('@tesseract.js-data/por/package.json')),'4.0.0/por.traineddata.gz'),join(root,'por.traineddata.gz'));
console.log('OCR em português preparado para execução local no navegador.');
