import {readFile,writeFile} from 'node:fs/promises';import pg from 'pg';
const cloud=process.argv.includes('--cloud');const env=JSON.parse(await readFile(cloud?'.local/cloud-test-env.json':'.local/test-env.json','utf8'));const url=new URL(env.adminDatabaseUrl);if(cloud){const project=JSON.parse(await readFile('.vercel/project.json','utf8'));if(project.projectName!=='black-finance-financeiro-test'||!url.hostname.endsWith('.neon.tech'))throw new Error('Destino de teste inválido.');}else if(!['localhost','127.0.0.1'].includes(url.hostname)||url.port!=='54322')throw new Error('Destino local inválido.');
const db=new pg.Pool({connectionString:env.adminDatabaseUrl,max:1});try{const actor=env.actor??(await db.query('SELECT id FROM app.users WHERE email=$1',[env.email])).rows[0].id;
await db.query('BEGIN');await db.query('SELECT pg_advisory_xact_lock(812712)');const existing=await db.query("SELECT response FROM app.idempotency_records WHERE actor_id=$1 AND key='demo-fixture-v1'",[actor]);if(!existing.rowCount){await db.query("SELECT set_config('app.seed_actor',$1,true)",[actor]);await db.query(await readFile('scripts/seed-demo.sql','utf8'));await db.query("INSERT INTO app.idempotency_records(actor_id,key,payload_hash,response) VALUES($1,'demo-fixture-v1','demo-v1','{\"created\":true}')",[actor]);}await db.query('COMMIT');
const data=(await db.query(`SELECT a.name,l.name AS legal_entity,b.balance_minor,coalesce(p.total,0)::text AS ledger,coalesce(d.total,0)::text AS daily FROM app.accounts a JOIN app.legal_entities l ON l.id=a.legal_entity_id JOIN app.account_balances b ON b.account_id=a.id LEFT JOIN(SELECT account_id,sum(signed_minor) total FROM app.cash_postings GROUP BY account_id)p ON p.account_id=a.id LEFT JOIN(SELECT account_id,sum(net_minor) total FROM app.cash_daily GROUP BY account_id)d ON d.account_id=a.id WHERE l.cnpj IN('12ABC34501DE35','11222333000181') ORDER BY a.id`)).rows;
for(const r of data)if(r.balance_minor!==r.ledger||r.balance_minor!==r.daily)throw new Error('Divergência no dataset de referência.');
const totals=(await db.query(`SELECT e.status,e.direction,count(*)::int AS count,sum(e.amount_minor)::text AS amount_minor FROM app.entries e JOIN app.accounts a ON a.id=e.account_id JOIN app.legal_entities l ON l.id=a.legal_entity_id WHERE l.cnpj IN('12ABC34501DE35','11222333000181') GROUP BY e.status,e.direction ORDER BY e.status,e.direction`)).rows;
await writeFile(`docs/demo-${cloud?'cloud':'local'}-totals.json`,JSON.stringify({accounts:data,entries:totals},null,2));console.log(`Dataset ${cloud?'cloud':'local'} pronto: 2 CNPJs, 4 contas, 200 lançamentos; saldos reconciliados.`);
}catch(e){await db.query('ROLLBACK');throw e;}finally{await db.end();}
